/* ---------------------------------------------------------------------------
   Seaport reference data for shipping documents (packing list, etc.).

   · CHINA_PORTS      — the major Chinese sea/container ports (Port of Loading,
                        since Koleex ships FROM China).
   · PORTS_BY_COUNTRY — destination ports grouped by country (Port of Discharge:
                        pick a country, then a port in that country).
   · COUNTRY_FLAG     — flag emoji per country, shown ONLY inside the dropdown
                        options (the value written onto the packing list is the
                        plain country/port name, no flag).

   Curated, not exhaustive — covers the world's major container ports plus a
   thorough set for Koleex's core markets. The pickers still allow free text,
   so an unlisted port can always be typed.
   --------------------------------------------------------------------------- */

export const CHINA_PORTS: string[] = [
  "Shanghai", "Ningbo-Zhoushan", "Shenzhen", "Guangzhou (Nansha)", "Qingdao",
  "Tianjin", "Xiamen", "Dalian", "Lianyungang", "Yingkou", "Rizhao", "Yantai",
  "Fuzhou", "Quanzhou", "Zhuhai", "Dongguan", "Zhanjiang", "Shantou", "Nantong",
  "Zhongshan", "Weihai", "Jiangyin", "Taicang", "Yangzhou", "Zhenjiang",
  "Wenzhou", "Beihai", "Fangchenggang", "Qinhuangdao", "Haikou", "Yangpu",
  "Jinzhou", "Dandong", "Huanghua", "Jiaxing", "Taizhou", "Wuhu", "Nanjing",
  "Zhangjiagang", "Changshu", "Foshan", "Jingtang", "Hong Kong",
];

export const PORTS_BY_COUNTRY: Record<string, string[]> = {
  Algeria: ["Algiers", "Oran", "Bejaia", "Skikda"],
  Angola: ["Luanda", "Lobito"],
  Argentina: ["Buenos Aires", "Rosario", "La Plata"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Fremantle", "Adelaide"],
  Azerbaijan: ["Baku (Alat)"],
  Bahrain: ["Khalifa Bin Salman"],
  Bangladesh: ["Chittagong (Chattogram)", "Mongla"],
  Belgium: ["Antwerp", "Zeebrugge"],
  Brazil: ["Santos", "Paranagua", "Itajai", "Rio de Janeiro"],
  Brunei: ["Muara"],
  Bulgaria: ["Varna", "Burgas"],
  Cambodia: ["Sihanoukville", "Phnom Penh"],
  Cameroon: ["Douala", "Kribi"],
  Canada: ["Vancouver", "Montreal", "Prince Rupert", "Halifax"],
  Chile: ["San Antonio", "Valparaiso", "Iquique"],
  Colombia: ["Cartagena", "Buenaventura", "Barranquilla"],
  "Costa Rica": ["Puerto Limon / Moin", "Caldera"],
  Croatia: ["Rijeka", "Ploce"],
  Cyprus: ["Limassol", "Larnaca"],
  Denmark: ["Aarhus", "Copenhagen"],
  Djibouti: ["Djibouti", "Doraleh"],
  "Dominican Republic": ["Caucedo", "Haina", "Puerto Plata"],
  Ecuador: ["Guayaquil", "Posorja"],
  Egypt: ["Alexandria", "Port Said", "Damietta", "Ain Sokhna", "Suez", "El Dekheila", "Adabiya", "Safaga"],
  Finland: ["Helsinki", "Kotka", "Hamina"],
  France: ["Le Havre", "Marseille-Fos", "Dunkirk"],
  Georgia: ["Poti", "Batumi"],
  Germany: ["Hamburg", "Bremerhaven", "Wilhelmshaven"],
  Ghana: ["Tema", "Takoradi"],
  Greece: ["Piraeus", "Thessaloniki"],
  Guatemala: ["Puerto Quetzal", "Santo Tomas de Castilla"],
  Honduras: ["Puerto Cortes"],
  India: ["Nhava Sheva (JNPT)", "Mundra", "Chennai", "Kolkata", "Cochin", "Visakhapatnam"],
  Indonesia: ["Tanjung Priok (Jakarta)", "Tanjung Perak (Surabaya)", "Belawan"],
  Iran: ["Bandar Abbas (Shahid Rajaee)", "Bushehr", "Bandar Imam Khomeini"],
  Iraq: ["Umm Qasr", "Basra"],
  Ireland: ["Dublin", "Cork"],
  Israel: ["Haifa", "Ashdod"],
  Italy: ["Genoa", "Gioia Tauro", "La Spezia", "Naples", "Livorno", "Trieste"],
  "Ivory Coast": ["Abidjan", "San Pedro"],
  Jamaica: ["Kingston"],
  Japan: ["Tokyo", "Yokohama", "Kobe", "Nagoya", "Osaka"],
  Jordan: ["Aqaba"],
  Kazakhstan: ["Aktau", "Kuryk"],
  Kenya: ["Mombasa"],
  Kuwait: ["Shuwaikh", "Shuaiba"],
  Lebanon: ["Beirut", "Tripoli"],
  Libya: ["Tripoli", "Benghazi", "Misrata"],
  Malaysia: ["Port Klang", "Tanjung Pelepas", "Penang"],
  Maldives: ["Male"],
  Malta: ["Marsaxlokk", "Valletta"],
  Mexico: ["Manzanillo", "Veracruz", "Lazaro Cardenas"],
  Morocco: ["Casablanca", "Tanger Med"],
  Mozambique: ["Maputo", "Beira", "Nacala"],
  Myanmar: ["Yangon", "Thilawa"],
  Netherlands: ["Rotterdam", "Amsterdam"],
  "New Zealand": ["Auckland", "Tauranga", "Lyttelton"],
  Nigeria: ["Lagos (Apapa)", "Lagos (Tin Can)", "Onne"],
  Norway: ["Oslo", "Bergen"],
  Oman: ["Sohar", "Salalah", "Muscat"],
  Pakistan: ["Karachi", "Port Qasim", "Gwadar"],
  Panama: ["Balboa", "Colon", "Manzanillo (PSA)"],
  Peru: ["Callao", "Paita"],
  Philippines: ["Manila", "Cebu"],
  Poland: ["Gdansk", "Gdynia", "Szczecin-Swinoujscie"],
  Portugal: ["Lisbon", "Leixoes", "Sines"],
  Qatar: ["Hamad Port (Doha)"],
  Romania: ["Constanta"],
  Russia: ["Novorossiysk", "St Petersburg", "Vladivostok"],
  "Saudi Arabia": ["Jeddah", "Dammam", "Jubail", "King Abdullah Port"],
  Senegal: ["Dakar"],
  Singapore: ["Singapore"],
  Slovenia: ["Koper"],
  "South Africa": ["Durban", "Cape Town", "Port Elizabeth"],
  "South Korea": ["Busan", "Incheon", "Gwangyang"],
  Spain: ["Valencia", "Algeciras", "Barcelona", "Bilbao"],
  "Sri Lanka": ["Colombo", "Hambantota"],
  Sudan: ["Port Sudan"],
  Sweden: ["Gothenburg", "Helsingborg"],
  Syria: ["Latakia", "Tartus"],
  Taiwan: ["Kaohsiung", "Keelung", "Taichung", "Taipei"],
  Tanzania: ["Dar es Salaam"],
  Thailand: ["Laem Chabang", "Bangkok"],
  "Trinidad and Tobago": ["Port of Spain", "Point Lisas"],
  Tunisia: ["Rades", "Sfax"],
  Turkey: ["Istanbul (Ambarli)", "Mersin", "Izmir", "Gemlik", "Iskenderun"],
  Ukraine: ["Odessa", "Chornomorsk", "Pivdennyi"],
  "United Arab Emirates": ["Jebel Ali (Dubai)", "Khalifa (Abu Dhabi)", "Sharjah"],
  "United Kingdom": ["Felixstowe", "Southampton", "London Gateway", "Liverpool", "Immingham"],
  "United States": ["Los Angeles", "Long Beach", "New York/New Jersey", "Savannah", "Houston", "Seattle", "Oakland", "Norfolk", "Charleston", "Miami"],
  Uruguay: ["Montevideo"],
  Vietnam: ["Ho Chi Minh (Cat Lai)", "Hai Phong", "Cai Mep", "Da Nang"],
  Yemen: ["Aden", "Hodeidah", "Mukalla"],
  Albania: ["Durres", "Vlore"],
  Bahamas: ["Freeport", "Nassau"],
  Barbados: ["Bridgetown"],
  Belize: ["Belize City", "Big Creek"],
  Benin: ["Cotonou"],
  "Cape Verde": ["Praia", "Mindelo"],
  Comoros: ["Moroni"],
  "Congo (Republic)": ["Pointe-Noire"],
  Cuba: ["Havana", "Mariel", "Santiago de Cuba"],
  "DR Congo": ["Matadi", "Banana"],
  "El Salvador": ["Acajutla", "La Union"],
  "Equatorial Guinea": ["Malabo", "Bata"],
  Eritrea: ["Massawa", "Assab"],
  Estonia: ["Tallinn"],
  Fiji: ["Suva", "Lautoka"],
  Gabon: ["Libreville", "Owendo", "Port-Gentil"],
  Gambia: ["Banjul"],
  Guinea: ["Conakry"],
  "Guinea-Bissau": ["Bissau"],
  Guyana: ["Georgetown"],
  Haiti: ["Port-au-Prince", "Cap-Haitien"],
  Iceland: ["Reykjavik", "Reykjanesbaer"],
  Latvia: ["Riga", "Ventspils", "Liepaja"],
  Liberia: ["Monrovia"],
  Lithuania: ["Klaipeda"],
  Madagascar: ["Toamasina (Tamatave)"],
  Mauritania: ["Nouakchott", "Nouadhibou"],
  Mauritius: ["Port Louis"],
  Montenegro: ["Bar"],
  Namibia: ["Walvis Bay", "Luderitz"],
  "New Caledonia": ["Noumea"],
  Nicaragua: ["Corinto"],
  "Papua New Guinea": ["Port Moresby", "Lae"],
  Samoa: ["Apia"],
  "Sao Tome and Principe": ["Sao Tome"],
  Seychelles: ["Victoria"],
  "Sierra Leone": ["Freetown"],
  "Solomon Islands": ["Honiara"],
  Somalia: ["Mogadishu", "Berbera", "Bosaso"],
  Suriname: ["Paramaribo"],
  "Timor-Leste": ["Dili"],
  Togo: ["Lome"],
  Tonga: ["Nuku'alofa"],
  Turkmenistan: ["Turkmenbashi"],
  Vanuatu: ["Port Vila"],
  Venezuela: ["La Guaira", "Puerto Cabello", "Maracaibo"],
};

/* Flag emoji per country — displayed ONLY in the dropdown option list, never
   written into the document value. */
export const COUNTRY_FLAG: Record<string, string> = {
  Algeria: "🇩🇿", Angola: "🇦🇴", Argentina: "🇦🇷", Australia: "🇦🇺", Azerbaijan: "🇦🇿",
  Bahrain: "🇧🇭", Bangladesh: "🇧🇩", Belgium: "🇧🇪", Brazil: "🇧🇷", Brunei: "🇧🇳",
  Bulgaria: "🇧🇬", Cambodia: "🇰🇭", Cameroon: "🇨🇲", Canada: "🇨🇦", Chile: "🇨🇱",
  Colombia: "🇨🇴", "Costa Rica": "🇨🇷", Croatia: "🇭🇷", Cyprus: "🇨🇾", Denmark: "🇩🇰",
  Djibouti: "🇩🇯", "Dominican Republic": "🇩🇴", Ecuador: "🇪🇨", Egypt: "🇪🇬", Finland: "🇫🇮",
  France: "🇫🇷", Georgia: "🇬🇪", Germany: "🇩🇪", Ghana: "🇬🇭", Greece: "🇬🇷",
  Guatemala: "🇬🇹", Honduras: "🇭🇳", India: "🇮🇳", Indonesia: "🇮🇩", Iran: "🇮🇷",
  Iraq: "🇮🇶", Ireland: "🇮🇪", Israel: "🇮🇱", Italy: "🇮🇹", "Ivory Coast": "🇨🇮",
  Jamaica: "🇯🇲", Japan: "🇯🇵", Jordan: "🇯🇴", Kazakhstan: "🇰🇿", Kenya: "🇰🇪",
  Kuwait: "🇰🇼", Lebanon: "🇱🇧", Libya: "🇱🇾", Malaysia: "🇲🇾", Maldives: "🇲🇻",
  Malta: "🇲🇹", Mexico: "🇲🇽", Morocco: "🇲🇦", Mozambique: "🇲🇿", Myanmar: "🇲🇲",
  Netherlands: "🇳🇱", "New Zealand": "🇳🇿", Nigeria: "🇳🇬", Norway: "🇳🇴", Oman: "🇴🇲",
  Pakistan: "🇵🇰", Panama: "🇵🇦", Peru: "🇵🇪", Philippines: "🇵🇭", Poland: "🇵🇱",
  Portugal: "🇵🇹", Qatar: "🇶🇦", Romania: "🇷🇴", Russia: "🇷🇺", "Saudi Arabia": "🇸🇦",
  Senegal: "🇸🇳", Singapore: "🇸🇬", Slovenia: "🇸🇮", "South Africa": "🇿🇦", "South Korea": "🇰🇷",
  Spain: "🇪🇸", "Sri Lanka": "🇱🇰", Sudan: "🇸🇩", Sweden: "🇸🇪", Syria: "🇸🇾",
  Taiwan: "🇹🇼", Tanzania: "🇹🇿", Thailand: "🇹🇭", "Trinidad and Tobago": "🇹🇹", Tunisia: "🇹🇳",
  Turkey: "🇹🇷", Ukraine: "🇺🇦", "United Arab Emirates": "🇦🇪", "United Kingdom": "🇬🇧", "United States": "🇺🇸",
  Uruguay: "🇺🇾", Vietnam: "🇻🇳", Yemen: "🇾🇪",
  Albania: "🇦🇱", Bahamas: "🇧🇸", Barbados: "🇧🇧", Belize: "🇧🇿", Benin: "🇧🇯",
  "Cape Verde": "🇨🇻", Comoros: "🇰🇲", "Congo (Republic)": "🇨🇬", Cuba: "🇨🇺", "DR Congo": "🇨🇩",
  "El Salvador": "🇸🇻", "Equatorial Guinea": "🇬🇶", Eritrea: "🇪🇷", Estonia: "🇪🇪", Fiji: "🇫🇯",
  Gabon: "🇬🇦", Gambia: "🇬🇲", Guinea: "🇬🇳", "Guinea-Bissau": "🇬🇼", Guyana: "🇬🇾",
  Haiti: "🇭🇹", Iceland: "🇮🇸", Latvia: "🇱🇻", Liberia: "🇱🇷", Lithuania: "🇱🇹",
  Madagascar: "🇲🇬", Mauritania: "🇲🇷", Mauritius: "🇲🇺", Montenegro: "🇲🇪", Namibia: "🇳🇦",
  "New Caledonia": "🇳🇨", Nicaragua: "🇳🇮", "Papua New Guinea": "🇵🇬", Samoa: "🇼🇸", "Sao Tome and Principe": "🇸🇹",
  Seychelles: "🇸🇨", "Sierra Leone": "🇸🇱", "Solomon Islands": "🇸🇧", Somalia: "🇸🇴", Suriname: "🇸🇷",
  "Timor-Leste": "🇹🇱", Togo: "🇹🇬", Tonga: "🇹🇴", Turkmenistan: "🇹🇲", Vanuatu: "🇻🇺", Venezuela: "🇻🇪",
};

export const PORT_COUNTRIES: string[] = Object.keys(PORTS_BY_COUNTRY).sort();
