/* ---------------------------------------------------------------------------
   Job titles for cards, badges and signatures — the Hub's positions plus the
   titles a machinery trader and maker uses (owner, 29/09/2026: "all
   possible titles"), each in English, Chinese and Arabic, by group.
   English is the key; a title typed by hand stays as typed.
   --------------------------------------------------------------------------- */

export const TITLE_GROUPS = ["executive", "management", "sales", "marketing", "service", "engineering", "production", "supply", "finance", "people", "it", "legal", "admin", "partners", "other"] as const;
export type TitleGroup = (typeof TITLE_GROUPS)[number];
export interface TitleEntry { en: string; zh: string; ar: string; group: TitleGroup }

/* [en, zh, ar, group] */
const ROWS: Array<[string, string, string, TitleGroup]> = [
  ["Board Member", "董事", "عضو مجلس الإدارة", "executive"],
  ["Chairman", "董事长", "رئيس مجلس الإدارة", "executive"],
  ["Chief Accountant", "总会计师", "رئيس الحسابات", "executive"],
  ["Chief Commercial Officer (CCO)", "首席商务官", "الرئيس التجاري", "executive"],
  ["Chief Communications Officer (CCO)", "首席传播官", "رئيس الاتصال المؤسسي", "executive"],
  ["Chief Digital Officer (CDO)", "首席数字官", "رئيس التحول الرقمي", "executive"],
  ["Chief Executive Officer (CEO)", "首席执行官", "الرئيس التنفيذي", "executive"],
  ["Chief Financial Officer (CFO)", "首席财务官", "المدير المالي", "executive"],
  ["Chief Human Resources Officer (CHRO)", "首席人力资源官", "رئيس الموارد البشرية التنفيذي", "executive"],
  ["Chief Information Officer (CIO)", "首席信息官", "رئيس نظم المعلومات", "executive"],
  ["Chief Legal Officer (CLO)", "首席法务官", "الرئيس القانوني", "executive"],
  ["Chief Marketing Officer (CMO)", "首席营销官", "رئيس التسويق التنفيذي", "executive"],
  ["Chief of Staff", "幕僚长", "رئيس ديوان الإدارة", "executive"],
  ["Chief Operating Officer (COO)", "首席运营官", "مدير العمليات", "executive"],
  ["Chief Procurement Officer", "首席采购官", "رئيس المشتريات التنفيذي", "executive"],
  ["Chief Product Officer (CPO)", "首席产品官", "رئيس المنتجات", "executive"],
  ["Chief Quality Officer", "首席质量官", "رئيس الجودة التنفيذي", "executive"],
  ["Chief Sales Officer (CSO)", "首席销售官", "رئيس المبيعات التنفيذي", "executive"],
  ["Chief Strategy Officer", "首席战略官", "رئيس الاستراتيجية", "executive"],
  ["Chief Technology Officer (CTO)", "首席技术官", "مدير التكنولوجيا", "executive"],
  ["Co-Founder", "联合创始人", "شريك مؤسس", "executive"],
  ["Deputy General Manager", "副总经理", "نائب المدير العام", "executive"],
  ["Executive Director", "执行董事", "المدير التنفيذي", "executive"],
  ["Executive Vice President", "执行副总裁", "نائب الرئيس التنفيذي", "executive"],
  ["Founder", "创始人", "المؤسس", "executive"],
  ["Founder & CEO", "创始人兼首席执行官", "المؤسس والرئيس التنفيذي", "executive"],
  ["General Manager (GM)", "总经理", "المدير العام", "executive"],
  ["Head of Administration", "行政总监", "رئيس الشؤون الإدارية", "executive"],
  ["Head of After-Sales", "售后总监", "رئيس خدمات ما بعد البيع", "executive"],
  ["Head of Business Development", "业务拓展总监", "رئيس تطوير الأعمال", "executive"],
  ["Head of Customer Service", "客户服务总监", "رئيس خدمة العملاء", "executive"],
  ["Head of Design", "设计总监", "رئيس التصميم", "executive"],
  ["Head of E-commerce", "电商总监", "رئيس التجارة الإلكترونية", "executive"],
  ["Head of Finance", "财务总监", "رئيس الشؤون المالية", "executive"],
  ["Head of HR", "人力资源总监", "رئيس الموارد البشرية", "executive"],
  ["Head of IT", "信息技术总监", "رئيس تقنية المعلومات", "executive"],
  ["Head of Legal", "法务总监", "رئيس الشؤون القانونية", "executive"],
  ["Head of Logistics", "物流总监", "رئيس اللوجستيات", "executive"],
  ["Head of Marketing", "市场总监", "رئيس التسويق", "executive"],
  ["Head of PR", "公关总监", "رئيس العلاقات العامة", "executive"],
  ["Head of Procurement", "采购总监", "رئيس المشتريات", "executive"],
  ["Head of Production", "生产总监", "رئيس الإنتاج", "executive"],
  ["Head of Quality", "质量总监", "رئيس الجودة", "executive"],
  ["Head of Sales", "销售总监", "رئيس المبيعات", "executive"],
  ["Managing Director", "董事总经理", "العضو المنتدب", "executive"],
  ["Owner", "企业主", "المالك", "executive"],
  ["Partner", "合伙人", "شريك", "executive"],
  ["President", "总裁", "الرئيس", "executive"],
  ["Vice Chairman", "副董事长", "نائب رئيس مجلس الإدارة", "executive"],
  ["Vice President", "副总裁", "نائب الرئيس", "executive"],
  ["Assistant Manager", "助理经理", "مساعد المدير", "management"],
  ["Branch Manager", "分公司经理", "مدير الفرع", "management"],
  ["Country Manager", "国家经理", "مدير الدولة", "management"],
  ["Department Manager", "部门经理", "مدير القسم", "management"],
  ["Operations Director", "运营总监", "مدير العمليات", "management"],
  ["Operations Manager", "运营经理", "مدير التشغيل", "management"],
  ["Program Manager", "项目群经理", "مدير البرامج", "management"],
  ["Project Coordinator", "项目协调员", "منسق المشروع", "management"],
  ["Project Manager", "项目经理", "مدير المشروع", "management"],
  ["Regional Director", "区域总监", "المدير الإقليمي", "management"],
  ["Team Leader", "组长", "قائد الفريق", "management"],
  ["Account Executive", "客户专员", "تنفيذي حسابات", "sales"],
  ["Account Manager", "客户经理", "مدير حسابات", "sales"],
  ["Application Engineer", "应用工程师", "مهندس تطبيقات", "sales"],
  ["Area Sales Manager", "区域销售经理", "مدير مبيعات المنطقة", "sales"],
  ["Business Development Director", "业务拓展总监", "مدير تطوير الأعمال التنفيذي", "sales"],
  ["Business Development Executive", "业务拓展专员", "تنفيذي تطوير الأعمال", "sales"],
  ["Business Development Manager", "业务拓展经理", "مدير تطوير الأعمال", "sales"],
  ["E-commerce Manager", "电商经理", "مدير التجارة الإلكترونية", "sales"],
  ["Export Manager", "出口经理", "مدير التصدير", "sales"],
  ["Export Sales Manager", "出口销售经理", "مدير مبيعات التصدير", "sales"],
  ["International Sales Manager", "国际销售经理", "مدير المبيعات الدولية", "sales"],
  ["Key Account Manager", "大客户经理", "مدير الحسابات الرئيسية", "sales"],
  ["Market Expansion Specialist", "市场拓展专员", "أخصائي التوسع في الأسواق", "sales"],
  ["Marketplace Specialist", "电商平台专员", "أخصائي المنصات الإلكترونية", "sales"],
  ["Online Store Manager", "网店经理", "مدير المتجر الإلكتروني", "sales"],
  ["Product Listing Specialist", "产品上架专员", "أخصائي إدراج المنتجات", "sales"],
  ["Regional Sales Manager", "区域销售经理", "مدير المبيعات الإقليمي", "sales"],
  ["Retail Sales Associate", "零售销售顾问", "موظف مبيعات التجزئة", "sales"],
  ["Sales Assistant", "销售助理", "مساعد مبيعات", "sales"],
  ["Sales Consultant", "销售顾问", "مستشار مبيعات", "sales"],
  ["Sales Coordinator", "销售协调员", "منسق مبيعات", "sales"],
  ["Sales Director", "销售总监", "مدير المبيعات", "sales"],
  ["Sales Engineer", "销售工程师", "مهندس مبيعات", "sales"],
  ["Sales Executive", "销售专员", "تنفيذي مبيعات", "sales"],
  ["Sales Manager", "销售经理", "مدير المبيعات", "sales"],
  ["Sales Representative", "销售代表", "مندوب مبيعات", "sales"],
  ["Sales Supervisor", "销售主管", "مشرف مبيعات", "sales"],
  ["Sales Trainee", "销售实习生", "متدرب مبيعات", "sales"],
  ["Senior Sales Executive", "高级销售专员", "تنفيذي مبيعات أول", "sales"],
  ["Showroom Manager", "展厅经理", "مدير صالة العرض", "sales"],
  ["Showroom Sales", "展厅销售", "مبيعات صالة العرض", "sales"],
  ["Store Manager", "门店经理", "مدير المعرض", "sales"],
  ["Technical Sales Engineer", "技术销售工程师", "مهندس مبيعات فني", "sales"],
  ["3D Designer", "3D设计师", "مصمم ثلاثي الأبعاد", "marketing"],
  ["Art Director", "艺术总监", "المدير الفني", "marketing"],
  ["Brand Manager", "品牌经理", "مدير العلامة التجارية", "marketing"],
  ["Communications Manager", "传播经理", "مدير الاتصال", "marketing"],
  ["Communications Officer", "传播专员", "مسؤول الاتصال", "marketing"],
  ["Community Manager", "社群经理", "مدير المجتمع الرقمي", "marketing"],
  ["Content Creator", "内容创作者", "صانع محتوى", "marketing"],
  ["Content Manager", "内容经理", "مدير المحتوى", "marketing"],
  ["Copywriter", "文案策划", "كاتب إعلانات", "marketing"],
  ["Creative Director", "创意总监", "المدير الإبداعي", "marketing"],
  ["Designer", "设计师", "مصمم", "marketing"],
  ["E-commerce Photographer", "电商摄影师", "مصور التجارة الإلكترونية", "marketing"],
  ["Email Marketing Specialist", "邮件营销专员", "أخصائي التسويق عبر البريد الإلكتروني", "marketing"],
  ["Event Coordinator", "活动协调员", "منسق فعاليات", "marketing"],
  ["Events Manager", "活动经理", "مدير الفعاليات", "marketing"],
  ["Exhibition Manager", "展会经理", "مدير المعارض", "marketing"],
  ["Graphic Designer", "平面设计师", "مصمم جرافيك", "marketing"],
  ["Industrial Product Designer", "工业产品设计师", "مصمم منتجات صناعية", "marketing"],
  ["Marketing Analyst", "市场分析师", "محلل تسويق", "marketing"],
  ["Marketing Coordinator", "市场协调员", "منسق تسويق", "marketing"],
  ["Marketing Director", "市场总监", "مدير التسويق التنفيذي", "marketing"],
  ["Marketing Manager", "市场经理", "مدير التسويق", "marketing"],
  ["Marketing Specialist", "市场专员", "أخصائي تسويق", "marketing"],
  ["Media Relations Officer", "媒体关系专员", "مسؤول العلاقات الإعلامية", "marketing"],
  ["Motion Designer", "动效设计师", "مصمم موشن جرافيك", "marketing"],
  ["Photographer", "摄影师", "مصور", "marketing"],
  ["PR Director", "公关总监", "مدير العلاقات العامة التنفيذي", "marketing"],
  ["PR Manager", "公关经理", "مدير العلاقات العامة", "marketing"],
  ["PR Specialist", "公关专员", "أخصائي العلاقات العامة", "marketing"],
  ["Product Manager", "产品经理", "مدير المنتج", "marketing"],
  ["Product Specialist", "产品专员", "أخصائي منتجات", "marketing"],
  ["Senior Graphic Designer", "高级平面设计师", "مصمم جرافيك أول", "marketing"],
  ["SEO Specialist", "SEO 专员", "أخصائي تحسين محركات البحث", "marketing"],
  ["Social Media Specialist", "社交媒体专员", "أخصائي وسائل التواصل الاجتماعي", "marketing"],
  ["Video Editor", "视频剪辑师", "محرر فيديو", "marketing"],
  ["Videographer", "摄像师", "مصور فيديو", "marketing"],
  ["After-Sales Engineer", "售后工程师", "مهندس خدمات ما بعد البيع", "service"],
  ["After-Sales Manager", "售后经理", "مدير خدمات ما بعد البيع", "service"],
  ["Calibration Technician", "校准技术员", "فني معايرة", "service"],
  ["Commissioning Engineer", "调试工程师", "مهندس تشغيل وتجهيز", "service"],
  ["Complaints Officer", "投诉专员", "مسؤول الشكاوى", "service"],
  ["Customer Service Manager", "客户服务经理", "مدير خدمة العملاء", "service"],
  ["Customer Service Supervisor", "客户服务主管", "مشرف خدمة العملاء", "service"],
  ["Customer Success Manager", "客户成功经理", "مدير نجاح العملاء", "service"],
  ["Customer Success Specialist", "客户成功专员", "أخصائي نجاح العملاء", "service"],
  ["Embroidery Machine Technician", "绣花机技术员", "فني ماكينات تطريز", "service"],
  ["Field Service Engineer", "现场服务工程师", "مهندس خدمة ميدانية", "service"],
  ["Field Technician", "现场技术员", "فني ميداني", "service"],
  ["Installation Engineer", "安装工程师", "مهندس تركيب", "service"],
  ["Installation Technician", "安装技术员", "فني تركيب", "service"],
  ["Machine Technician", "设备技术员", "فني ماكينات", "service"],
  ["Senior Service Engineer", "高级服务工程师", "مهندس خدمة أول", "service"],
  ["Service Director", "服务总监", "مدير الخدمة التنفيذي", "service"],
  ["Service Engineer", "服务工程师", "مهندس خدمة", "service"],
  ["Service Manager", "服务经理", "مدير الخدمة", "service"],
  ["Service Technician", "服务技术员", "فني خدمة", "service"],
  ["Sewing Machine Mechanic", "缝纫机机修工", "ميكانيكي ماكينات خياطة", "service"],
  ["Sewing Machine Technician", "缝纫机技术员", "فني ماكينات خياطة", "service"],
  ["Spare Parts Coordinator", "配件协调员", "منسق قطع الغيار", "service"],
  ["Spare Parts Manager", "配件经理", "مدير قطع الغيار", "service"],
  ["Technical Support Engineer", "技术支持工程师", "مهندس دعم فني", "service"],
  ["Warranty Officer", "保修专员", "مسؤول الضمان", "service"],
  ["Automation Engineer", "自动化工程师", "مهندس أتمتة", "engineering"],
  ["Design Engineer", "设计工程师", "مهندس تصميم", "engineering"],
  ["Electrical Engineer", "电气工程师", "مهندس كهربائي", "engineering"],
  ["Embedded Systems Engineer", "嵌入式工程师", "مهندس أنظمة مدمجة", "engineering"],
  ["Industrial Engineer", "工业工程师", "مهندس صناعي", "engineering"],
  ["Mechanical Engineer", "机械工程师", "مهندس ميكانيكي", "engineering"],
  ["Process Engineer", "工艺工程师", "مهندس عمليات", "engineering"],
  ["R&D Engineer", "研发工程师", "مهندس بحث وتطوير", "engineering"],
  ["R&D Manager", "研发经理", "مدير البحث والتطوير", "engineering"],
  ["Supplier Quality Engineer", "供应商质量工程师", "مهندس جودة الموردين", "engineering"],
  ["Technical Director", "技术总监", "المدير الفني التقني", "engineering"],
  ["Test Engineer", "测试工程师", "مهندس اختبار", "engineering"],
  ["Assembly Operator", "装配操作员", "عامل تجميع", "production"],
  ["Factory Manager", "工厂经理", "مدير المصنع", "production"],
  ["Final Inspection Officer", "终检专员", "مسؤول الفحص النهائي", "production"],
  ["Garment Technologist", "服装技术员", "أخصائي تكنولوجيا الملابس", "production"],
  ["Incoming Inspection Officer", "来料检验专员", "مسؤول فحص الوارد", "production"],
  ["Line Leader", "线长", "قائد الخط", "production"],
  ["Machine Operator", "机器操作员", "مشغل ماكينات", "production"],
  ["Pattern Maker", "打版师", "صانع باترون", "production"],
  ["Plant Manager", "厂长", "مدير المصنع", "production"],
  ["Production Manager", "生产经理", "مدير الإنتاج", "production"],
  ["Production Planner", "生产计划员", "مخطط الإنتاج", "production"],
  ["Production Supervisor", "生产主管", "مشرف الإنتاج", "production"],
  ["QA Manager", "质量保证经理", "مدير ضمان الجودة", "production"],
  ["Quality Engineer", "质量工程师", "مهندس جودة", "production"],
  ["Quality Inspector", "质检员", "مفتش جودة", "production"],
  ["Quality Manager", "质量经理", "مدير الجودة", "production"],
  ["Textile Engineer", "纺织工程师", "مهندس نسيج", "production"],
  ["Workshop Foreman", "车间主任", "رئيس الورشة", "production"],
  ["Workshop Manager", "车间经理", "مدير الورشة", "production"],
  ["Buyer", "采购员", "مشتري", "supply"],
  ["Company Driver", "公司司机", "سائق الشركة", "supply"],
  ["Container Planner", "集装箱配载员", "مخطط الحاويات", "supply"],
  ["Customs Broker", "报关员", "مخلص جمركي", "supply"],
  ["Customs Clearance Specialist", "报关专员", "أخصائي التخليص الجمركي", "supply"],
  ["Delivery Driver", "送货司机", "سائق توصيل", "supply"],
  ["Document Controller", "文控专员", "مراقب الوثائق", "supply"],
  ["Export Documentation Officer", "出口单证专员", "مسؤول مستندات التصدير", "supply"],
  ["Freight Forwarding Coordinator", "货运代理协调员", "منسق الشحن", "supply"],
  ["Import Manager", "进口经理", "مدير الاستيراد", "supply"],
  ["Import/Export Specialist", "进出口专员", "أخصائي الاستيراد والتصدير", "supply"],
  ["Logistics Coordinator", "物流协调员", "منسق لوجستي", "supply"],
  ["Logistics Director", "物流总监", "مدير اللوجستيات التنفيذي", "supply"],
  ["Logistics Manager", "物流经理", "مدير اللوجستيات", "supply"],
  ["Merchandiser", "跟单员", "منسق طلبيات", "supply"],
  ["Procurement Manager", "采购经理", "مدير المشتريات", "supply"],
  ["Procurement Officer", "采购专员", "مسؤول مشتريات", "supply"],
  ["Purchasing Coordinator", "采购协调员", "منسق المشتريات", "supply"],
  ["Senior Buyer", "高级采购员", "مشتري أول", "supply"],
  ["Shipping Coordinator", "船务协调员", "منسق الشحن البحري", "supply"],
  ["Sourcing Manager", "寻源经理", "مدير التوريد", "supply"],
  ["Sourcing Specialist", "寻源专员", "أخصائي توريد", "supply"],
  ["Supply Chain Manager", "供应链经理", "مدير سلسلة الإمداد", "supply"],
  ["Warehouse Clerk", "仓库文员", "كاتب مستودع", "supply"],
  ["Warehouse Keeper", "仓库管理员", "أمين المستودع", "supply"],
  ["Warehouse Manager", "仓库经理", "مدير المستودع", "supply"],
  ["Warehouse Supervisor", "仓库主管", "مشرف المستودع", "supply"],
  ["Accountant", "会计", "محاسب", "finance"],
  ["Auditor", "审计师", "مدقق حسابات", "finance"],
  ["Bookkeeper", "记账员", "ماسك دفاتر", "finance"],
  ["Cashier", "出纳", "أمين الصندوق", "finance"],
  ["Collections Officer", "收款专员", "مسؤول التحصيل", "finance"],
  ["Credit Controller", "信用控制专员", "مراقب الائتمان", "finance"],
  ["Credit Manager", "信用经理", "مدير الائتمان", "finance"],
  ["Finance Manager", "财务经理", "مدير مالي", "finance"],
  ["Financial Analyst", "财务分析师", "محلل مالي", "finance"],
  ["Financial Controller", "财务主管", "المراقب المالي", "finance"],
  ["Investment Manager", "投资经理", "مدير الاستثمار", "finance"],
  ["Investor Relations Officer", "投资者关系专员", "مسؤول علاقات المستثمرين", "finance"],
  ["Junior Accountant", "初级会计", "محاسب مبتدئ", "finance"],
  ["Price Analyst", "价格分析师", "محلل أسعار", "finance"],
  ["Senior Accountant", "高级会计", "محاسب أول", "finance"],
  ["Tax Specialist", "税务专员", "أخصائي ضرائب", "finance"],
  ["Treasurer", "司库", "أمين الخزينة", "finance"],
  ["HR Assistant", "人事助理", "مساعد موارد بشرية", "people"],
  ["HR Business Partner", "人力资源业务伙伴", "شريك أعمال الموارد البشرية", "people"],
  ["HR Director", "人力资源总监", "مدير الموارد البشرية التنفيذي", "people"],
  ["HR Generalist", "人事专员", "أخصائي موارد بشرية", "people"],
  ["HR Manager", "人力资源经理", "مدير الموارد البشرية", "people"],
  ["HR Supervisor", "人力资源主管", "مشرف الموارد البشرية", "people"],
  ["Payroll Officer", "薪酬专员", "مسؤول الرواتب", "people"],
  ["Recruitment Specialist", "招聘专员", "أخصائي توظيف", "people"],
  ["Talent Acquisition Manager", "人才招聘经理", "مدير استقطاب المواهب", "people"],
  ["Technical Trainer", "技术培训师", "مدرب فني", "people"],
  ["Trainer", "培训师", "مدرب", "people"],
  ["Training Coordinator", "培训协调员", "منسق التدريب", "people"],
  ["Training Manager", "培训经理", "مدير التدريب", "people"],
  ["AI Engineer", "人工智能工程师", "مهندس ذكاء اصطناعي", "it"],
  ["Backend Developer", "后端开发工程师", "مطور الواجهة الخلفية", "it"],
  ["Data Analyst", "数据分析师", "محلل بيانات", "it"],
  ["Data Engineer", "数据工程师", "مهندس بيانات", "it"],
  ["Data Scientist", "数据科学家", "عالم بيانات", "it"],
  ["DevOps Engineer", "DevOps 工程师", "مهندس DevOps", "it"],
  ["ERP Administrator", "ERP 系统管理员", "مسؤول نظام ERP", "it"],
  ["Frontend Developer", "前端开发工程师", "مطور الواجهة الأمامية", "it"],
  ["Full-stack Developer", "全栈开发工程师", "مطور متكامل", "it"],
  ["IT Director", "信息技术总监", "مدير تقنية المعلومات التنفيذي", "it"],
  ["IT Manager", "信息技术经理", "مدير تقنية المعلومات", "it"],
  ["IT Support Technician", "IT 支持技术员", "فني دعم تقنية المعلومات", "it"],
  ["Mobile Developer", "移动开发工程师", "مطور تطبيقات الجوال", "it"],
  ["Product Owner", "产品负责人", "مالك المنتج", "it"],
  ["QA Engineer", "质量保证工程师", "مهندس ضمان الجودة", "it"],
  ["QA Tester", "测试工程师", "مختبر ضمان الجودة", "it"],
  ["Software Engineer", "软件工程师", "مهندس برمجيات", "it"],
  ["Systems Administrator", "系统管理员", "مسؤول الأنظمة", "it"],
  ["UI/UX Designer", "UI/UX 设计师", "مصمم واجهات وتجربة المستخدم", "it"],
  ["Web Developer", "网页开发工程师", "مطور ويب", "it"],
  ["Company Secretary", "公司秘书", "سكرتير الشركة", "legal"],
  ["Compliance Officer", "合规专员", "مسؤول الامتثال", "legal"],
  ["Contracts Administrator", "合同管理员", "مسؤول العقود", "legal"],
  ["General Counsel", "总法律顾问", "المستشار القانوني العام", "legal"],
  ["ISO & Standards Officer", "ISO 与标准专员", "مسؤول الأيزو والمعايير", "legal"],
  ["Legal Advisor", "法律顾问", "مستشار قانوني", "legal"],
  ["Legal Counsel", "法律顾问", "مستشار قانوني", "legal"],
  ["Legal Manager", "法务经理", "مدير الشؤون القانونية", "legal"],
  ["Paralegal", "律师助理", "مساعد قانوني", "legal"],
  ["Administration Manager", "行政经理", "مدير الشؤون الإدارية", "admin"],
  ["Administrative Assistant", "行政助理", "مساعد إداري", "admin"],
  ["Executive Assistant", "行政助理", "مساعد تنفيذي", "admin"],
  ["Executive Secretary", "行政秘书", "سكرتير تنفيذي", "admin"],
  ["Facility Manager", "物业设施经理", "مدير المرافق", "admin"],
  ["Interpreter (Chinese–Arabic)", "中阿口译员", "مترجم فوري (صيني–عربي)", "admin"],
  ["Interpreter (Chinese–English)", "中英口译员", "مترجم فوري (صيني–إنجليزي)", "admin"],
  ["Office Attendant", "办公室勤杂员", "عامل مكتب", "admin"],
  ["Office Manager", "办公室经理", "مدير المكتب", "admin"],
  ["Personal Assistant to the CEO", "总裁助理", "مساعد شخصي للرئيس التنفيذي", "admin"],
  ["Receptionist", "前台接待", "موظف استقبال", "admin"],
  ["Security Guard", "保安", "حارس أمن", "admin"],
  ["Strategy & Planning Officer", "战略规划专员", "مسؤول الاستراتيجية والتخطيط", "admin"],
  ["Translator", "翻译", "مترجم", "admin"],
  ["Agent Support Coordinator", "代理商支持协调员", "منسق دعم الوكلاء", "partners"],
  ["Authorized Dealer", "授权经销商", "موزع معتمد", "partners"],
  ["Call Center Agent", "呼叫中心专员", "موظف مركز الاتصال", "partners"],
  ["Channel Manager", "渠道经理", "مدير القنوات", "partners"],
  ["Channel Sales Manager", "渠道销售经理", "مدير مبيعات القنوات", "partners"],
  ["Country Agent / Distributor", "国家代理 / 经销商", "وكيل / موزع الدولة", "partners"],
  ["Customer Service Agent", "客服专员", "موظف خدمة العملاء", "partners"],
  ["Dealer Development Manager", "经销商发展经理", "مدير تطوير الموزعين", "partners"],
  ["Distributor Account Manager", "经销商客户经理", "مدير حسابات الموزعين", "partners"],
  ["Exclusive Distributor", "独家经销商", "موزع حصري", "partners"],
  ["Franchise Coordinator", "加盟协调员", "منسق الامتياز التجاري", "partners"],
  ["Live Chat Agent", "在线客服专员", "موظف الدردشة المباشرة", "partners"],
  ["Order Processing Agent", "订单处理专员", "موظف معالجة الطلبات", "partners"],
  ["Partnerships Manager", "合作伙伴经理", "مدير الشراكات", "partners"],
  ["Regional Agent Manager", "区域代理经理", "مدير الوكلاء الإقليمي", "partners"],
  ["Sales Agent", "销售代理", "وكيل مبيعات", "partners"],
  ["Telesales Agent", "电话销售专员", "موظف مبيعات هاتفية", "partners"],
  ["Advisor", "顾问", "مستشار", "other"],
  ["Consultant", "顾问", "مستشار", "other"],
  ["Coordinator", "协调员", "منسق", "other"],
  ["Intern", "实习生", "متدرب", "other"],
  ["Officer", "专员", "مسؤول", "other"],
  ["Senior Consultant", "高级顾问", "مستشار أول", "other"],
  ["Specialist", "专员", "أخصائي", "other"],
  ["Tenders & Bids Specialist", "招投标专员", "أخصائي المناقصات والعطاءات", "other"],
  ["Trainee", "培训生", "متدرب", "other"],
];

export const TITLES: TitleEntry[] = ROWS.map(([en, zh, ar, group]) => ({ en, zh, ar, group }));

const BY_EN = new Map(TITLES.map((t) => [t.en.toLowerCase(), t]));

/** The library entry a title is (by its English), or null. */
export const titleEntry = (en: string): TitleEntry | null => BY_EN.get(en.trim().toLowerCase()) ?? null;

/** A library title in a language; null when the title is not in the library. */
export function titleIn(en: string, lang: "en" | "zh" | "ar"): string | null {
  const e = titleEntry(en);
  return e ? e[lang] : null;
}
