/**
 * Fabric Rolling / Winding Machines — XPRL (v1)
 *
 * Field set from the owner's XPR template collection ("卷绕机" — the EN list's
 * "Looping machine" was a mistranslation; canonical name follows the coding
 * system: Fabric Winding / Rolling Machine) plus the types-master facets
 * (roll_capacity, winding_type, with_measuring). Templates only.
 */

import type { ProductSchemaDefinition } from "@/types/product-schema";
import {
  DEFAULT_PUBLIC_VISIBILITY,
  DEFAULT_TECHNICAL_VISIBILITY,
} from "../visibility";

const tech = DEFAULT_TECHNICAL_VISIBILITY;
const pub = DEFAULT_PUBLIC_VISIBILITY;

export const FABRIC_ROLLING_SCHEMA: ProductSchemaDefinition = {
  id: "fabric-rolling.v1",
  divisionCode: "garment-machinery",
  categoryCode: "fabric-preparation",
  subcategoryCode: "XPRL",
  name: "Fabric Rolling / Winding Machine",
  version: "1.0.0",
  appliesTo: {
    description:
      "Machines that wind fabric into even, straight-edged rolls — from loose fabric, plaits or other rolls — with length counting and edge alignment.",
  },
  groups: [
    {
      id: "type-application",
      title: "Type & Application",
      order: 10,
      fields: [
        {
          id: "winding_type",
          key: "winding_type",
          anchor: true,
          importance: "high",
          anchorPriority: 10,
          label: "Winding Type",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: true,
          description: "Winding principle used to build the roll.",
          options: [
            { value: "surface", label: "Surface (Friction) Winding" },
            { value: "center", label: "Center (Shaft) Winding" },
            { value: "loose", label: "Loose / Tension-Free Winding" },
            { value: "double_fold", label: "Double-Fold Rolling" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "fabric_compatibility",
          key: "fabric_compatibility",
          anchor: true,
          importance: "high",
          anchorPriority: 20,
          label: "Fabric Compatibility",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: true,
          description: "Fabric constructions the machine can wind.",
          options: [
            { value: "knit", label: "Knit" },
            { value: "woven", label: "Woven" },
            { value: "elastic", label: "Elastic / Spandex" },
            { value: "tubular", label: "Tubular" },
            { value: "heavy", label: "Heavy Fabrics" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "material_card",
        },
        {
          id: "with_measuring",
          key: "with_measuring",
          label: "With Length Measuring",
          order: 30,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Counts fabric length while winding.",
          ...pub,
          comparable: true,
          visualRenderType: "boolean_feature",
        },
        {
          id: "automation_level",
          key: "automation_level",
          label: "Automation Level",
          order: 40,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Degree of automation.",
          options: [
            { value: "manual", label: "Manual" },
            { value: "semi_automatic", label: "Semi-Automatic" },
            { value: "automatic", label: "Automatic" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
      ],
    },

    {
      id: "winding-performance",
      title: "Winding Performance",
      order: 20,
      fields: [
        {
          id: "max_fabric_width",
          key: "max_fabric_width",
          importance: "critical",
          anchor: true,
          anchorPriority: 30,
          label: "Max Fabric Width",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: true,
          description: "Maximum fabric width the machine can wind.",
          suggestions: [1800, 2000, 2200, 2400, 2600, 3200],
          ...tech,
          comparable: true,
          filterVisible: true,
          visualRenderType: "metric_block",
        },
        {
          id: "winding_speed",
          key: "winding_speed",
          importance: "high",
          label: "Winding Speed",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m/min",
          required: false,
          description: "Fabric winding speed.",
          suggestions: [20, 30, 40, 60, 80],
          ...pub,
          comparable: true,
          visualRenderType: "metric_block",
        },
        {
          id: "max_roll_diameter",
          key: "max_roll_diameter",
          label: "Max Roll Diameter",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Largest roll the machine can build.",
          suggestions: [400, 500, 600, 800],
          ...pub,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "max_roll_weight",
          key: "max_roll_weight",
          label: "Max Roll Weight",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Heaviest roll the machine can build/carry.",
          suggestions: [60, 80, 100, 150],
          ...pub,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "edge_alignment_accuracy",
          key: "edge_alignment_accuracy",
          label: "Edge Alignment Accuracy",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "± mm",
          required: false,
          description: "Edge-to-edge winding tolerance.",
          suggestions: [2, 3, 5],
          ...tech,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "tension_control",
          key: "tension_control",
          label: "Tension Control",
          order: 60,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Fabric tension management while winding.",
          options: [
            { value: "mechanical", label: "Mechanical" },
            { value: "auto_tension", label: "Automatic Tension Control" },
            { value: "tension_free", label: "Tension-Free" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
      ],
    },

    {
      id: "handling",
      title: "Handling",
      order: 30,
      fields: [
        {
          id: "feeding_method",
          key: "feeding_method",
          label: "Feeding Method",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How fabric enters the machine.",
          options: [
            { value: "roll_letoff", label: "Roll Let-off" },
            { value: "plait_feed", label: "Plaited-Fabric Feed" },
            { value: "loose_feed", label: "Loose-Fabric Feed" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "discharge_method",
          key: "discharge_method",
          label: "Discharge Method",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How the finished roll is taken off.",
          options: [
            { value: "manual_doff", label: "Manual Doffing" },
            { value: "auto_doff", label: "Automatic Doffing" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
      ],
    },

    {
      id: "electrical-utilities",
      title: "Electrical & Utilities",
      order: 40,
      fields: [
        {
          id: "phase",
          key: "phase",
          label: "Power Phase",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Electrical supply phase.",
          options: [
            { value: "single_phase", label: "Single Phase (1PH)" },
            { value: "three_phase", label: "Three Phase (3PH)" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "voltage_options",
          key: "voltage_options",
          label: "Voltage",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Rated supply voltage.",
          options: [
            { value: "220v", label: "220 V" },
            { value: "380v", label: "380 V" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "motor_power_kw",
          key: "motor_power_kw",
          label: "Motor Power",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kW",
          required: false,
          description: "Rated motor power.",
          suggestions: [0.75, 1.1, 1.5, 2.2],
          ...pub,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "frequency_hz",
          key: "frequency_hz",
          label: "Frequency",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "Hz",
          required: false,
          description: "Rated supply frequency.",
          suggestions: [50, 60],
          ...pub,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "equipment-options",
      title: "Equipment & Options",
      order: 50,
      fields: [
        {
          id: "equipment_features",
          key: "equipment_features",
          label: "Equipment & Features",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Fitted equipment and available options.",
          options: [
            { value: "length_counter", label: "Digital Length Counter" },
            { value: "preset_length_stop", label: "Preset-Length Auto Stop" },
            { value: "edge_aligner", label: "Photoelectric Edge Aligner" },
            { value: "variable_speed", label: "Variable-Speed Inverter Drive" },
            { value: "slitting", label: "Slitting Attachment" },
            { value: "paper_core_chuck", label: "Paper-Core Chuck" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
      ],
    },

    {
      id: "physical",
      title: "Physical",
      order: 60,
      formTab: "logistics",
      fields: [
        {
          id: "machine_weight_kg",
          key: "machine_weight_kg",
          label: "Machine Weight",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net weight of the machine.",
          suggestions: [200, 300, 450, 600],
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "machine_dimensions",
          key: "machine_dimensions",
          label: "Machine Dimensions (L×W×H)",
          order: 20,
          fieldType: "dimension",
          dataType: "string",
          unit: "mm",
          required: false,
          description: "Overall machine dimensions in mm (L×W×H).",
          ...pub,
          visualRenderType: "packing_block",
        },
      ],
    },

    {
      id: "packing-shipping",
      title: "Packing & Shipping",
      order: 65,
      formTab: "logistics",
      fields: [
        {
          id: "packing_dimensions",
          key: "packing_dimensions",
          label: "Packing Dimensions (L×W×H)",
          order: 10,
          fieldType: "dimension",
          dataType: "string",
          unit: "mm",
          required: false,
          description: "Packed crate dimensions in mm (L×W×H).",
          ...pub,
          visualRenderType: "packing_block",
        },
        {
          id: "cbm",
          key: "cbm",
          label: "CBM",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m³",
          required: false,
          description: "Packed volume in cubic metres.",
          ...pub,
          computed: { from: "packing_dimensions", formula: "cbm_m3_from_mm_dimensions" },
          visualRenderType: "spec_card",
        },
        {
          id: "net_weight",
          key: "net_weight",
          label: "Net Weight (N.W.)",
          order: 25,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net shipping weight on the packing list.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "gross_weight",
          key: "gross_weight",
          label: "Gross Weight",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Gross shipping weight.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "packing_type",
          key: "packing_type",
          label: "Packing Type",
          order: 40,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How the machine is packed for shipment.",
          options: [
            { value: "wooden_case", label: "Wooden Case" },
            { value: "plywood_crate", label: "Plywood Crate" },
            { value: "carton", label: "Carton" },
            { value: "pallet_film", label: "Pallet + Stretch Film" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "container_20ft_qty",
          key: "container_20ft_qty",
          label: "Qty per 20ft Container",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 20ft container.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "container_40ft_qty",
          key: "container_40ft_qty",
          label: "Qty per 40ft Container",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 40ft STANDARD container.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "container_40hq_qty",
          key: "container_40hq_qty",
          label: "Qty per 40HQ Container",
          order: 65,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 40ft High-Cube container.",
          ...pub,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "safety-compliance",
      title: "Safety & Compliance",
      order: 70,
      fields: [
        {
          id: "safety_features",
          key: "safety_features",
          label: "Safety Features",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Built-in operator- and machine-safety systems.",
          options: [
            { value: "emergency_stop", label: "Emergency Stop" },
            { value: "guard_covers", label: "Guard Covers" },
            { value: "overload_protection", label: "Motor Overload Protection" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
        {
          id: "certifications",
          key: "certifications",
          label: "Certifications",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Quality and compliance certifications.",
          options: [
            { value: "ce", label: "CE" },
            { value: "iso9001", label: "ISO 9001" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
      ],
    },
  ],
};
