/**
 * Fabric Inspection Machines — XPRI (v1)
 *
 * Field set from the owner's XPR template collection plus the types-master
 * required facets for XPRI (inspection_method, with_rolling). Templates only —
 * values are entered per model in Product Data.
 */

import type { ProductSchemaDefinition } from "@/types/product-schema";
import {
  DEFAULT_PUBLIC_VISIBILITY,
  DEFAULT_TECHNICAL_VISIBILITY,
} from "../visibility";

const tech = DEFAULT_TECHNICAL_VISIBILITY;
const pub = DEFAULT_PUBLIC_VISIBILITY;

export const FABRIC_INSPECTION_SCHEMA: ProductSchemaDefinition = {
  id: "fabric-inspection.v1",
  divisionCode: "garment-machinery",
  categoryCode: "fabric-preparation",
  subcategoryCode: "XPRI",
  name: "Fabric Inspection Machine",
  version: "1.0.0",
  appliesTo: {
    description:
      "Machines that unroll, back-light, measure and re-roll fabric so defects are caught and marked before spreading and cutting.",
  },
  groups: [
    {
      id: "type-application",
      title: "Type & Application",
      order: 10,
      fields: [
        {
          id: "inspection_method",
          key: "inspection_method",
          anchor: true,
          importance: "high",
          anchorPriority: 10,
          label: "Inspection Method",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: true,
          description: "How defects are detected.",
          options: [
            { value: "manual_4point", label: "Manual (4-Point System)" },
            { value: "vision_assisted", label: "Camera-Assisted" },
            { value: "ai_vision", label: "AI Vision (Automatic Defect Detection)" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "fabric_compatibility",
          key: "fabric_compatibility",
          anchor: true,
          importance: "high",
          anchorPriority: 20,
          label: "Fabric Compatibility",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: true,
          description: "Fabric constructions the machine can inspect.",
          options: [
            { value: "knit", label: "Knit" },
            { value: "woven", label: "Woven" },
            { value: "denim", label: "Denim" },
            { value: "elastic", label: "Elastic / Spandex" },
            { value: "tubular", label: "Tubular" },
            { value: "technical", label: "Technical Fabrics" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "material_card",
        },
        {
          id: "with_rolling",
          key: "with_rolling",
          label: "With Re-Rolling",
          order: 30,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Re-winds inspected fabric back onto a roll.",
          ...pub,
          comparable: true,
          visualRenderType: "boolean_feature",
        },
        {
          id: "automation_level",
          key: "automation_level",
          label: "Automation Level",
          order: 40,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Degree of automation.",
          options: [
            { value: "manual", label: "Manual" },
            { value: "semi_automatic", label: "Semi-Automatic" },
            { value: "automatic", label: "Automatic" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
      ],
    },

    {
      id: "inspection-performance",
      title: "Inspection Performance",
      order: 20,
      fields: [
        {
          id: "max_fabric_width",
          key: "max_fabric_width",
          importance: "critical",
          anchor: true,
          anchorPriority: 30,
          label: "Max Fabric Width",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: true,
          description: "Maximum fabric width the machine can inspect.",
          suggestions: [1800, 2000, 2200, 2400, 2600, 3200],
          ...tech,
          comparable: true,
          filterVisible: true,
          visualRenderType: "metric_block",
        },
        {
          id: "max_inspection_speed",
          key: "max_inspection_speed",
          importance: "high",
          label: "Max Inspection Speed",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m/min",
          required: false,
          description: "Top fabric speed during inspection.",
          suggestions: [20, 30, 40, 60, 90],
          ...pub,
          comparable: true,
          visualRenderType: "metric_block",
        },
        {
          id: "max_roll_diameter",
          key: "max_roll_diameter",
          label: "Max Roll Diameter",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Largest roll accepted on the let-off / rewind.",
          suggestions: [400, 500, 600, 800],
          ...pub,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "light_source",
          key: "light_source",
          label: "Light Source System",
          order: 40,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Illumination used to reveal defects.",
          options: [
            { value: "led_top", label: "LED Top Light" },
            { value: "led_bottom", label: "LED Bottom (Back-Light)" },
            { value: "led_dual", label: "LED Dual (Top + Bottom)" },
            { value: "adjustable", label: "Adjustable Intensity" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "length_measuring_accuracy",
          key: "length_measuring_accuracy",
          label: "Length Measuring Accuracy",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "%",
          required: false,
          description: "Length-counter accuracy (± percent).",
          suggestions: [0.1, 0.2, 0.5],
          ...tech,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "edge_alignment_accuracy",
          key: "edge_alignment_accuracy",
          label: "Edge Alignment Accuracy",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "± mm",
          required: false,
          description: "Edge-to-edge winding tolerance.",
          suggestions: [2, 3, 5],
          ...tech,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "handling",
      title: "Handling",
      order: 30,
      fields: [
        {
          id: "feeding_method",
          key: "feeding_method",
          label: "Feeding Method",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How fabric enters the machine.",
          options: [
            { value: "roll_letoff", label: "Roll Let-off" },
            { value: "plait_feed", label: "Plaited-Fabric Feed" },
            { value: "both", label: "Roll + Plait" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "discharge_method",
          key: "discharge_method",
          label: "Discharge Method",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How fabric leaves the machine.",
          options: [
            { value: "rewind", label: "Re-Wind to Roll" },
            { value: "plaiter", label: "Plaiter (Folded Output)" },
            { value: "both", label: "Roll + Plait" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "tension_control",
          key: "tension_control",
          label: "Tension Control",
          order: 30,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Fabric tension management during winding.",
          options: [
            { value: "mechanical", label: "Mechanical" },
            { value: "auto_tension", label: "Automatic Tension Control" },
            { value: "tension_free", label: "Tension-Free" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
      ],
    },

    {
      id: "electrical-utilities",
      title: "Electrical & Utilities",
      order: 40,
      fields: [
        {
          id: "phase",
          key: "phase",
          label: "Power Phase",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Electrical supply phase.",
          options: [
            { value: "single_phase", label: "Single Phase (1PH)" },
            { value: "three_phase", label: "Three Phase (3PH)" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "voltage_options",
          key: "voltage_options",
          label: "Voltage",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Rated supply voltage.",
          options: [
            { value: "220v", label: "220 V" },
            { value: "380v", label: "380 V" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "frequency_hz",
          key: "frequency_hz",
          label: "Frequency",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "Hz",
          required: false,
          description: "Rated supply frequency.",
          suggestions: [50, 60],
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "power_consumption_kw",
          key: "power_consumption_kw",
          label: "Power",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kW",
          required: false,
          description: "Rated power consumption.",
          suggestions: [0.75, 1.1, 1.5, 2.2, 3],
          ...pub,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "air_pressure",
          key: "air_pressure",
          label: "Air Pressure",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "bar",
          required: false,
          description: "Compressed-air requirement (if pneumatic functions fitted).",
          suggestions: [4, 5, 6],
          ...tech,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "equipment-options",
      title: "Equipment & Options",
      order: 50,
      fields: [
        {
          id: "equipment_features",
          key: "equipment_features",
          label: "Equipment & Features",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Fitted equipment and available options.",
          options: [
            { value: "length_counter", label: "Digital Length Counter" },
            { value: "defect_marker", label: "Defect Marking / Labelling" },
            { value: "defect_report", label: "Defect Report / Grading Software" },
            { value: "edge_aligner", label: "Photoelectric Edge Aligner" },
            { value: "variable_speed", label: "Variable-Speed Inverter Drive" },
            { value: "lint_removal", label: "Lint / Dust Removal" },
            { value: "joint_detector", label: "Seam / Joint Detector" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
      ],
    },

    {
      id: "physical",
      title: "Physical",
      order: 60,
      formTab: "logistics",
      fields: [
        {
          id: "machine_weight_kg",
          key: "machine_weight_kg",
          label: "Machine Weight",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net weight of the machine.",
          suggestions: [400, 600, 800, 1200],
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "machine_dimensions",
          key: "machine_dimensions",
          label: "Machine Dimensions (L×W×H)",
          order: 20,
          fieldType: "dimension",
          dataType: "string",
          unit: "mm",
          required: false,
          description: "Overall machine dimensions in mm (L×W×H).",
          ...pub,
          visualRenderType: "packing_block",
        },
      ],
    },

    {
      id: "packing-shipping",
      title: "Packing & Shipping",
      order: 65,
      formTab: "logistics",
      fields: [
        {
          id: "packing_dimensions",
          key: "packing_dimensions",
          label: "Packing Dimensions (L×W×H)",
          order: 10,
          fieldType: "dimension",
          dataType: "string",
          unit: "mm",
          required: false,
          description: "Packed crate dimensions in mm (L×W×H).",
          ...pub,
          visualRenderType: "packing_block",
        },
        {
          id: "cbm",
          key: "cbm",
          label: "CBM",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m³",
          required: false,
          description: "Packed volume in cubic metres.",
          ...pub,
          computed: { from: "packing_dimensions", formula: "cbm_m3_from_mm_dimensions" },
          visualRenderType: "spec_card",
        },
        {
          id: "net_weight",
          key: "net_weight",
          label: "Net Weight (N.W.)",
          order: 25,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net shipping weight on the packing list.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "gross_weight",
          key: "gross_weight",
          label: "Gross Weight",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Gross shipping weight.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "packing_type",
          key: "packing_type",
          label: "Packing Type",
          order: 40,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How the machine is packed for shipment.",
          options: [
            { value: "wooden_case", label: "Wooden Case" },
            { value: "plywood_crate", label: "Plywood Crate" },
            { value: "carton", label: "Carton" },
            { value: "pallet_film", label: "Pallet + Stretch Film" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "container_20ft_qty",
          key: "container_20ft_qty",
          label: "Qty per 20ft Container",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 20ft container.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "container_40ft_qty",
          key: "container_40ft_qty",
          label: "Qty per 40ft Container",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 40ft STANDARD container.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "container_40hq_qty",
          key: "container_40hq_qty",
          label: "Qty per 40HQ Container",
          order: 65,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 40ft High-Cube container.",
          ...pub,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "safety-compliance",
      title: "Safety & Compliance",
      order: 70,
      fields: [
        {
          id: "safety_features",
          key: "safety_features",
          label: "Safety Features",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Built-in operator- and machine-safety systems.",
          options: [
            { value: "emergency_stop", label: "Emergency Stop" },
            { value: "guard_covers", label: "Guard Covers" },
            { value: "anti_glare", label: "Anti-Glare Operator Screen" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
        {
          id: "certifications",
          key: "certifications",
          label: "Certifications",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Quality and compliance certifications.",
          options: [
            { value: "ce", label: "CE" },
            { value: "iso9001", label: "ISO 9001" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
      ],
    },
  ],
};
