/**
 * Fabric Cutting Tables — XPRT (v1)
 *
 * Field set from the owner's XPR template collection plus the types-master
 * facets for XPRT (surface_type, length, width, sectioned_vacuum,
 * spreader_rails). Tables are MODULAR — length is built from sections, the
 * same configurable logic as the head+stand+table sets. Templates only.
 */

import type { ProductSchemaDefinition } from "@/types/product-schema";
import {
  DEFAULT_PUBLIC_VISIBILITY,
  DEFAULT_TECHNICAL_VISIBILITY,
} from "../visibility";

const tech = DEFAULT_TECHNICAL_VISIBILITY;
const pub = DEFAULT_PUBLIC_VISIBILITY;

export const FABRIC_CUTTING_TABLE_SCHEMA: ProductSchemaDefinition = {
  id: "fabric-cutting-table.v1",
  divisionCode: "garment-machinery",
  categoryCode: "fabric-preparation",
  subcategoryCode: "XPRT",
  name: "Fabric Spreading / Cutting Table",
  version: "1.0.0",
  appliesTo: {
    description:
      "Precision-flat modular tables that carry spreading machines and cutting — flatness, straightness and diagonal accuracy are the product.",
  },
  groups: [
    {
      id: "type-application",
      title: "Type & Configuration",
      order: 10,
      fields: [
        {
          id: "surface_type",
          key: "surface_type",
          anchor: true,
          importance: "high",
          anchorPriority: 10,
          label: "Surface Type",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: true,
          description: "Working-surface construction.",
          options: [
            { value: "static", label: "Static (Standard Laminate)" },
            { value: "vacuum", label: "Vacuum" },
            { value: "air_float", label: "Air-Float (Air Cushion)" },
            { value: "conveyor", label: "Conveyor Top" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "surface_material",
          key: "surface_material",
          label: "Surface Material",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Table-top material.",
          options: [
            { value: "hpl_laminate", label: "HPL Laminate on MDF" },
            { value: "steel", label: "Steel Sheet" },
            { value: "composite", label: "Composite Panel" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "sectioned_vacuum",
          key: "sectioned_vacuum",
          label: "Sectioned Vacuum Zones",
          order: 30,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Vacuum switchable per table section (vacuum tables).",
          ...pub,
          comparable: true,
          visualRenderType: "boolean_feature",
        },
        {
          id: "spreader_rails",
          key: "spreader_rails",
          label: "Spreader Rails",
          order: 40,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Side rails fitted for an automatic spreading machine.",
          ...pub,
          comparable: true,
          visualRenderType: "boolean_feature",
        },
      ],
    },

    {
      id: "geometry-precision",
      title: "Geometry & Precision",
      order: 20,
      fields: [
        {
          id: "table_width",
          key: "table_width",
          importance: "critical",
          anchor: true,
          anchorPriority: 20,
          label: "Table Width",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: true,
          description: "Working-surface width.",
          suggestions: [1800, 2000, 2200, 2400, 2600, 3200],
          ...tech,
          comparable: true,
          filterVisible: true,
          visualRenderType: "metric_block",
        },
        {
          id: "table_length",
          key: "table_length",
          importance: "critical",
          anchor: true,
          anchorPriority: 30,
          label: "Table Length",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m",
          required: true,
          description:
            "Total table length — built from modular sections; configured per order.",
          suggestions: [6, 8, 10, 12, 16, 20, 30],
          ...tech,
          comparable: true,
          filterVisible: true,
          visualRenderType: "metric_block",
        },
        {
          id: "section_length",
          key: "section_length",
          label: "Section Length",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m",
          required: false,
          description: "Length of one modular section.",
          suggestions: [1, 1.2, 2],
          ...tech,
          visualRenderType: "spec_card",
        },
        {
          id: "table_height",
          key: "table_height",
          label: "Table Height",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Working height (state range if adjustable).",
          suggestions: [750, 800, 850, 900],
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "height_adjustable",
          key: "height_adjustable",
          label: "Height Adjustable",
          order: 50,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Leg levelling / height adjustment fitted.",
          ...pub,
          visualRenderType: "boolean_feature",
        },
        {
          id: "table_flatness",
          key: "table_flatness",
          importance: "high",
          label: "Surface Flatness",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm/m",
          required: false,
          description: "Maximum flatness deviation per metre.",
          suggestions: [0.5, 1, 2],
          ...tech,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "table_straightness",
          key: "table_straightness",
          label: "Edge Straightness",
          order: 70,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm/m",
          required: false,
          description: "Maximum edge straightness deviation per metre.",
          suggestions: [0.5, 1, 2],
          ...tech,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "diagonal_error",
          key: "diagonal_error",
          label: "Diagonal Error",
          order: 80,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Maximum difference between the two diagonals.",
          suggestions: [1, 2, 3, 5],
          ...tech,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "max_load",
          key: "max_load",
          label: "Max Distributed Load",
          order: 90,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg/m²",
          required: false,
          description: "Load capacity of the surface (fabric rolls + machine).",
          suggestions: [100, 150, 200, 300],
          ...tech,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "utilities",
      title: "Utilities",
      order: 40,
      fields: [
        {
          id: "vacuum_power_kw",
          key: "vacuum_power_kw",
          label: "Vacuum / Blower Power",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kW",
          required: false,
          description: "Fan power (vacuum / air-float tables).",
          suggestions: [2.2, 3, 4, 5.5, 7.5],
          ...tech,
          visualRenderType: "spec_card",
        },
        {
          id: "voltage_options",
          key: "voltage_options",
          label: "Voltage",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Rated supply voltage (powered tables).",
          options: [
            { value: "220v", label: "220 V" },
            { value: "380v", label: "380 V" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "phase",
          key: "phase",
          label: "Power Phase",
          order: 30,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Electrical supply phase (powered tables).",
          options: [
            { value: "single_phase", label: "Single Phase (1PH)" },
            { value: "three_phase", label: "Three Phase (3PH)" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
      ],
    },

    {
      id: "equipment-options",
      title: "Equipment & Options",
      order: 50,
      fields: [
        {
          id: "equipment_features",
          key: "equipment_features",
          label: "Equipment & Options",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Fitted equipment and available options.",
          options: [
            { value: "spreader_rails", label: "Spreading-Machine Rails" },
            { value: "end_catcher", label: "End Catcher / Clamp Bar" },
            { value: "cutting_groove", label: "End-Cutter Groove" },
            { value: "under_shelf", label: "Under-Table Shelf" },
            { value: "castors", label: "Levelling Feet / Castors" },
            { value: "power_sockets", label: "Integrated Power Sockets" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
      ],
    },

    {
      id: "physical",
      title: "Physical",
      order: 60,
      formTab: "logistics",
      fields: [
        {
          id: "weight_per_section",
          key: "weight_per_section",
          label: "Weight per Section",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net weight of one modular section.",
          suggestions: [80, 100, 150, 200],
          ...pub,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "packing-shipping",
      title: "Packing & Shipping",
      order: 65,
      formTab: "logistics",
      fields: [
        {
          id: "packing_dimensions",
          key: "packing_dimensions",
          label: "Packing Dimensions (L×W×H)",
          order: 10,
          fieldType: "dimension",
          dataType: "string",
          unit: "mm",
          required: false,
          description: "Packed dimensions per section/bundle in mm (L×W×H).",
          ...pub,
          visualRenderType: "packing_block",
        },
        {
          id: "cbm",
          key: "cbm",
          label: "CBM",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m³",
          required: false,
          description: "Packed volume in cubic metres.",
          ...pub,
          computed: { from: "packing_dimensions", formula: "cbm_m3_from_mm_dimensions" },
          visualRenderType: "spec_card",
        },
        {
          id: "net_weight",
          key: "net_weight",
          label: "Net Weight (N.W.)",
          order: 25,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net shipping weight on the packing list.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "gross_weight",
          key: "gross_weight",
          label: "Gross Weight",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Gross shipping weight (per section/bundle).",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "packing_type",
          key: "packing_type",
          label: "Packing Type",
          order: 40,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How the machine is packed for shipment.",
          options: [
            { value: "wooden_case", label: "Wooden Case" },
            { value: "plywood_crate", label: "Plywood Crate" },
            { value: "carton", label: "Carton" },
            { value: "pallet_film", label: "Pallet + Stretch Film" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "container_20ft_qty",
          key: "container_20ft_qty",
          label: "Qty per 20ft Container",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 20ft container.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "container_40ft_qty",
          key: "container_40ft_qty",
          label: "Qty per 40ft Container",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 40ft STANDARD container.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "container_40hq_qty",
          key: "container_40hq_qty",
          label: "Qty per 40HQ Container",
          order: 65,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 40ft High-Cube container.",
          ...pub,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "safety-compliance",
      title: "Safety & Compliance",
      order: 70,
      fields: [
        {
          id: "certifications",
          key: "certifications",
          label: "Certifications",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Quality and compliance certifications.",
          options: [
            { value: "ce", label: "CE" },
            { value: "iso9001", label: "ISO 9001" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
      ],
    },
  ],
};
