/**
 * Fabric Relaxing Machines — XPRR (v1)
 *
 * Field set from the owner's XPR template collection (organized in
 * docs/product-data-v2/spec-templates/xpr-fabric-preparation-spec-templates.md)
 * plus the required/comparison facets the types-master defines for XPRR
 * (relaxation_method, output_form, automation_level). Templates only — every
 * value is entered per model in Product Data.
 */

import type { ProductSchemaDefinition } from "@/types/product-schema";
import {
  DEFAULT_PUBLIC_VISIBILITY,
  DEFAULT_TECHNICAL_VISIBILITY,
} from "../visibility";

const tech = DEFAULT_TECHNICAL_VISIBILITY;
const pub = DEFAULT_PUBLIC_VISIBILITY;

export const FABRIC_RELAXING_SCHEMA: ProductSchemaDefinition = {
  id: "fabric-relaxing.v1",
  divisionCode: "garment-machinery",
  categoryCode: "fabric-preparation",
  subcategoryCode: "XPRR",
  name: "Fabric Relaxing Machine",
  version: "1.0.0",
  appliesTo: {
    description:
      "Machines that release fabric tension after knitting/dyeing — steaming or tension-free unwinding so the fabric reaches natural dimensions before spreading and cutting.",
  },
  groups: [
    {
      id: "type-application",
      title: "Type & Application",
      order: 10,
      fields: [
        {
          id: "relaxing_method",
          key: "relaxing_method",
          anchor: true,
          importance: "high",
          anchorPriority: 10,
          label: "Relaxing Method",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: true,
          description: "How the machine releases fabric tension.",
          options: [
            { value: "steam", label: "Steam Relaxing" },
            { value: "tensionless_mechanical", label: "Tension-Free Mechanical" },
            { value: "air_vibration", label: "Air / Vibration" },
            { value: "combined", label: "Combined (Steam + Mechanical)" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "fabric_compatibility",
          key: "fabric_compatibility",
          anchor: true,
          importance: "high",
          anchorPriority: 20,
          label: "Fabric Compatibility",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: true,
          description: "Fabric constructions the machine can relax.",
          options: [
            { value: "knit", label: "Knit" },
            { value: "woven", label: "Woven" },
            { value: "elastic", label: "Elastic / Spandex" },
            { value: "tubular", label: "Tubular" },
            { value: "open_width", label: "Open Width" },
            { value: "delicate", label: "Delicate / Silk-like" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "material_card",
        },
        {
          id: "output_form",
          key: "output_form",
          label: "Output Form",
          order: 30,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How relaxed fabric leaves the machine.",
          options: [
            { value: "roll_to_roll", label: "Roll → Roll" },
            { value: "roll_to_plait", label: "Roll → Plait (Folded)" },
            { value: "plait_to_plait", label: "Plait → Plait" },
          ],
          ...pub,
          comparable: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "automation_level",
          key: "automation_level",
          label: "Automation Level",
          order: 40,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Degree of automation.",
          options: [
            { value: "manual", label: "Manual" },
            { value: "semi_automatic", label: "Semi-Automatic" },
            { value: "automatic", label: "Automatic" },
          ],
          ...pub,
          comparable: true,
          visualRenderType: "technical_badge",
        },
      ],
    },

    {
      id: "relaxing-performance",
      title: "Relaxing Performance",
      order: 20,
      fields: [
        {
          id: "max_fabric_width",
          key: "max_fabric_width",
          importance: "critical",
          anchor: true,
          anchorPriority: 30,
          label: "Max Fabric Width",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: true,
          description: "Maximum fabric width the machine can process.",
          suggestions: [1800, 2000, 2200, 2400, 2600, 3000, 3200, 3600],
          ...tech,
          comparable: true,
          filterVisible: true,
          visualRenderType: "metric_block",
        },
        {
          id: "working_speed",
          key: "working_speed",
          importance: "high",
          label: "Working Speed",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m/min",
          required: false,
          description: "Fabric throughput speed.",
          suggestions: [10, 15, 20, 25, 30, 40],
          ...pub,
          comparable: true,
          visualRenderType: "metric_block",
        },
        {
          id: "max_operating_temp",
          key: "max_operating_temp",
          label: "Max Operating Temperature",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "°C",
          required: false,
          description: "Highest steam-chamber working temperature.",
          suggestions: [100, 110, 120, 135],
          ...tech,
          visualRenderType: "spec_card",
        },
        {
          id: "steam_consumption",
          key: "steam_consumption",
          label: "Steam Consumption",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg/h",
          required: false,
          description: "Steam usage at rated speed (steam models).",
          suggestions: [30, 50, 80, 100, 150],
          ...tech,
          visualRenderType: "spec_card",
        },
        {
          id: "max_roll_diameter",
          key: "max_roll_diameter",
          label: "Max Roll Diameter",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Largest fabric roll the in-feed accepts.",
          suggestions: [400, 500, 600, 800, 1000],
          ...pub,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "max_roll_weight",
          key: "max_roll_weight",
          label: "Max Roll Weight",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Heaviest fabric roll the in-feed carries.",
          suggestions: [60, 80, 100, 150, 200],
          ...pub,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "handling-accuracy",
      title: "Handling & Accuracy",
      order: 30,
      fields: [
        {
          id: "feeding_method",
          key: "feeding_method",
          label: "Feeding Method",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How fabric enters the machine.",
          options: [
            { value: "roll_cradle", label: "Roll Cradle (Tension-Free Let-off)" },
            { value: "shaft_unwind", label: "Shaft Unwind" },
            { value: "plait_feed", label: "Plaited-Fabric Feed" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "discharge_method",
          key: "discharge_method",
          label: "Discharge Method",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How fabric leaves the machine.",
          options: [
            { value: "rewind", label: "Re-Wind to Roll" },
            { value: "plaiter", label: "Plaiter (Folded Output)" },
            { value: "conveyor", label: "Conveyor Out-feed" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "edge_alignment_accuracy",
          key: "edge_alignment_accuracy",
          label: "Edge Alignment Accuracy",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "± mm",
          required: false,
          description: "Edge-to-edge alignment tolerance.",
          suggestions: [2, 3, 5],
          ...tech,
          comparable: true,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "electrical-utilities",
      title: "Electrical & Utilities",
      order: 40,
      fields: [
        {
          id: "phase",
          key: "phase",
          label: "Power Phase",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Electrical supply phase.",
          options: [
            { value: "single_phase", label: "Single Phase (1PH)" },
            { value: "three_phase", label: "Three Phase (3PH)" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "voltage_options",
          key: "voltage_options",
          label: "Voltage",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Rated supply voltage.",
          options: [
            { value: "220v", label: "220 V" },
            { value: "380v", label: "380 V" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "frequency_hz",
          key: "frequency_hz",
          label: "Frequency",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "Hz",
          required: false,
          description: "Rated supply frequency.",
          suggestions: [50, 60],
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "power_consumption_w",
          key: "power_consumption_w",
          label: "Total Installed Power",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kW",
          required: false,
          description: "Total connected electrical load.",
          suggestions: [3, 5, 8, 12, 18],
          ...pub,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "air_pressure",
          key: "air_pressure",
          label: "Air Pressure",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "bar",
          required: false,
          description: "Compressed-air supply requirement.",
          suggestions: [4, 5, 6],
          ...tech,
          visualRenderType: "spec_card",
        },
        {
          id: "steam_pressure",
          key: "steam_pressure",
          label: "Steam Pressure",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "bar",
          required: false,
          description: "Steam supply requirement (steam models).",
          suggestions: [3, 4, 5, 6],
          ...tech,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "equipment-options",
      title: "Equipment & Options",
      order: 50,
      fields: [
        {
          id: "equipment_features",
          key: "equipment_features",
          label: "Equipment & Features",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Fitted equipment and available options.",
          options: [
            { value: "edge_uncurler", label: "Edge Uncurler" },
            { value: "plaiter", label: "Plaiter" },
            { value: "tubular_opening", label: "Tubular Opening Device" },
            { value: "photo_edge_sensor", label: "Photoelectric Edge Sensor" },
            { value: "length_counter", label: "Length Counter" },
            { value: "variable_speed", label: "Variable-Speed Inverter Drive" },
            { value: "cooling_zone", label: "Cooling Zone" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
      ],
    },

    {
      id: "physical",
      title: "Physical",
      order: 60,
      formTab: "logistics",
      fields: [
        {
          id: "machine_weight_kg",
          key: "machine_weight_kg",
          label: "Machine Weight",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net weight of the machine.",
          suggestions: [500, 800, 1200, 1800, 2500],
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "machine_dimensions",
          key: "machine_dimensions",
          label: "Machine Dimensions (L×W×H)",
          order: 10,
          fieldType: "dimension",
          dataType: "string",
          unit: "mm",
          required: false,
          description: "Overall machine dimensions in mm (L×W×H).",
          ...pub,
          visualRenderType: "packing_block",
        },
      ],
    },

    {
      id: "packing-shipping",
      title: "Packing & Shipping",
      order: 65,
      formTab: "logistics",
      fields: [
        {
          id: "packing_dimensions",
          key: "packing_dimensions",
          label: "Packing Dimensions (L×W×H)",
          order: 20,
          fieldType: "dimension",
          dataType: "string",
          unit: "mm",
          required: false,
          description: "Packed crate dimensions in mm (L×W×H).",
          ...pub,
          visualRenderType: "packing_block",
        },
        {
          id: "cbm",
          key: "cbm",
          label: "CBM",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m³",
          required: false,
          description: "Packed volume in cubic metres.",
          ...pub,
          computed: { from: "packing_dimensions", formula: "cbm_m3_from_mm_dimensions" },
          visualRenderType: "spec_card",
        },
        {
          id: "net_weight",
          key: "net_weight",
          label: "Net Weight (N.W.)",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net shipping weight on the packing list.",
          ...pub,
          computed: { from: "machine_weight_kg", formula: "copy_number" },
          visualRenderType: "spec_card",
        },
        {
          id: "gross_weight",
          key: "gross_weight",
          label: "Gross Weight",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Gross shipping weight.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "packing_type",
          key: "packing_type",
          label: "Packing Type",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How the machine is packed for shipment.",
          options: [
            { value: "wooden_case", label: "Wooden Case" },
            { value: "plywood_crate", label: "Plywood Crate" },
            { value: "carton", label: "Carton" },
            { value: "pallet_film", label: "Pallet + Stretch Film" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "container_20ft_qty",
          key: "container_20ft_qty",
          label: "Qty per 20ft Container",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 20ft container.",
          ...pub,
          computed: { from: "cbm", formula: "qty_per_20ft_from_cbm" },
          visualRenderType: "spec_card",
        },
        {
          id: "container_40ft_qty",
          key: "container_40ft_qty",
          label: "Qty per 40ft Container",
          order: 70,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 40ft STANDARD container.",
          ...pub,
          computed: { from: "cbm", formula: "qty_per_40ft_from_cbm" },
          visualRenderType: "spec_card",
        },
        {
          id: "container_40hq_qty",
          key: "container_40hq_qty",
          label: "Qty per 40HQ Container",
          order: 80,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 40ft High-Cube container.",
          ...pub,
          computed: { from: "cbm", formula: "qty_per_40hq_from_cbm" },
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "safety-compliance",
      title: "Safety & Compliance",
      order: 70,
      fields: [
        {
          id: "safety_features",
          key: "safety_features",
          label: "Safety Features",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Built-in operator- and machine-safety systems.",
          options: [
            { value: "emergency_stop", label: "Emergency Stop" },
            { value: "overheat_protection", label: "Over-Heat Protection" },
            { value: "steam_safety_valve", label: "Steam Safety Valve" },
            { value: "guard_covers", label: "Guard Covers" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
        {
          id: "certifications",
          key: "certifications",
          label: "Certifications",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Quality and compliance certifications.",
          options: [
            { value: "ce", label: "CE" },
            { value: "iso9001", label: "ISO 9001" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
      ],
    },
  ],
};
