/**
 * Fabric Handling / Pre-shrinking Systems — subcategory code XPRH (v1)
 *
 * The owner's 「面料处理系统」 (steam pre-shrink + cooling tunnel). NOTE on the
 * code: the live DB subcategory under fabric-preparation is "XPRH — Fabric
 * Handling Systems"; the types-master reserves XPRH for the Rotary Heat Press
 * (different category), and ▲ XPRP is the PROPOSED replacement token — the
 * resolver keys on division|category|subcategory so the reuse is unambiguous
 * here. When governance renames the subcategory to XPRP, only
 * `subcategoryCode` below changes. Templates only — no values here.
 */

import type { ProductSchemaDefinition } from "@/types/product-schema";
import {
  DEFAULT_PUBLIC_VISIBILITY,
  DEFAULT_TECHNICAL_VISIBILITY,
} from "../visibility";

const tech = DEFAULT_TECHNICAL_VISIBILITY;
const pub = DEFAULT_PUBLIC_VISIBILITY;

export const FABRIC_PRESHRINK_SCHEMA: ProductSchemaDefinition = {
  id: "fabric-preshrink.v1",
  divisionCode: "garment-machinery",
  categoryCode: "fabric-preparation",
  subcategoryCode: "XPRH",
  name: "Fabric Handling / Pre-shrinking System",
  version: "1.0.0",
  appliesTo: {
    description:
      "Steam pre-shrinking and stabilising lines — steam chamber, dwell and cooling zone — that pre-shrink fabric before cutting so garments hold their size.",
  },
  groups: [
    {
      id: "type-application",
      title: "Type & Application",
      order: 10,
      fields: [
        {
          id: "heating_method",
          key: "heating_method",
          anchor: true,
          importance: "high",
          anchorPriority: 10,
          label: "Heating Method",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: true,
          description: "Heat source for the steam/treatment chamber.",
          options: [
            { value: "steam", label: "Steam" },
            { value: "electric", label: "Electric" },
            { value: "electric_steam", label: "Electric-Generated Steam" },
            { value: "gas", label: "Gas" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "cooling_method",
          key: "cooling_method",
          label: "Cooling Method",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How fabric is cooled after the steam zone.",
          options: [
            { value: "ambient_air", label: "Ambient Air" },
            { value: "forced_air", label: "Forced Cold Air" },
            { value: "chilled_rollers", label: "Chilled Rollers" },
            { value: "vacuum_cooling", label: "Vacuum Cooling" },
          ],
          ...pub,
          comparable: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "fabric_compatibility",
          key: "fabric_compatibility",
          anchor: true,
          importance: "high",
          anchorPriority: 20,
          label: "Fabric Compatibility",
          order: 30,
          fieldType: "multi_select",
          dataType: "json",
          required: true,
          description: "Fabric constructions the line can treat.",
          options: [
            { value: "knit", label: "Knit" },
            { value: "woven", label: "Woven" },
            { value: "elastic", label: "Elastic / Spandex" },
            { value: "wool", label: "Wool / Suiting" },
            { value: "delicate", label: "Delicate Fabrics" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "material_card",
        },
        {
          id: "automation_level",
          key: "automation_level",
          label: "Automation Level",
          order: 40,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Degree of automation.",
          options: [
            { value: "semi_automatic", label: "Semi-Automatic" },
            { value: "automatic", label: "Automatic" },
            { value: "programmable", label: "Programmable (Recipe Control)" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
      ],
    },

    {
      id: "process-performance",
      title: "Process Performance",
      order: 20,
      fields: [
        {
          id: "max_fabric_width",
          key: "max_fabric_width",
          importance: "critical",
          anchor: true,
          anchorPriority: 30,
          label: "Max Fabric Width",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: true,
          description: "Maximum fabric width the line can treat.",
          suggestions: [1800, 2000, 2200, 2400, 2600],
          ...tech,
          comparable: true,
          filterVisible: true,
          visualRenderType: "metric_block",
        },
        {
          id: "max_working_speed",
          key: "max_working_speed",
          importance: "high",
          label: "Max Working Speed",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m/min",
          required: false,
          description: "Top line speed.",
          suggestions: [10, 15, 20, 30],
          ...pub,
          comparable: true,
          visualRenderType: "metric_block",
        },
        {
          id: "normal_preshrink_speed",
          key: "normal_preshrink_speed",
          label: "Normal Pre-shrink Speed",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m/min",
          required: false,
          description: "Recommended speed for full shrinkage release.",
          suggestions: [6, 8, 10, 15],
          ...tech,
          visualRenderType: "spec_card",
        },
        {
          id: "max_operating_temp",
          key: "max_operating_temp",
          label: "Max Operating Temperature",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "°C",
          required: false,
          description: "Highest chamber temperature.",
          suggestions: [100, 110, 120, 135],
          ...tech,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "chamber_humidity",
          key: "chamber_humidity",
          label: "Steam Chamber Humidity",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "%RH",
          required: false,
          description: "Relative humidity in the steam chamber.",
          suggestions: [80, 90, 95, 100],
          ...tech,
          visualRenderType: "spec_card",
        },
        {
          id: "exit_temp",
          key: "exit_temp",
          label: "Cooling-Zone Exit Temperature",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "°C",
          required: false,
          description: "Fabric temperature leaving the cooling zone.",
          suggestions: [30, 35, 40],
          ...tech,
          visualRenderType: "spec_card",
        },
        {
          id: "temp_control_accuracy",
          key: "temp_control_accuracy",
          label: "Temperature Control Accuracy",
          order: 70,
          fieldType: "unit_number",
          dataType: "number",
          unit: "± °C",
          required: false,
          description: "Chamber temperature regulation tolerance.",
          suggestions: [1, 2, 3],
          ...tech,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "cooling_zone_length",
          key: "cooling_zone_length",
          label: "Cooling Zone Length",
          order: 80,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m",
          required: false,
          description: "Length of the cooling section.",
          suggestions: [1.5, 2, 3, 4],
          ...tech,
          visualRenderType: "spec_card",
        },
        {
          id: "resting_time",
          key: "resting_time",
          label: "Recommended Resting Time",
          order: 90,
          fieldType: "unit_number",
          dataType: "number",
          unit: "h",
          required: false,
          description: "Fabric dwell time before treatment for best results.",
          suggestions: [12, 24, 48],
          ...tech,
          visualRenderType: "spec_card",
        },
        {
          id: "steam_consumption",
          key: "steam_consumption",
          label: "Steam Consumption",
          order: 100,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg/h",
          required: false,
          description: "Steam usage at rated speed.",
          suggestions: [50, 80, 120, 180],
          ...tech,
          comparable: true,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "handling",
      title: "Handling",
      order: 30,
      fields: [
        {
          id: "feeding_method",
          key: "feeding_method",
          label: "Feeding Method",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How fabric enters the line.",
          options: [
            { value: "roll_letoff", label: "Roll Let-off" },
            { value: "plait_feed", label: "Plaited-Fabric Feed" },
            { value: "j_box", label: "J-Box Accumulator" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "discharge_method",
          key: "discharge_method",
          label: "Discharge Method",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How treated fabric leaves the line.",
          options: [
            { value: "rewind", label: "Re-Wind to Roll" },
            { value: "plaiter", label: "Plaiter (Folded Output)" },
            { value: "both", label: "Roll + Plait" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "edge_alignment_accuracy",
          key: "edge_alignment_accuracy",
          label: "Edge Alignment Accuracy",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "± mm",
          required: false,
          description: "Edge-to-edge alignment tolerance at output.",
          suggestions: [2, 3, 5],
          ...tech,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "electrical-utilities",
      title: "Electrical & Utilities",
      order: 40,
      fields: [
        {
          id: "total_installed_power",
          key: "total_installed_power",
          label: "Total Installed Power",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kW",
          required: false,
          description: "Total connected electrical load.",
          suggestions: [8, 12, 18, 25, 40],
          ...pub,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "voltage_options",
          key: "voltage_options",
          label: "Voltage",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Rated supply voltage.",
          options: [
            { value: "220v", label: "220 V" },
            { value: "380v", label: "380 V" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "phase",
          key: "phase",
          label: "Power Phase",
          order: 30,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Electrical supply phase.",
          options: [{ value: "three_phase", label: "Three Phase (3PH)" }],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "steam_pressure",
          key: "steam_pressure",
          label: "Steam Pressure Requirement",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "bar",
          required: false,
          description: "Required steam supply pressure.",
          suggestions: [3, 4, 5, 6],
          ...tech,
          visualRenderType: "spec_card",
        },
        {
          id: "air_pressure",
          key: "air_pressure",
          label: "Air Pressure",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "bar",
          required: false,
          description: "Compressed-air supply requirement.",
          suggestions: [4, 5, 6],
          ...tech,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "equipment-options",
      title: "Equipment & Options",
      order: 50,
      fields: [
        {
          id: "equipment_features",
          key: "equipment_features",
          label: "Equipment & Features",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Fitted equipment and available options.",
          options: [
            { value: "recipe_memory", label: "Recipe / Program Memory" },
            { value: "plaiter", label: "Plaiter" },
            { value: "j_box", label: "J-Box Accumulator" },
            { value: "length_counter", label: "Length Counter" },
            { value: "moisture_sensor", label: "Moisture Sensor" },
            { value: "extended_cooling", label: "Extended Cooling Zone" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
      ],
    },

    {
      id: "physical",
      title: "Physical",
      order: 60,
      formTab: "logistics",
      fields: [
        {
          id: "machine_weight_kg",
          key: "machine_weight_kg",
          label: "Machine Weight",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net weight of the line.",
          suggestions: [1500, 2500, 4000, 6000],
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "machine_dimensions",
          key: "machine_dimensions",
          label: "Machine Dimensions (L×W×H)",
          order: 20,
          fieldType: "dimension",
          dataType: "string",
          unit: "mm",
          required: false,
          description: "Overall line dimensions in mm (L×W×H).",
          ...pub,
          visualRenderType: "packing_block",
        },
      ],
    },

    {
      id: "packing-shipping",
      title: "Packing & Shipping",
      order: 65,
      formTab: "logistics",
      fields: [
        {
          id: "packing_dimensions",
          key: "packing_dimensions",
          label: "Packing Dimensions (L×W×H)",
          order: 10,
          fieldType: "dimension",
          dataType: "string",
          unit: "mm",
          required: false,
          description: "Packed crate dimensions in mm (L×W×H).",
          ...pub,
          visualRenderType: "packing_block",
        },
        {
          id: "cbm",
          key: "cbm",
          label: "CBM",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m³",
          required: false,
          description: "Packed volume in cubic metres.",
          ...pub,
          computed: { from: "packing_dimensions", formula: "cbm_m3_from_mm_dimensions" },
          visualRenderType: "spec_card",
        },
        {
          id: "gross_weight",
          key: "gross_weight",
          label: "Gross Weight",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Gross shipping weight.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "packing_type",
          key: "packing_type",
          label: "Packing Type",
          order: 40,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How the machine is packed for shipment.",
          options: [
            { value: "wooden_case", label: "Wooden Case" },
            { value: "plywood_crate", label: "Plywood Crate" },
            { value: "carton", label: "Carton" },
            { value: "pallet_film", label: "Pallet + Stretch Film" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "container_20ft_qty",
          key: "container_20ft_qty",
          label: "Qty per 20ft Container",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 20ft container.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "container_40ft_qty",
          key: "container_40ft_qty",
          label: "Qty per 40ft / 40HQ Container",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "units",
          required: false,
          description: "How many units load into one 40ft/40HQ container.",
          ...pub,
          visualRenderType: "spec_card",
        },
      ],
    },

    {
      id: "safety-compliance",
      title: "Safety & Compliance",
      order: 70,
      fields: [
        {
          id: "safety_features",
          key: "safety_features",
          label: "Safety Features",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Built-in operator- and machine-safety systems.",
          options: [
            { value: "emergency_stop", label: "Emergency Stop" },
            { value: "overheat_protection", label: "Over-Heat Protection" },
            { value: "steam_safety_valve", label: "Steam Safety Valve" },
            { value: "door_interlock", label: "Chamber Door Interlock" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
        {
          id: "certifications",
          key: "certifications",
          label: "Certifications",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Quality and compliance certifications.",
          options: [
            { value: "ce", label: "CE" },
            { value: "iso9001", label: "ISO 9001" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
      ],
    },
  ],
};
