/**
 * Lockstitch — Standard Single Needle (v1)
 *
 * First complete machine-kind schema in the Koleex product-schema system.
 * Serves as the canonical template for future machine-kind schemas (overlock,
 * coverstitch, buttonhole, etc.). Field structure, visibility spreads, group
 * ordering conventions, and visualRenderType usage here should be mirrored by
 * subsequent kinds to keep the catalog UI and data layer consistent.
 */

import type { ProductSchemaDefinition } from "@/types/product-schema";
import {
  DEFAULT_PUBLIC_VISIBILITY,
  DEFAULT_INTERNAL_VISIBILITY,
  DEFAULT_COMMERCIAL_VISIBILITY,
  DEFAULT_TECHNICAL_VISIBILITY,
} from "../visibility";

const tech = DEFAULT_TECHNICAL_VISIBILITY;
const pub = DEFAULT_PUBLIC_VISIBILITY;
const internal = DEFAULT_INTERNAL_VISIBILITY;
const commercial = DEFAULT_COMMERCIAL_VISIBILITY;

// Suppress unused-warning for `commercial` — kept exported-style alias so future
// fields can opt into commercial visibility without re-importing.
void commercial;

export const LOCKSTITCH_SCHEMA: ProductSchemaDefinition = {
  id: "lockstitch.standard-single-needle.v1",
  /* Keyed to the ACTUAL taxonomy the resolver is fed (see resolveSchema
     call sites): products carry division_slug + category_slug (slugs, not
     codes — divisions/categories have no code column) and we resolve the
     subcategory via subcategories.code. The real Lockstitch subcategory
     code is XSL (XCS is straight-knife cutting). machineKindId is omitted
     so the schema registers at the SUBCATEGORY level — the ladder step that
     products actually hit, since resolveSchema is called without a machine
     kind. The machine kind lives in `name`. */
  divisionCode: "garment-machinery",
  categoryCode: "industrial-sewing-machines",
  subcategoryCode: "XSL",
  name: "Standard Single Needle Lockstitch",
  version: "1.0.0",
  appliesTo: {
    description:
      "Single-needle industrial lockstitch sewing machines used for general apparel, denim, shirts, and uniform production.",
  },
  groups: [
    // ------------------------------------------------------------------
    // Group 1 — Performance
    // ------------------------------------------------------------------
    {
      id: "performance",
      title: "Performance",
      order: 10,
      fields: [
        {
          id: "max_sewing_speed",
          key: "max_sewing_speed",
          importance: "critical",
          anchorPriority: 10,
          insight:
            "High-speed output engineered for high-volume apparel lines — more garments per shift without sacrificing stitch quality.",
          label: "Max Sewing Speed",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "SPM",
          required: true,
          description: "Maximum stitches per minute the machine can sustain.",
          ...tech,
          comparable: true,
          filterVisible: true,
          visualRenderType: "metric_block",
        },
        {
          id: "stitch_length_min",
          key: "stitch_length_min",
          label: "Stitch Length (Min)",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Shortest stitch length the machine can produce.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "stitch_length_max",
          key: "stitch_length_max",
          label: "Stitch Length (Max)",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Longest stitch length the machine can produce.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "presser_foot_lift",
          key: "presser_foot_lift",
          label: "Presser Foot Lift",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Maximum vertical lift of the presser foot.",
          ...pub,
          visualRenderType: "spec_card",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 2 — Needle & Thread
    // ------------------------------------------------------------------
    {
      id: "needle-thread",
      title: "Needle & Thread",
      order: 20,
      fields: [
        {
          id: "needle_system",
          key: "needle_system",
          label: "Needle System",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Industrial needle system used by the machine.",
          options: [
            { value: "dpx5", label: "DPx5" },
            { value: "dpx17", label: "DPx17" },
            { value: "dbxk5", label: "DBxK5" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "needle_size_range",
          key: "needle_size_range",
          label: "Needle Size Range",
          order: 20,
          fieldType: "text",
          dataType: "string",
          required: false,
          description: "Compatible needle gauge range (e.g. 9–18).",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "thread_type_supported",
          key: "thread_type_supported",
          label: "Thread Types Supported",
          order: 30,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Thread fiber types the machine can sew reliably.",
          options: [
            { value: "polyester", label: "Polyester" },
            { value: "cotton", label: "Cotton" },
            { value: "nylon", label: "Nylon" },
            { value: "silk", label: "Silk" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 3 — Mechanical
    // ------------------------------------------------------------------
    {
      id: "mechanical",
      title: "Mechanical",
      order: 30,
      fields: [
        {
          id: "motor_type",
          key: "motor_type",
          anchor: true,
          importance: "high",
          anchorPriority: 20,
          insight:
            "Direct-drive servo delivers instant stop/start and precise torque at low speed — no belt slip, no clutch lag, less operator fatigue.",
          label: "Motor Type",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Drive motor technology powering the machine head.",
          options: [
            { value: "servo", label: "Servo" },
            { value: "clutch", label: "Clutch" },
            { value: "direct_drive", label: "Direct Drive" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "feed_mechanism",
          key: "feed_mechanism",
          label: "Feed Mechanism",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How the fabric is advanced under the needle.",
          options: [
            { value: "drop_feed", label: "Drop Feed" },
            { value: "compound_feed", label: "Compound Feed" },
            { value: "unison_feed", label: "Unison Feed" },
            { value: "walking_foot", label: "Walking Foot" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "hook_looper_type",
          key: "hook_looper_type",
          label: "Hook / Looper Type",
          order: 30,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Rotary or oscillating hook configuration.",
          options: [
            { value: "rotary", label: "Rotary" },
            { value: "oscillating", label: "Oscillating" },
            { value: "vertical", label: "Vertical" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "lubrication_system",
          key: "lubrication_system",
          anchor: true,
          importance: "high",
          anchorPriority: 30,
          insight:
            "Semi-dry head lubricates only the hook race — keeps whites and pastels stain-free, cutting reject rates on premium fabric.",
          label: "Lubrication System",
          order: 40,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Method used to lubricate moving parts.",
          options: [
            { value: "auto", label: "Automatic" },
            { value: "manual", label: "Manual" },
            { value: "semi_dry", label: "Semi-Dry" },
            { value: "dry", label: "Dry Head" },
          ],
          ...pub,
          visualRenderType: "spec_card",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 4 — Material Capability
    // ------------------------------------------------------------------
    {
      id: "material",
      title: "Material Capability",
      order: 40,
      fields: [
        {
          id: "material_weight",
          key: "material_weight",
          anchor: true,
          importance: "high",
          anchorPriority: 40,
          insight:
            "Tuned for medium-weight fabric — the everyday sweet spot for shirts, denim, and general apparel production.",
          label: "Material Weight",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Weight class of fabrics the machine handles best.",
          options: [
            { value: "light", label: "Light" },
            { value: "medium", label: "Medium" },
            { value: "heavy", label: "Heavy" },
            { value: "extra_heavy", label: "Extra Heavy" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "icon_chip",
        },
        {
          id: "suitable_fabrics",
          key: "suitable_fabrics",
          label: "Suitable Fabrics",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Fabric materials the machine is suited to sew.",
          options: [
            { value: "cotton", label: "Cotton" },
            { value: "denim", label: "Denim" },
            { value: "silk", label: "Silk" },
            { value: "wool", label: "Wool" },
            { value: "polyester", label: "Polyester" },
            { value: "linen", label: "Linen" },
            { value: "knit", label: "Knit" },
            { value: "leather", label: "Leather" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "material_card",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 5 — Application
    // ------------------------------------------------------------------
    {
      id: "application",
      title: "Application",
      order: 50,
      fields: [
        {
          id: "industry_applications",
          key: "industry_applications",
          label: "Industry Applications",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Industries that commonly deploy this machine.",
          options: [
            { value: "apparel", label: "Apparel" },
            { value: "denim_jeans", label: "Denim & Jeans" },
            { value: "shirts", label: "Shirts" },
            { value: "suits", label: "Suits" },
            { value: "sportswear", label: "Sportswear" },
            { value: "lingerie", label: "Lingerie" },
            { value: "uniforms", label: "Uniforms" },
            { value: "leather_goods", label: "Leather Goods" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "application_card",
        },
        {
          id: "suitable_garments",
          key: "suitable_garments",
          label: "Suitable Garments",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Garment types frequently produced on this machine.",
          options: [
            { value: "shirts", label: "Shirts" },
            { value: "trousers", label: "Trousers" },
            { value: "jackets", label: "Jackets" },
            { value: "dresses", label: "Dresses" },
            { value: "jeans", label: "Jeans" },
            { value: "workwear", label: "Workwear" },
          ],
          ...pub,
          visualRenderType: "application_card",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 6 — Lockstitch Configuration
    // ------------------------------------------------------------------
    {
      id: "lockstitch-config",
      title: "Lockstitch Configuration",
      order: 60,
      fields: [
        {
          id: "bed_type",
          key: "bed_type",
          anchor: true,
          importance: "normal",
          anchorPriority: 60,
          label: "Bed Type",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: true,
          description: "Form factor of the machine bed.",
          options: [
            { value: "flat", label: "Flat Bed" },
            { value: "cylinder", label: "Cylinder Bed" },
            { value: "post", label: "Post Bed" },
            { value: "long_arm", label: "Long Arm" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "hook_size",
          key: "hook_size",
          label: "Hook Size",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Relative size class of the rotary hook.",
          options: [
            { value: "small", label: "Small" },
            { value: "standard", label: "Standard" },
            { value: "large", label: "Large" },
            { value: "x-large", label: "X-Large" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "bobbin_type",
          key: "bobbin_type",
          label: "Bobbin Type",
          order: 30,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Bobbin case standard used by the hook.",
          options: [
            { value: "standard", label: "Standard M" },
            { value: "large_l", label: "Large L" },
            { value: "large_m", label: "Large M" },
          ],
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "max_material_thickness",
          key: "max_material_thickness",
          anchor: false,
          label: "Max Material Thickness",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Thickest material the machine can sew under the foot.",
          ...pub,
          comparable: true,
          visualRenderType: "metric_block",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 7 — Stitch & Feed
    // ------------------------------------------------------------------
    {
      id: "stitch-feed",
      title: "Stitch & Feed",
      order: 70,
      fields: [
        {
          id: "stitch_pattern",
          key: "stitch_pattern",
          label: "Stitch Pattern",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Stitch structure produced by the machine.",
          options: [
            { value: "lockstitch", label: "Lockstitch" },
            { value: "chain_stitch", label: "Chain Stitch" },
            { value: "zigzag", label: "Zigzag" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "reverse_feed",
          key: "reverse_feed",
          label: "Reverse Feed",
          order: 20,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Supports back-tacking by reversing feed direction.",
          ...pub,
          visualRenderType: "boolean_feature",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 8 — Automation
    // ------------------------------------------------------------------
    {
      id: "automation",
      title: "Automation",
      order: 80,
      fields: [
        {
          id: "auto_thread_trimmer",
          key: "auto_thread_trimmer",
          anchor: true,
          importance: "high",
          anchorPriority: 50,
          insight:
            "Automatic thread trimming removes a manual step every seam — faster cycle times and consistent thread tails across operators.",
          label: "Auto Thread Trimmer",
          order: 10,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Automatically trims thread at cycle end.",
          ...pub,
          comparable: true,
          visualRenderType: "boolean_feature",
        },
        {
          id: "auto_back_tack",
          key: "auto_back_tack",
          label: "Auto Back Tack",
          order: 20,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Automatically performs back-tacking at seam ends.",
          ...pub,
          visualRenderType: "boolean_feature",
        },
        {
          id: "auto_presser_foot_lifter",
          key: "auto_presser_foot_lifter",
          label: "Auto Presser Foot Lifter",
          order: 30,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Lifts the presser foot automatically between operations.",
          ...pub,
          visualRenderType: "boolean_feature",
        },
        {
          id: "auto_thread_wiper",
          key: "auto_thread_wiper",
          label: "Auto Thread Wiper",
          order: 40,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Wipes the thread tail away after trimming.",
          ...pub,
          visualRenderType: "boolean_feature",
        },
        {
          id: "needle_positioning",
          key: "needle_positioning",
          label: "Needle Positioning",
          order: 50,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Automatic needle stop position behavior.",
          options: [
            { value: "up", label: "Up" },
            { value: "down", label: "Down" },
            { value: "both", label: "Up + Down" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 9 — Electrical
    // ------------------------------------------------------------------
    {
      id: "electrical",
      title: "Electrical",
      order: 90,
      fields: [
        {
          id: "voltage_options",
          key: "voltage_options",
          label: "Voltage Options",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: true,
          description: "Supply voltages the machine can be configured for.",
          options: [
            { value: "110V", label: "110 V" },
            { value: "220V", label: "220 V" },
            { value: "380V", label: "380 V" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "frequency_hz",
          key: "frequency_hz",
          label: "Frequency",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Mains frequency compatibility.",
          options: [
            { value: "50", label: "50 Hz" },
            { value: "60", label: "60 Hz" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "motor_power_w",
          key: "motor_power_w",
          anchor: true,
          anchorGroup: "performance",
          anchorPriority: 25,
          insight:
            "Right-sized servo power for continuous duty — strong enough for medium-heavy seams, efficient enough to cut energy cost per shift.",
          label: "Motor Power",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "W",
          required: true,
          description: "Rated power output of the drive motor.",
          ...pub,
          comparable: true,
          visualRenderType: "metric_block",
        },
        {
          id: "power_consumption_w",
          key: "power_consumption_w",
          anchor: false,
          label: "Power Consumption",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "W",
          required: false,
          description: "Typical electrical power draw during operation.",
          ...pub,
          comparable: true,
          visualRenderType: "metric_block",
        },
        {
          id: "phase",
          key: "phase",
          label: "Phase",
          order: 50,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Single- or three-phase power requirement.",
          options: [
            { value: "single", label: "Single Phase" },
            { value: "three", label: "Three Phase" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "plug_types",
          key: "plug_types",
          label: "Plug Types",
          order: 60,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "IEC plug type letters supported for the cordset.",
          options: [
            { value: "A", label: "Type A" },
            { value: "B", label: "Type B" },
            { value: "C", label: "Type C" },
            { value: "D", label: "Type D" },
            { value: "E", label: "Type E" },
            { value: "F", label: "Type F" },
            { value: "G", label: "Type G" },
            { value: "H", label: "Type H" },
            { value: "I", label: "Type I" },
            { value: "J", label: "Type J" },
            { value: "K", label: "Type K" },
            { value: "L", label: "Type L" },
            { value: "M", label: "Type M" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
        {
          id: "pneumatic_supply_required",
          key: "pneumatic_supply_required",
          label: "Pneumatic Supply Required",
          order: 70,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Requires compressed air for automation features.",
          ...pub,
          visualRenderType: "boolean_feature",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 10 — Physical
    // ------------------------------------------------------------------
    {
      id: "physical",
      title: "Physical",
      order: 100,
      fields: [
        {
          id: "machine_dimensions",
          key: "machine_dimensions",
          label: "Machine Dimensions",
          order: 10,
          fieldType: "dimension",
          dataType: "json",
          unit: "mm",
          required: false,
          description: "Overall length, width, and height of the machine head.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "machine_weight_kg",
          key: "machine_weight_kg",
          label: "Machine Weight",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net weight of the machine head.",
          ...pub,
          visualRenderType: "metric_block",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 11 — Compliance & Customs
    // ------------------------------------------------------------------
    {
      id: "compliance",
      title: "Compliance & Customs",
      order: 110,
      fields: [
        {
          id: "hs_code",
          key: "hs_code",
          label: "HS Code",
          order: 10,
          fieldType: "text",
          dataType: "string",
          required: false,
          description: "Harmonized System tariff code used for customs.",
          ...internal,
          quoteVisible: true,
          invoiceVisible: true,
          visualRenderType: "plain_text",
        },
        {
          id: "ip_rating",
          key: "ip_rating",
          label: "IP Rating",
          order: 20,
          fieldType: "text",
          dataType: "string",
          required: false,
          description: "Ingress protection rating of the enclosure.",
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "operating_temperature",
          key: "operating_temperature",
          label: "Operating Temperature",
          order: 30,
          fieldType: "range",
          dataType: "json",
          unit: "°C",
          required: false,
          description: "Ambient temperature range for normal operation.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "ce_certified",
          key: "ce_certified",
          label: "CE Certified",
          order: 40,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Carries CE marking for the European Economic Area.",
          ...pub,
          comparable: true,
          visualRenderType: "boolean_feature",
        },
        {
          id: "rohs_compliant",
          key: "rohs_compliant",
          label: "RoHS Compliant",
          order: 50,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Complies with the EU RoHS hazardous-substances directive.",
          ...pub,
          comparable: true,
          visualRenderType: "boolean_feature",
        },
        {
          id: "oil_mist_filter",
          key: "oil_mist_filter",
          label: "Oil Mist Filter",
          order: 60,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Includes an oil mist filter for cleaner operation.",
          ...pub,
          visualRenderType: "boolean_feature",
        },
        {
          id: "colors",
          key: "colors",
          label: "Available Colors",
          order: 70,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Standard housing colors offered for this machine.",
          options: [
            { value: "white", label: "White" },
            { value: "silver", label: "Silver" },
            { value: "green", label: "Industrial Green" },
            { value: "black", label: "Black" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 12 — Purchase Options
    // ------------------------------------------------------------------
    {
      id: "purchase-options",
      title: "Purchase Options",
      order: 120,
      fields: [
        {
          id: "supports_head_only",
          key: "supports_head_only",
          label: "Supports Head-Only Purchase",
          order: 10,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Available for sale as a head unit without stand or motor.",
          ...internal,
          quoteVisible: true,
          invoiceVisible: true,
          visualRenderType: "boolean_feature",
        },
        {
          id: "supports_complete_set",
          key: "supports_complete_set",
          label: "Supports Complete Set Purchase",
          order: 20,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Available for sale as a complete set with stand, motor, and table.",
          ...internal,
          quoteVisible: true,
          invoiceVisible: true,
          visualRenderType: "boolean_feature",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 13 — Fulfillment Defaults
    // ------------------------------------------------------------------
    {
      id: "fulfillment",
      title: "Fulfillment Defaults",
      order: 130,
      fields: [
        {
          id: "moq",
          key: "moq",
          label: "Minimum Order Quantity",
          order: 10,
          fieldType: "number",
          dataType: "number",
          required: false,
          description: "Default minimum order quantity for this machine.",
          ...internal,
          quoteVisible: true,
          visualRenderType: "plain_text",
        },
        {
          id: "lead_time",
          key: "lead_time",
          label: "Lead Time",
          order: 20,
          fieldType: "text",
          dataType: "string",
          required: false,
          description: "Default production and shipping lead time.",
          ...internal,
          quoteVisible: true,
          brochureVisible: true,
          visualRenderType: "plain_text",
        },
      ],
    },
  ],
};
