/**
 * Spreading Machines — Fully Automatic Fabric Spreader (v1)
 *
 * Second complete subcategory schema in the Koleex product-schema system,
 * modeled on lockstitch.ts. Resolves at the SUBCATEGORY level: products carry
 * division_slug (garment-machinery) + category_slug (fabric-preparation) and
 * the resolver matches the subcategory via subcategories.code = "XPRS".
 *
 * Field set distilled from the KOLEEX A10 operation manual (our own machine)
 * plus competitor spec sheets (Tesan AS200 family, Benma BR-1900, Yili YL-S,
 * Dison DS, Feiyue FYK). Deep drive/servo/fault-code content from the manual is
 * intentionally EXCLUDED — that is service-manual material, not product-page
 * spec. Per-width variants (1.6–3.0 m) are handled at the model layer, not here.
 */

import type { ProductSchemaDefinition } from "@/types/product-schema";
import {
  DEFAULT_PUBLIC_VISIBILITY,
  DEFAULT_INTERNAL_VISIBILITY,
  DEFAULT_TECHNICAL_VISIBILITY,
} from "../visibility";

const tech = DEFAULT_TECHNICAL_VISIBILITY;
const pub = DEFAULT_PUBLIC_VISIBILITY;
const internal = DEFAULT_INTERNAL_VISIBILITY;
void internal;

export const SPREADING_MACHINES_SCHEMA: ProductSchemaDefinition = {
  id: "spreading-machines.fully-automatic.v1",
  divisionCode: "garment-machinery",
  categoryCode: "fabric-preparation",
  subcategoryCode: "XPRS",
  name: "Fully Automatic Fabric Spreader",
  version: "1.0.0",
  appliesTo: {
    description:
      "Automatic cloth-spreading machines that lay fabric in even, tension-free plies onto a cutting table ahead of cutting — for knit and woven, roll and folded fabric.",
  },
  groups: [
    // ------------------------------------------------------------------
    // Group 1 — Type & Application
    // ------------------------------------------------------------------
    {
      id: "type-application",
      title: "Type & Application",
      order: 10,
      fields: [
        {
          id: "spreader_type",
          key: "spreader_type",
          anchor: true,
          importance: "high",
          anchorPriority: 20,
          label: "Spreader Type",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: true,
          description: "Machine configuration / body style.",
          options: [
            { value: "standard", label: "Standard" },
            { value: "heavy_duty", label: "Heavy-Duty" },
            { value: "large", label: "Large Format" },
            { value: "turn_table", label: "Turn-Table" },
            { value: "tubular", label: "Tubular" },
            { value: "two_in_one", label: "Two-in-One (Knit + Woven)" },
            { value: "mini", label: "Mini / Compact" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "fabric_compatibility",
          key: "fabric_compatibility",
          anchor: true,
          importance: "high",
          anchorPriority: 30,
          insight:
            "Handles both knit and woven, roll and folded fabric — one machine covers the mill's full fabric range instead of dedicated units per type.",
          label: "Fabric Compatibility",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: true,
          description: "Fabric constructions and formats the machine can spread.",
          options: [
            { value: "knit", label: "Knit" },
            { value: "woven", label: "Woven" },
            { value: "roll", label: "Roll Fabric" },
            { value: "folded", label: "Folded Fabric" },
            { value: "tubular", label: "Tubular Fabric" },
            { value: "piece", label: "Piece Fabric" },
            { value: "stepped", label: "Stepped / Ladder Fabric" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "material_card",
        },
        {
          id: "suitable_for",
          key: "suitable_for",
          label: "Suitable For",
          order: 30,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Products and industries the spreader commonly serves.",
          options: [
            { value: "t_shirts", label: "T-Shirts" },
            { value: "shirts", label: "Shirts" },
            { value: "denim", label: "Denim & Jeans" },
            { value: "childrens_wear", label: "Children's Wear" },
            { value: "home_textile", label: "Home Textile" },
            { value: "underwear", label: "Underwear" },
            { value: "swimwear", label: "Swimwear" },
            { value: "sportswear", label: "Sportswear" },
            { value: "trousers", label: "Trousers" },
            { value: "jackets", label: "Jackets" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "application_card",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 2 — Spreading Performance
    // ------------------------------------------------------------------
    {
      id: "spreading-performance",
      title: "Spreading Performance",
      order: 20,
      fields: [
        {
          id: "max_cloth_width",
          key: "max_cloth_width",
          importance: "critical",
          anchor: true,
          anchorPriority: 10,
          insight:
            "Determines the widest lay the machine can spread — match it to your widest fabric roll so no width is left unusable.",
          label: "Max Cloth Width",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: true,
          description: "Maximum fabric width the machine can spread.",
          ...tech,
          comparable: true,
          filterVisible: true,
          visualRenderType: "metric_block",
        },
        {
          id: "table_width",
          key: "table_width",
          label: "Table Width",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Required cutting-table width for this machine.",
          ...pub,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "travel_speed",
          key: "travel_speed",
          importance: "high",
          anchor: true,
          anchorPriority: 15,
          insight:
            "Higher travel speed means more plies per hour — the direct lever on cutting-room throughput.",
          label: "Travel Speed",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m/min",
          required: false,
          description: "Maximum spreading (carriage) speed.",
          ...tech,
          comparable: true,
          filterVisible: true,
          visualRenderType: "metric_block",
        },
        {
          id: "max_roll_diameter",
          key: "max_roll_diameter",
          label: "Max Fabric Roll Diameter",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Largest fabric roll the cradle accepts.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "max_roll_weight",
          key: "max_roll_weight",
          label: "Max Fabric Roll Weight",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Heaviest fabric roll the cradle can carry.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "lay_height_one_way",
          key: "lay_height_one_way",
          label: "Lay Height — One-Way",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Maximum spread height in one-way (face-up) mode.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "lay_height_zigzag",
          key: "lay_height_zigzag",
          label: "Lay Height — Zigzag / Face-to-Face",
          order: 70,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Maximum spread height in zigzag / double-pull mode.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "lay_height_tubular",
          key: "lay_height_tubular",
          label: "Lay Height — Tubular",
          order: 80,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Maximum spread height with the tubular-fabric unit.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "spreading_methods",
          key: "spreading_methods",
          anchor: true,
          importance: "high",
          anchorPriority: 40,
          insight:
            "The more spreading methods it supports, the more fabric types and marker layouts one machine can handle without extra equipment.",
          label: "Spreading Methods",
          order: 90,
          fieldType: "multi_select",
          dataType: "json",
          required: true,
          description: "Laying patterns the machine can perform.",
          options: [
            { value: "one_way_face_up", label: "One-Way (Face-Up)" },
            { value: "one_way_front_catcher", label: "One-Way with Front Catcher" },
            { value: "zigzag_face_to_face", label: "Zigzag / Face-to-Face" },
            { value: "multiple_length", label: "Multiple-Length Spreading" },
            { value: "tubular", label: "Tubular" },
            { value: "reverse_rolled", label: "Reverse-Rolled" },
            { value: "gradual_stepped", label: "Gradual / Stepped One-Way" },
            { value: "cycle", label: "Cycle Spreading" },
          ],
          ...pub,
          comparable: true,
          filterVisible: true,
          visualRenderType: "icon_chip",
        },
        {
          id: "spreading_mode",
          key: "spreading_mode",
          label: "Spreading Mode",
          order: 100,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Single-pull lays on the forward pass only; double-pull lays both directions.",
          options: [
            { value: "single_pull", label: "Single-Pull" },
            { value: "double_pull", label: "Double-Pull" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 3 — Control & Automation
    // ------------------------------------------------------------------
    {
      id: "control-automation",
      title: "Control & Automation",
      order: 30,
      fields: [
        {
          id: "control_system",
          key: "control_system",
          anchor: true,
          importance: "high",
          anchorPriority: 25,
          insight:
            "Dual AC-servo drive with a multi-CPU controller gives smooth, tension-free spreading and repeatable stop/start accuracy.",
          label: "Control System",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Drive and controller architecture.",
          options: [
            { value: "dual_servo", label: "Dual AC Servo" },
            { value: "single_servo", label: "Single Servo" },
            { value: "plc", label: "PLC Controlled" },
            { value: "stepper", label: "Stepper" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "positioning_accuracy",
          key: "positioning_accuracy",
          anchor: true,
          importance: "high",
          anchorPriority: 45,
          insight:
            "Sub-millimetre return-to-origin accuracy keeps every ply edge-aligned — cleaner cuts and less end waste.",
          label: "Positioning Accuracy",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "mm",
          required: false,
          description: "Repeatable positioning / zero-return accuracy.",
          ...tech,
          comparable: true,
          visualRenderType: "metric_block",
        },
        {
          id: "touchscreen",
          key: "touchscreen",
          label: "Touchscreen Control",
          order: 30,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Colour industrial touchscreen interface.",
          ...pub,
          visualRenderType: "boolean_feature",
        },
        {
          id: "interface_languages",
          key: "interface_languages",
          label: "Interface Languages",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "languages",
          required: false,
          description: "Number of on-screen interface languages (e.g. Chinese/English).",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "fabric_program_memory",
          key: "fabric_program_memory",
          label: "Fabric Program Memory",
          order: 50,
          fieldType: "unit_number",
          dataType: "number",
          unit: "profiles",
          required: false,
          description: "Named fabric profiles the machine can store and recall.",
          ...pub,
          comparable: true,
          visualRenderType: "spec_card",
        },
        {
          id: "speed_gears",
          key: "speed_gears",
          label: "Speed Gears",
          order: 60,
          fieldType: "unit_number",
          dataType: "number",
          unit: "gears",
          required: false,
          description: "Number of adjustable forward/reverse speed steps.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "operating_modes",
          key: "operating_modes",
          label: "Operating Modes",
          order: 70,
          fieldType: "unit_number",
          dataType: "number",
          unit: "modes",
          required: false,
          description: "Independent spreading programs run in sequence (Mode 1/2/3).",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "edge_alignment",
          key: "edge_alignment",
          label: "Edge Alignment",
          order: 80,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "How the fabric selvedge is kept straight during spreading.",
          options: [
            { value: "photosensor", label: "Automatic (Photosensor)" },
            { value: "mechanical", label: "Mechanical Guide" },
            { value: "manual", label: "Manual" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "tension_control",
          key: "tension_control",
          anchor: true,
          importance: "normal",
          anchorPriority: 55,
          insight:
            "Tension-free feeding stops knit and stretch fabric from relaxing after cutting — protecting size accuracy on elastic goods.",
          label: "Tension Control",
          order: 90,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Fabric tension management during spreading.",
          options: [
            { value: "tension_free", label: "Tension-Free" },
            { value: "auto", label: "Automatic" },
            { value: "manual", label: "Manual" },
          ],
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "cutting_device",
          key: "cutting_device",
          label: "Automatic End Cutter",
          order: 100,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Built-in automatic fabric cutter at end of each ply.",
          ...pub,
          visualRenderType: "boolean_feature",
        },
        {
          id: "auto_blade_sharpening",
          key: "auto_blade_sharpening",
          anchor: true,
          importance: "normal",
          anchorPriority: 65,
          label: "Automatic Blade Sharpening",
          order: 110,
          fieldType: "boolean",
          dataType: "boolean",
          required: false,
          description: "Cutter self-sharpens after a set number of cuts.",
          ...pub,
          visualRenderType: "boolean_feature",
        },
        {
          id: "connectivity",
          key: "connectivity",
          label: "Connectivity / Smart",
          order: 120,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Data and cutting-room-management integration options.",
          options: [
            { value: "wifi", label: "Wi-Fi" },
            { value: "usb", label: "USB Work Orders" },
            { value: "server", label: "Server / Network" },
            { value: "mes", label: "MES / ERP Integration" },
            { value: "production_tracking", label: "Production Tracking" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 4 — Electrical
    // ------------------------------------------------------------------
    {
      id: "electrical",
      title: "Electrical",
      order: 40,
      fields: [
        {
          id: "phase",
          key: "phase",
          label: "Power Phase",
          order: 10,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Electrical supply phase.",
          options: [
            { value: "single_phase", label: "Single Phase (1PH)" },
            { value: "three_phase", label: "Three Phase (3PH)" },
          ],
          ...pub,
          visualRenderType: "technical_badge",
        },
        {
          id: "voltage_options",
          key: "voltage_options",
          label: "Voltage",
          order: 20,
          fieldType: "select",
          dataType: "string",
          required: false,
          description: "Rated supply voltage.",
          options: [
            { value: "220v", label: "220 V" },
            { value: "230v", label: "230 V" },
            { value: "380v", label: "380 V" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
        {
          id: "frequency_hz",
          key: "frequency_hz",
          label: "Frequency",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "Hz",
          required: false,
          description: "Rated supply frequency.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "power_consumption_w",
          key: "power_consumption_w",
          label: "Power",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kW",
          required: false,
          description: "Rated power consumption.",
          ...pub,
          comparable: true,
          visualRenderType: "spec_card",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 5 — Equipment & Options
    // ------------------------------------------------------------------
    {
      id: "equipment-options",
      title: "Equipment & Options",
      order: 50,
      fields: [
        {
          id: "standard_equipment",
          key: "standard_equipment",
          label: "Standard Equipment",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Devices included as standard with the machine.",
          options: [
            { value: "cutting_device", label: "Cutting Device" },
            { value: "operator_platform", label: "Operator Platform" },
            { value: "folded_fabric_platform", label: "Folded-Fabric Platform" },
            { value: "edge_control", label: "Automatic Edge Control" },
            { value: "fabric_flatting_bar", label: "Fabric Flattening Bar" },
            { value: "run_out_sensor", label: "Fabric Run-Out Sensor" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
        {
          id: "optional_devices",
          key: "optional_devices",
          label: "Optional Devices",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Add-on devices available for this machine.",
          options: [
            { value: "anti_static", label: "Anti-Static Device" },
            { value: "manned_platform", label: "Riding / Manned Platform" },
            { value: "safety_sensor", label: "Safety Sensor Device" },
            { value: "tubular_device", label: "Tubular / Cylinder Device" },
            { value: "front_catcher", label: "Front Catcher" },
            { value: "rear_catcher", label: "Rear Catcher" },
            { value: "zigzag_device", label: "Zigzag Device" },
            { value: "auto_elevating", label: "Automatic Elevating Device" },
            { value: "photoelectric_flatting", label: "Photoelectric Flatting Device" },
            { value: "fabric_weighing", label: "Fabric Weighing System" },
            { value: "width_measurement", label: "Fabric Width Measurement" },
            { value: "reverse_rolling", label: "Reverse Rolling Roller" },
            { value: "anti_collision", label: "Photoelectric Anti-Collision" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 6 — Physical & Packing
    // ------------------------------------------------------------------
    {
      id: "physical",
      title: "Physical",
      order: 60,
      fields: [
        {
          id: "machine_weight_kg",
          key: "machine_weight_kg",
          label: "Machine Weight",
          order: 10,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net weight of the machine.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "machine_dimensions",
          key: "machine_dimensions",
          label: "Machine Dimensions (L×W×H)",
          order: 20,
          fieldType: "text",
          dataType: "string",
          required: false,
          description: "Overall machine dimensions in mm (L×W×H).",
          ...pub,
          visualRenderType: "packing_block",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 6b — Packing & Shipping (edited on the Logistics tab, not Specs)
    // Shipping-unit data (crate size / volume / shipping weight) for freight,
    // container loading, and customs. formTab:"logistics" routes this group to
    // the Logistics step in the product form; still stored in schema_specs.
    // ------------------------------------------------------------------
    {
      id: "packing-shipping",
      title: "Packing & Shipping",
      order: 65,
      formTab: "logistics",
      fields: [
        {
          id: "packing_dimensions",
          key: "packing_dimensions",
          label: "Packing Dimensions (L×W×H)",
          order: 10,
          fieldType: "text",
          dataType: "string",
          required: false,
          description: "Packed carton/crate dimensions in mm (L×W×H).",
          ...pub,
          visualRenderType: "packing_block",
        },
        {
          id: "cbm",
          key: "cbm",
          label: "CBM",
          order: 20,
          fieldType: "unit_number",
          dataType: "number",
          unit: "m³",
          required: false,
          description: "Packed volume in cubic metres.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "net_weight",
          key: "net_weight",
          label: "Net Weight",
          order: 30,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Net weight, packed.",
          ...pub,
          visualRenderType: "spec_card",
        },
        {
          id: "gross_weight",
          key: "gross_weight",
          label: "Gross Weight",
          order: 40,
          fieldType: "unit_number",
          dataType: "number",
          unit: "kg",
          required: false,
          description: "Gross shipping weight.",
          ...pub,
          visualRenderType: "spec_card",
        },
      ],
    },

    // ------------------------------------------------------------------
    // Group 7 — Safety & Compliance
    // ------------------------------------------------------------------
    {
      id: "safety-compliance",
      title: "Safety & Compliance",
      order: 70,
      fields: [
        {
          id: "safety_features",
          key: "safety_features",
          label: "Safety Features",
          order: 10,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Built-in operator- and machine-safety systems.",
          options: [
            { value: "emergency_stop", label: "Emergency Stop (Brake Lines)" },
            { value: "front_rear_photosensor", label: "Front & Rear Safety Photosensor" },
            { value: "anti_collision", label: "Anti-Collision" },
            { value: "run_out_sensor", label: "Fabric Run-Out Sensor" },
            { value: "auto_return_origin", label: "Automatic Return-to-Origin" },
          ],
          ...pub,
          visualRenderType: "icon_chip",
        },
        {
          id: "certifications",
          key: "certifications",
          label: "Certifications",
          order: 20,
          fieldType: "multi_select",
          dataType: "json",
          required: false,
          description: "Quality and compliance certifications.",
          options: [
            { value: "ce", label: "CE" },
            { value: "iso9000", label: "ISO 9000" },
            { value: "iso9001", label: "ISO 9001" },
          ],
          ...pub,
          filterVisible: true,
          visualRenderType: "technical_badge",
        },
      ],
    },
  ],
};
