import "server-only";

/* ---------------------------------------------------------------------------
   ai-agent/catalog-knowledge — the Koleex Catalog 2025 index (544 models),
   distilled from the owner's catalog sheet. Every machine here is a KOLEEX
   machine: no other manufacturer or brand may ever be named alongside
   these models. Garbled OCR taglines were dropped at build time — a null
   tagline means "describe from the category, don't invent copy".
   Source: Koleex Catalog 2025 (image-based PDF), pages 28-138.
   --------------------------------------------------------------------------- */

export interface CatalogEntry {
  /** Koleex model code (the product's identity). */
  model: string;
  /** Catalog series / machine family. */
  category: string;
  /** Clean marketing tagline where the OCR was trustworthy; null otherwise. */
  tagline: string | null;
  /** Page in the printed Koleex Catalog 2025. */
  page: number | null;
}

export const CATALOG_ENTRIES: CatalogEntry[] = [
  { model: "XF-2130", category: "Spreading Machine Series", tagline: null, page: 28 },
  { model: "XF-A10", category: "Spreading Machine Series", tagline: "Intelligent spreading machine", page: 28 },
  { model: "XF-A3T", category: "Spreading Machine Series", tagline: "Intelligent spreading machine", page: 28 },
  { model: "XF-A7", category: "Spreading Machine Series", tagline: "Intelligent spreading machine", page: 28 },
  { model: "XF-1800E-HZ", category: "Fabric Relaxing and Inspection Machines", tagline: "Heavy fabric relaxing machine", page: 29 },
  { model: "XF-1800E-HZ-LC", category: "Fabric Relaxing and Inspection Machines", tagline: "Heavy fabric relaxing machine", page: 29 },
  { model: "XF-2100E-ZS", category: "Fabric Relaxing and Inspection Machines", tagline: "Knit, woven fabric relaxing machine", page: 29 },
  { model: "XF-2100F-JS-ED", category: "Fabric Relaxing and Inspection Machines", tagline: "Automatic edge alignment fabric rolling machine", page: 29 },
  { model: "XF-2300E-ZS-ED", category: "Fabric Relaxing and Inspection Machines", tagline: "Automatic edge alignment fabric relaxing machine", page: 29 },
  { model: "XF-1700D", category: "Fabric Batching, Folding and Loading Machines", tagline: "Automatic batching machine", page: 30 },
  { model: "XF-2000D", category: "Fabric Batching, Folding and Loading Machines", tagline: "Automatic batching machine", page: 30 },
  { model: "XF-301A", category: "Fabric Batching, Folding and Loading Machines", tagline: "Woven automatic fabric loosening machine", page: 30 },
  { model: "XF-9000D", category: "Fabric Batching, Folding and Loading Machines", tagline: "High speed folding and stitching machine", page: 30 },
  { model: "XF-A06-1", category: "Fabric Batching, Folding and Loading Machines", tagline: null, page: 30 },
  { model: "XF-2100C-ED", category: "Fabric Loosening and Inspection Machines", tagline: "Automatic edge alignment fabric inspection and rolling machine", page: 31 },
  { model: "XF-2100C-ED-LC-W", category: "Fabric Loosening and Inspection Machines", tagline: "Automatic edge alignment fabric inspection and rolling machine", page: 31 },
  { model: "XF-2100CP-ED", category: "Fabric Loosening and Inspection Machines", tagline: "Digital multi- fabric inspection machine", page: 31 },
  { model: "XF-301", category: "Fabric Loosening and Inspection Machines", tagline: "Automatic fabric loosening machine (knit and woven fabric)", page: 31 },
  { model: "XF-301B", category: "Fabric Loosening and Inspection Machines", tagline: "Automatic fabric loosening machine (side to side)", page: 31 },
  { model: "XF-1800B-JS-ED", category: "Fabric Inspection Machines", tagline: "Automatic edge alignment heavy fabric inspection machine", page: 32 },
  { model: "XF-A03-6", category: "Fabric Inspection Machines", tagline: "Fabric inspection machine woven and knit", page: 32 },
  { model: "XF-AO3", category: "Fabric Inspection Machines", tagline: null, page: 32 },
  { model: "XF-4800", category: "Fabric Shrinking Machines", tagline: "Fabric shrinking machine", page: 33 },
  { model: "XF-4800-A", category: "Fabric Shrinking Machines", tagline: "Fabric shrinking machine", page: 33 },
  { model: "XF-6800", category: "Fabric Shrinking Machines", tagline: "Fabric shrinking machine", page: 33 },
  { model: "XF-8800", category: "Fabric Shrinking Machines", tagline: "Fabric shrinking machine", page: 33 },
  { model: "XC-2100AS", category: "Needle Detection and Fabric Inspection Machines", tagline: "Automatic fabric roll slitting machine", page: 34 },
  { model: "XC-2100BS", category: "Needle Detection and Fabric Inspection Machines", tagline: null, page: 34 },
  { model: "XF-12090", category: "Needle Detection and Fabric Inspection Machines", tagline: "Visual line drawing machine", page: 34 },
  { model: "XF-Q900LS/Q900LSS", category: "Fusing and Bonding Machines", tagline: "Single/double roller & press fusing machine", page: 35 },
  { model: "XC-988", category: "Straight Knife Cutting Machines", tagline: null, page: 37 },
  { model: "XC-988S", category: "Straight Knife Cutting Machines", tagline: "Computer Servo Cutting Machine", page: 37 },
  { model: "XC-9988", category: "Straight Knife Cutting Machines", tagline: "Auto-Sharpening Cutting Machine", page: 37 },
  { model: "XC-F9", category: "Straight Knife Cutting Machines", tagline: null, page: 37 },
  { model: "XC-F9881", category: "Straight Knife Cutting Machines", tagline: null, page: 37 },
  { model: "XC-P10", category: "Straight Knife Cutting Machines", tagline: "Computer Servo Cutting Machine", page: 37 },
  { model: "XC-P9", category: "Straight Knife Cutting Machines", tagline: null, page: 37 },
  { model: "XC-P9/F9/F9881/988", category: "Straight Knife Cutting Machines", tagline: null, page: 37 },
  { model: "XC-1-1", category: "Straight Knife Cutting Machines", tagline: null, page: 38 },
  { model: "XC-1-1A", category: "Straight Knife Cutting Machines", tagline: null, page: 38 },
  { model: "XC-A200", category: "Straight Knife Cutting Machines", tagline: "Electroheat Cutter", page: 38 },
  { model: "XCC1-1/1-1A", category: "Straight Knife Cutting Machines", tagline: null, page: 38 },
  { model: "XCC1-1B", category: "Straight Knife Cutting Machines", tagline: null, page: 38 },
  { model: "XC-110B", category: "Handheld Cutting Machines", tagline: null, page: 39 },
  { model: "XC-125", category: "Handheld Cutting Machines", tagline: null, page: 39 },
  { model: "XC-125/110/100/90", category: "Handheld Cutting Machines", tagline: "Round cutting machine", page: 39 },
  { model: "XC-125B", category: "Handheld Cutting Machines", tagline: null, page: 39 },
  { model: "XC-C2", category: "Handheld Cutting Machines", tagline: null, page: 39 },
  { model: "XC-P100/P110/P125", category: "Handheld Cutting Machines", tagline: "Servo round cutting machine", page: 39 },
  { model: "XC-P100B", category: "Handheld Cutting Machines", tagline: null, page: 39 },
  { model: "XC-P100S/P110S/P125S", category: "Handheld Cutting Machines", tagline: null, page: 39 },
  { model: "XC-2700DA-1/2", category: "Strip Cutting Machines", tagline: "High precision automatic strip cutting machine", page: 40 },
  { model: "XC-2700DA-3", category: "Strip Cutting Machines", tagline: "Dual servo automatic strip cutting machine", page: 40 },
  { model: "XC-2700DB", category: "Strip Cutting Machines", tagline: "High precision automatic strip cutting machine", page: 40 },
  { model: "XC-801A", category: "Cutting and Label Cutting Machines", tagline: null, page: 41 },
  { model: "XC-802A", category: "Cutting and Label Cutting Machines", tagline: null, page: 41 },
  { model: "XC-ATC-A2", category: "Cutting and Label Cutting Machines", tagline: "Double knives cylinder cloth cutting strip machine", page: 41 },
  { model: "XC-150HX", category: "Label and Tape Cutting Machines", tagline: "Auto-cutting machine (Multi-function bevel cutter)", page: 42 },
  { model: "XC-2500S", category: "Label and Tape Cutting Machines", tagline: "Over-seaming Rubber Band Machine", page: 42 },
  { model: "XC-2700S", category: "Label and Tape Cutting Machines", tagline: null, page: 42 },
  { model: "XC-988L/H", category: "Label and Tape Cutting Machines", tagline: null, page: 42 },
  { model: "XC-205A", category: "Cutting Tables and Manual Cutters", tagline: null, page: 43 },
  { model: "XC-205B", category: "Cutting Tables and Manual Cutters", tagline: "Wireless semi-auto end cutter", page: 43 },
  { model: "XC-206", category: "Cutting Tables and Manual Cutters", tagline: "Digital display manual end cutter", page: 43 },
  { model: "XC-DB-1", category: "Cutting Tables and Manual Cutters", tagline: "Manual end cutter", page: 43 },
  { model: "XC-DB-2", category: "Cutting Tables and Manual Cutters", tagline: "Digital display manual end cutter", page: 43 },
  { model: "XC-DB-2A", category: "Cutting Tables and Manual Cutters", tagline: "Manual end cutter", page: 43 },
  { model: "XC-2007L", category: "Automatic Cutting System", tagline: "CNC automatic cutting machine", page: 44 },
  { model: "XC-1325D/1630D", category: "Laser Cutting and Marking Machine Series", tagline: null, page: 45 },
  { model: "XC-16100/1680Q", category: "Laser Cutting and Marking Machine Series", tagline: null, page: 45 },
  { model: "XC-1610Z/1810Z", category: "Laser Cutting and Marking Machine Series", tagline: null, page: 45 },
  { model: "XC-B13S/B13-V/B11S", category: "Digital Cutting Machines", tagline: null, page: 46 },
  { model: "XC-B2S", category: "Digital Cutting Machines", tagline: "Intelligent cutting machine", page: 46 },
  { model: "XC-B3016S/B6616S/B160160S/B5516S", category: "Digital Cutting Machines", tagline: "Digital cutting machine", page: 46 },
  { model: "XSL-A104E", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 48 },
  { model: "XSL-Q246-33", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 48 },
  { model: "XSL-Q246L-33", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 48 },
  { model: "XSL-A144", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 49 },
  { model: "XSL-L7", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 49 },
  { model: "XSL-L9", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 49 },
  { model: "XSL-A191", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 50 },
  { model: "XSL-QI96MF", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 50 },
  { model: "XSL-Q184", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 51 },
  { model: "XSL-Q185", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 51 },
  { model: "XSL-5498", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 52 },
  { model: "XSL-A136MF", category: "Industrial Lockstitch Sewing Machines", tagline: null, page: 52 },
  { model: "XSL-5300-D3", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 53 },
  { model: "XSL-A100", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A101", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A104", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A105", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A120", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A124", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A140", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A180", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A190", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A201", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A210", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A220", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A221", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A225", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A2251", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A240", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A245", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A251", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A254", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A267", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-A286", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-AI25", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 54 },
  { model: "XSL-6150", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-8000A4", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: "Inteligentlockstitch sewing machine", page: 55 },
  { model: "XSL-8700", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-8700D", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-9900A4-360P", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-9900A4-560P", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-9900A4-850P", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-A134-800", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-B100", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-B101", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-B104", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-B105", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-B120", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-B124", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-B146ZS", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-B15", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-BI26MF", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-BI35CD", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-BT10", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-Q100", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-Q125", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSL-Q126MF", category: "Industrial Lockstitch Sewing Machines with Side Cutter", tagline: null, page: 55 },
  { model: "XSO-730S", category: "Overlock Sewing Machine Series", tagline: "Direct-drive overlock sewing machine", page: 56 },
  { model: "XSO-777A", category: "Overlock Sewing Machine Series", tagline: null, page: 56 },
  { model: "XSO-988LC-6T-324BUT/HTR", category: "Overlock Sewing Machine Series", tagline: "Three needle six thread towel overlock machine with rear", page: 56 },
  { model: "XSO-H6D", category: "Overlock Sewing Machine Series", tagline: null, page: 56 },
  { model: "XSO-988LC-3T-O4BCT", category: "Overlock Sewing Machine Series", tagline: "Stepper intelligent overlock sewing machine with thread", page: 57 },
  { model: "XSO-988LC-3T-O4BKT", category: "Overlock Sewing Machine Series", tagline: null, page: 57 },
  { model: "XSO-988LC-4T-24BCT", category: "Overlock Sewing Machine Series", tagline: "Stepper intelligent overlock sewing machine with thread", page: 57 },
  { model: "XSO-988LC-4T-24BKT", category: "Overlock Sewing Machine Series", tagline: null, page: 57 },
  { model: "XSO-988LC-5T-35/55/S6BCT", category: "Overlock Sewing Machine Series", tagline: "Stepper intelligent overlock sewing machine with thread", page: 57 },
  { model: "XSO-H8T-3H-04BK", category: "Overlock Sewing Machine Series", tagline: null, page: 57 },
  { model: "XSO-H8T-4H-24B/UT", category: "Overlock Sewing Machine Series", tagline: null, page: 57 },
  { model: "XSO-H8T-4H-24BK", category: "Overlock Sewing Machine Series", tagline: "Intelligent overstitch overlock sewing machine(Touch screen)", page: 57 },
  { model: "XSO-H8T-5H-55/S6UT", category: "Overlock Sewing Machine Series", tagline: null, page: 57 },
  { model: "XSO-H8T-6H-324/325UT", category: "Overlock Sewing Machine Series", tagline: null, page: 57 },
  { model: "XSO-5100D-EXT", category: "Overlock Sewing Machine Series", tagline: null, page: 58 },
  { model: "XSO-888ST-3T-O4UT", category: "Overlock Sewing Machine Series", tagline: null, page: 58 },
  { model: "XSO-888ST-4T-24UT", category: "Overlock Sewing Machine Series", tagline: null, page: 58 },
  { model: "XSO-A5-4D", category: "Overlock Sewing Machine Series", tagline: null, page: 58 },
  { model: "XSO-A6-4DA", category: "Overlock Sewing Machine Series", tagline: "Intelligent overlock sewing machine", page: 58 },
  { model: "XSO-988LQ-3T-04BK", category: "Overlock Sewing Machine Series", tagline: null, page: 59 },
  { model: "XSO-988LQ-3T-15PZ", category: "Overlock Sewing Machine Series", tagline: null, page: 59 },
  { model: "XSO-988LQ-4T-24BK", category: "Overlock Sewing Machine Series", tagline: null, page: 59 },
  { model: "XSO-988LQ-4T-24UT", category: "Overlock Sewing Machine Series", tagline: "Intelligent overlock sewing machine", page: 59 },
  { model: "XSO-988LQ-5T-35/55/S6UT", category: "Overlock Sewing Machine Series", tagline: null, page: 59 },
  { model: "XSO-988LQ-6T-324/325UT", category: "Overlock Sewing Machine Series", tagline: "Intelligent overlock sewing machine", page: 59 },
  { model: "XSO-988LQ-WR-LC-3", category: "Overlock Sewing Machine Series", tagline: null, page: 59 },
  { model: "XSO-C8-4DF/UT", category: "Overlock Sewing Machine Series", tagline: "Stepper intelligent overlock sewing machine with back-latching", page: 60 },
  { model: "XSO-C8-4UT", category: "Overlock Sewing Machine Series", tagline: "Direct-drive overlock sewing machine(with elastic cord)", page: 60 },
  { model: "XSO-C9A-4UT", category: "Overlock Sewing Machine Series", tagline: "Stepper intelligent overlock sewing machine", page: 60 },
  { model: "XSO-C9S-4UT", category: "Overlock Sewing Machine Series", tagline: "Stepper intelligent overlock sewing machine", page: 60 },
  { model: "XSO-888ST-4T-24EUT", category: "Overlock Sewing Machine Series", tagline: "Intelligent round neck overlock sewing machine", page: 61 },
  { model: "XSO-H8ST-4T-24VT/SL", category: "Overlock Sewing Machine Series", tagline: null, page: 61 },
  { model: "XSO-X5100ST-4-24VT/ST", category: "Overlock Sewing Machine Series", tagline: "Direct-drive overlock sewing machine", page: 61 },
  { model: "XSO-X5100ST-4T-24VT/CL", category: "Overlock Sewing Machine Series", tagline: null, page: 61 },
  { model: "XSO-700A", category: "Overlock Sewing Machine Series", tagline: null, page: 62 },
  { model: "XSO-851A", category: "Overlock Sewing Machine Series", tagline: null, page: 62 },
  { model: "XSO-980D-4", category: "Overlock Sewing Machine Series", tagline: null, page: 62 },
  { model: "XSO-985A", category: "Overlock Sewing Machine Series", tagline: null, page: 62 },
  { model: "XSO-986ES", category: "Overlock Sewing Machine Series", tagline: null, page: 62 },
  { model: "XSO-986ES-3C", category: "Overlock Sewing Machine Series", tagline: null, page: 62 },
  { model: "XSO-C8-4D", category: "Overlock Sewing Machine Series", tagline: null, page: 62 },
  { model: "XSO-RX5816-UT", category: "Overlock Sewing Machine Series", tagline: null, page: 62 },
  { model: "XSO-RXS817-UT", category: "Overlock Sewing Machine Series", tagline: null, page: 62 },
  { model: "XSO-RXT5818-SUT", category: "Overlock Sewing Machine Series", tagline: null, page: 62 },
  { model: "XSO-5200A", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-5200A-EXT", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-5200D-EXT", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-5200LA", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-5200LD-EXT", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-710D", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-712D", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-713D", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-740D", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-757", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-760D", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-770D", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-987S", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-988D-BK", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-999A", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-999LA", category: "Overlock Sewing Machine Series", tagline: null, page: 63 },
  { model: "XSO-20-2", category: "Shell Stitch and Middle Speed Overlock Machines", tagline: null, page: 64 },
  { model: "XSO-20-6", category: "Shell Stitch and Middle Speed Overlock Machines", tagline: null, page: 64 },
  { model: "XSO-2501K", category: "Shell Stitch and Middle Speed Overlock Machines", tagline: null, page: 64 },
  { model: "XSO-2502", category: "Shell Stitch and Middle Speed Overlock Machines", tagline: null, page: 64 },
  { model: "XSO-2502K", category: "Shell Stitch and Middle Speed Overlock Machines", tagline: null, page: 64 },
  { model: "XSO-2502W", category: "Shell Stitch and Middle Speed Overlock Machines", tagline: null, page: 64 },
  { model: "XSO-2503W", category: "Shell Stitch and Middle Speed Overlock Machines", tagline: null, page: 64 },
  { model: "XSO-302/306", category: "Shell Stitch and Middle Speed Overlock Machines", tagline: null, page: 64 },
  { model: "XSO-GN1-1", category: "Shell Stitch and Middle Speed Overlock Machines", tagline: null, page: 64 },
  { model: "XSO-GN1-113D", category: "Shell Stitch and Middle Speed Overlock Machines", tagline: null, page: 64 },
  { model: "XSO-GN1-6D", category: "Shell Stitch and Middle Speed Overlock Machines", tagline: null, page: 64 },
  { model: "XSI-7720A-35V", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSL-7720A-35W", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSL-7720S-01", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSL-7720S-01V", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSL-7720S-O1W", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSL-7787A-", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSL-7787A-33WP", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSL-7787A-35W", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSL-7787S-01", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSL-7787S-01V", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSL-7787S-01W", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSO-7787A-35W", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSO-7787S-01V", category: "Industrial Interlock Sewing Machines", tagline: null, page: 65 },
  { model: "XSI-350ST-01VQ", category: "Industrial Interlock Sewing Machines", tagline: null, page: 66 },
  { model: "XSL-150A-01V", category: "Industrial Interlock Sewing Machines", tagline: null, page: 66 },
  { model: "XSL-150A-01W", category: "Industrial Interlock Sewing Machines", tagline: null, page: 66 },
  { model: "XSL-350D-01", category: "Industrial Interlock Sewing Machines", tagline: null, page: 66 },
  { model: "XSL-350D-05", category: "Industrial Interlock Sewing Machines", tagline: null, page: 66 },
  { model: "XSL-350D-08", category: "Industrial Interlock Sewing Machines", tagline: null, page: 66 },
  { model: "XSL-350S-01W", category: "Industrial Interlock Sewing Machines", tagline: null, page: 66 },
  { model: "XSL-350S-O1VP", category: "Industrial Interlock Sewing Machines", tagline: null, page: 66 },
  { model: "XSL-IS0A-O1P", category: "Industrial Interlock Sewing Machines", tagline: null, page: 66 },
  { model: "XSL-W500-07", category: "Industrial Interlock Sewing Machines", tagline: null, page: 66 },
  { model: "XSI-360S-35W", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 67 },
  { model: "XSL-160A-01W", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 67 },
  { model: "XSL-360ST-O1W", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 67 },
  { model: "XSL-T6OA-O1W", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 67 },
  { model: "XSL-W600-02", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 67 },
  { model: "XSL-W600A-35V", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 67 },
  { model: "XSL-WE600D-01", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 67 },
  { model: "XSL-WG600A-33VP", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 67 },
  { model: "XSI-2500LS", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSI-2500S", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSI-7640S-SQ-460HQ", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSL-2500LS", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSL-2500LS-TTH164", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSL-2500LSW-156", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSL-2500LSW-464", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSL-2500S-TT164", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSL-2500SW-464", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSL-7640A-SQSC-460", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSL-7640D-DQ-4520", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSL-7640S-SQ-4600", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSL-7640S-SQ-460HQ", category: "Industrial Cylinder Bed Interlock Sewing Machines", tagline: null, page: 68 },
  { model: "XSI-008-13032P-UT", category: "Industrial Multi-Needle Machines", tagline: "12-Needle inserting multi-needie machine", page: 69 },
  { model: "XSI-008-33048P", category: "Industrial Multi-Needle Machines", tagline: null, page: 69 },
  { model: "XSI-008-33048P/VPQ/VSM", category: "Industrial Multi-Needle Machines", tagline: null, page: 69 },
  { model: "XSI-008-65048P-SD/VPQ", category: "Industrial Multi-Needle Machines", tagline: null, page: 69 },
  { model: "XSI-008-04064P-VWL-D", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-008-08064P-VPL-LD", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-008-12064P-UT", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-008-12064P/DA", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-008-13032P-DTK/VPL", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-1404PMD", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-1404PSF", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-1406PL", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-1408PL", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-1412P", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-1425P", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-1433P", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-17048P-VSQ", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-33048P-VPQ", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-33048P-VSQ-VSM", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-4400-12064P-D", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-4400-12064P-UT", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSI-4400-12064P-VPQ-D", category: "Industrial Multi-Needle Machines", tagline: null, page: 70 },
  { model: "XSL-842/872", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-8422A4/8722A4", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-845/875", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-9420/9720", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-9421D/9721D-560", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-9422A-CK", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-9422A/9722A", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-9422A/9722A-560", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-942D/972D", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-9450/9750", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-9452A/9752A", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-9452A3/9752A3/9452A3/9752A3", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-945D/975D", category: "Double Needle Sewing Machines", tagline: null, page: 71 },
  { model: "XSL-0056-1D", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-0056-2D", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-0056-3D", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-3800LD", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-3810", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-3810D", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-3810DP", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-3820", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-3820D", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-3820D-DZ", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-3820DP", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-3830", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-3830D", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-3830D-UT", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-4830D", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-4930S", category: "Double Needle Sewing Machines", tagline: null, page: 72 },
  { model: "XSL-0317S", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 73 },
  { model: "XSL-0336S", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 73 },
  { model: "XSL-0385-D4", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 73 },
  { model: "XSL-0303A4-850", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 74 },
  { model: "XSL-0303D", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 74 },
  { model: "XSL-0303E3", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 74 },
  { model: "XSL-0313A3-56", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 74 },
  { model: "XSL-0313E3", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 74 },
  { model: "XSL-0313ES3", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 74 },
  { model: "XSL-0352A4", category: "Top and Bottom Feed Sewing Machines", tagline: "Intelligent side cutter top and bottom", page: 74 },
  { model: "XSL-0352E", category: "Top and Bottom Feed Sewing Machines", tagline: "Stepper intelligent side cutter top", page: 74 },
  { model: "XSL-202", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 74 },
  { model: "XSL-202A3", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 74 },
  { model: "XSL-1341", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 75 },
  { model: "XSL-1510D", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 75 },
  { model: "XSL-1510D-AE", category: "Top and Bottom Feed Sewing Machines", tagline: null, page: 75 },
  { model: "XSL-1510DL-18-7", category: "Compound Feed Sewing Machines", tagline: null, page: 76 },
  { model: "XSL-1510DL-25-7", category: "Compound Feed Sewing Machines", tagline: null, page: 76 },
  { model: "XSL-20518", category: "Compound Feed Sewing Machines", tagline: null, page: 76 },
  { model: "XSL-4400/44200W", category: "Compound Feed Sewing Machines", tagline: null, page: 76 },
  { model: "XSL-4400/4420A", category: "Compound Feed Sewing Machines", tagline: null, page: 76 },
  { model: "XSL-4420-640", category: "Compound Feed Sewing Machines", tagline: null, page: 76 },
  { model: "XSL-A121", category: "Compound Feed Sewing Machines", tagline: null, page: 76 },
  { model: "XSL-C4420-L85", category: "Compound Feed Sewing Machines", tagline: null, page: 76 },
  { model: "XSU-44T0", category: "Compound Feed Sewing Machines", tagline: null, page: 76 },
  { model: "XSS-1377D", category: "Buttonholing Sewing Machine Series", tagline: null, page: 77 },
  { model: "XSS-9820", category: "Buttonholing Sewing Machine Series", tagline: null, page: 77 },
  { model: "XSS-17908F", category: "Buttonholing Sewing Machine Series", tagline: null, page: 78 },
  { model: "XSS-1790B", category: "Buttonholing Sewing Machine Series", tagline: "Stepper intelligent button holing sewing machine", page: 78 },
  { model: "XSS-430D-55", category: "Buttonholing Sewing Machine Series", tagline: "Small range pattern machine(with medium pressure foot)", page: 79 },
  { model: "XSS-430D-96", category: "Buttonholing Sewing Machine Series", tagline: "Small range pattern machine(with medium pressure foot)", page: 79 },
  { model: "XSS-430D-MY", category: "Buttonholing Sewing Machine Series", tagline: "Intelligent automatic punching cap and eye machine", page: 79 },
  { model: "XSS-430H", category: "Buttonholing Sewing Machine Series", tagline: "Direct-drive electronic bartacking sewing machine", page: 79 },
  { model: "XSS-436D", category: "Buttonholing Sewing Machine Series", tagline: "Automatic fold the ribbon machine", page: 79 },
  { model: "XSS-438D", category: "Buttonholing Sewing Machine Series", tagline: "Automatic fold the ribbon machine", page: 79 },
  { model: "XSS-438D-ZM", category: "Buttonholing Sewing Machine Series", tagline: "Direct drive high speed computer button sewing machine", page: 79 },
  { model: "XSS-1900A-KD", category: "Bartacking Sewing Machines", tagline: "Cushion hole machine", page: 80 },
  { model: "XSS-1903A", category: "Bartacking Sewing Machines", tagline: null, page: 80 },
  { model: "XSS-1906A", category: "Bartacking Sewing Machines", tagline: null, page: 80 },
  { model: "XSS-1950", category: "Bartacking Sewing Machines", tagline: null, page: 80 },
  { model: "XSS-1950/1952", category: "Bartacking Sewing Machines", tagline: null, page: 80 },
  { model: "XSS-1956A", category: "Bartacking Sewing Machines", tagline: null, page: 80 },
  { model: "XSS-430A", category: "Bartacking Sewing Machines", tagline: null, page: 80 },
  { model: "XSS-437D", category: "Bartacking Sewing Machines", tagline: "Cushion hole machine", page: 80 },
  { model: "XSS-988D", category: "Button Feeder Machines", tagline: "Motor type button machine", page: 81 },
  { model: "XSS-988Q", category: "Button Feeder Machines", tagline: "Pneumatic type button machine", page: 81 },
  { model: "XSS-988R", category: "Button Feeder Machines", tagline: "All-letter recognition button machine", page: 81 },
  { model: "XSS-1261", category: "Feed-Off-The-Arm Sewing Machines", tagline: null, page: 82 },
  { model: "XSS-927D-PL", category: "Feed-Off-The-Arm Sewing Machines", tagline: null, page: 82 },
  { model: "XSS-9288L-MPF/CV-T", category: "Feed-Off-The-Arm Sewing Machines", tagline: null, page: 82 },
  { model: "XSS-928D-2PL", category: "Feed-Off-The-Arm Sewing Machines", tagline: null, page: 82 },
  { model: "XSS-928D-PL", category: "Feed-Off-The-Arm Sewing Machines", tagline: null, page: 82 },
  { model: "XSS-928D-PS", category: "Feed-Off-The-Arm Sewing Machines", tagline: null, page: 82 },
  { model: "XSS-928PF/CV", category: "Feed-Off-The-Arm Sewing Machines", tagline: null, page: 82 },
  { model: "XSS-9588-PF-CV", category: "Feed-Off-The-Arm Sewing Machines", tagline: null, page: 82 },
  { model: "XSS-100-2W", category: "Blind Stitch Sewing Machine Series", tagline: "sewing machine", page: 83 },
  { model: "XSS-100-6", category: "Blind Stitch Sewing Machine Series", tagline: "Automatic scarf sewing machine", page: 83 },
  { model: "XSS-101-1-3D", category: "Blind Stitch Sewing Machine Series", tagline: null, page: 83 },
  { model: "XSS-101-1D", category: "Blind Stitch Sewing Machine Series", tagline: null, page: 83 },
  { model: "XSS-101D", category: "Blind Stitch Sewing Machine Series", tagline: null, page: 83 },
  { model: "XSS-170-22D", category: "Blind Stitch Sewing Machine Series", tagline: "Automatic cloth receiving sewing machine", page: 83 },
  { model: "XSS-310D", category: "Blind Stitch Sewing Machine Series", tagline: "Automatic cloth receiving sewing machine", page: 83 },
  { model: "XSS-500", category: "Blind Stitch Sewing Machine Series", tagline: null, page: 83 },
  { model: "XSS-805R", category: "Blind Stitch Sewing Machine Series", tagline: null, page: 83 },
  { model: "XSS-861D", category: "Blind Stitch Sewing Machine Series", tagline: null, page: 83 },
  { model: "XSS-1530", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-1530D", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-20U23/33", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-20U43/53", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-20U457", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-20U457D", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-20U63", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-20U73/83", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-20U73D", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-20U93", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-20U93D", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-2530", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-2530D", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 84 },
  { model: "XSS-1588A", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-1588AW", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-1688A", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-1996A", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-2150H", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-2153BL30", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-2156", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-2284", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-2284D", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-2290-SR-7/P", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-2312D", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-2972", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 85 },
  { model: "XSS-1010XZ", category: "Industrial Zigzag Sewing Machines", tagline: "Intelligent cylinder arm pattern machine", page: 86 },
  { model: "XSS-2210-CH", category: "Industrial Zigzag Sewing Machines", tagline: "Intelligent pattern sewing machine", page: 86 },
  { model: "XSS-311G", category: "Industrial Zigzag Sewing Machines", tagline: "Intelligent pattern sewing machine", page: 86 },
  { model: "XSS-6040/3320/2210/1310", category: "Industrial Zigzag Sewing Machines", tagline: "Intelligent pattern sewing machine", page: 86 },
  { model: "XSS-360A-1300-980DSH", category: "Industrial Zigzag Sewing Machines", tagline: "360 degree rotating fully automatic template machine", page: 87 },
  { model: "XSS-880DS-8050", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 87 },
  { model: "XSS-880DS-8050JG", category: "Industrial Zigzag Sewing Machines", tagline: null, page: 87 },
  { model: "XA-6889K", category: "Automatic Pocket and Laser Sewing Units", tagline: "Intelligent lockstitch sewing machine", page: 89 },
  { model: "XSS-705", category: "Automatic Pocket and Laser Sewing Units", tagline: null, page: 89 },
  { model: "XSS-796", category: "Automatic Pocket and Laser Sewing Units", tagline: null, page: 89 },
  { model: "XA-858K-DK", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic pocket mouth curing machine (chain stitch)", page: 90 },
  { model: "XA-8750-DK", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic pocket mouth curling machine (lock stitch)", page: 90 },
  { model: "XA-DH2210", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic pocket decorative machine", page: 91 },
  { model: "XA-JD2303", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic pocket hemming machine(chainstitch)", page: 91 },
  { model: "XA-JD8420", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic pocket hemming machine(chainstitch)", page: 91 },
  { model: "XSS-J08420", category: "Automatic Pocket and Laser Sewing Units", tagline: null, page: 91 },
  { model: "XA-310", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic bottom hemming machine", page: 92 },
  { model: "XA-BT401-360", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic hemming machine", page: 92 },
  { model: "XA-ZT202", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic double-needle pillowcase hemming machine", page: 92 },
  { model: "XA-ZT202-H", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic double-needle pillowcase hemming machine", page: 92 },
  { model: "XA-CL102", category: "Automatic Pocket and Laser Sewing Units", tagline: "Fully automatic fitted sheet hemming machine", page: 93 },
  { model: "XA-FB402", category: "Automatic Pocket and Laser Sewing Units", tagline: "Fully automatic four-side hemming machine", page: 93 },
  { model: "XA-KS401", category: "Automatic Pocket and Laser Sewing Units", tagline: "Fully automatic four-side hemming machine", page: 93 },
  { model: "XA-KZ101", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic single-side hemming machine", page: 93 },
  { model: "XA-346", category: "Automatic Pocket and Laser Sewing Units", tagline: "Computer automatic hemming machine", page: 94 },
  { model: "XA-726", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic sleeve placket sewing machine (double)", page: 94 },
  { model: "XA-1105", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic waistband machine", page: 95 },
  { model: "XA-254", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic double-needle belt loop attaching machine", page: 95 },
  { model: "XA-CS232", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic windows screen curtain sewing machine", page: 96 },
  { model: "XA-EXT5100-4UT/SYL", category: "Automatic Pocket and Laser Sewing Units", tagline: null, page: 96 },
  { model: "XA-PB101", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic cloth receiving sewing machine", page: 96 },
  { model: "XA-TW111", category: "Automatic Pocket and Laser Sewing Units", tagline: null, page: 96 },
  { model: "XA-FG212", category: "Automatic Pocket and Laser Sewing Units", tagline: "Double-needle reflective tape sewing machine", page: 97 },
  { model: "XA-GL102", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic glove sewing machine", page: 97 },
  { model: "XA-TT111-X", category: "Automatic Pocket and Laser Sewing Units", tagline: "Non-woven hood elastic attaching machine", page: 97 },
  { model: "XA-XK101-SF", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic cuff overlock machine", page: 97 },
  { model: "XA-CD202", category: "Automatic Pocket and Laser Sewing Units", tagline: null, page: 98 },
  { model: "XA-FG204", category: "Automatic Pocket and Laser Sewing Units", tagline: "Automatic reflective tape overlock sewing machine", page: 98 },
  { model: "XA-APB/988-1903", category: "Automatic Pocket and Laser Sewing Units", tagline: "Electronic button sewing machine (automatic feeding)", page: 99 },
  { model: "XA-APY/1790", category: "Automatic Pocket and Laser Sewing Units", tagline: "Electronic flat buttonhole machine (automatic feeding)", page: 99 },
  { model: "XA-008-13032P-VPLSDC", category: "Automatic Pocket and Laser Sewing Units", tagline: null, page: 100 },
  { model: "XA-008-13032P-VPLSDK", category: "Automatic Pocket and Laser Sewing Units", tagline: "Fully automatic multi-needle tape attaching machine", page: 100 },
  { model: "XA-988A-4-FOUR", category: "Automatic Pocket and Laser Sewing Units", tagline: "Fully automatic four sided sewing edging machine", page: 100 },
  { model: "XA-2000-603", category: "Automatic Garment Sewing Units", tagline: "Fully automatic T-shirt placket machine", page: 101 },
  { model: "XA-899-2SD", category: "Automatic Garment Sewing Units", tagline: "Fully automatic multi-needle 2-in-1 folding machine", page: 101 },
  { model: "XA-3000-1400", category: "Automatic Garment Sewing Units", tagline: "Automatic pintuck sewing machine", page: 102 },
  { model: "XA-4800-787-600UT", category: "Automatic Garment Sewing Units", tagline: "Automatic single piece hemming machine", page: 102 },
  { model: "XA-K12", category: "Automatic Garment Sewing Units", tagline: null, page: 104 },
  { model: "XSE-591/592", category: "Special Industrial Sewing Machines", tagline: "Direct drive roller sewing machine", page: 106 },
  { model: "XSE-791", category: "Special Industrial Sewing Machines", tagline: null, page: 106 },
  { model: "XSE-9910", category: "Special Industrial Sewing Machines", tagline: null, page: 106 },
  { model: "XSE-9910D", category: "Special Industrial Sewing Machines", tagline: null, page: 106 },
  { model: "XSE-24698-1L", category: "Special Industrial Sewing Machines", tagline: "Super post bed compound feed sewing machine", page: 107 },
  { model: "XSE-2628LG", category: "Special Industrial Sewing Machines", tagline: null, page: 107 },
  { model: "XSE-810", category: "Special Industrial Sewing Machines", tagline: "Round body post bed sewing machine", page: 107 },
  { model: "XSE-8750", category: "Special Industrial Sewing Machines", tagline: null, page: 107 },
  { model: "XSE-168", category: "Special Industrial Sewing Machines", tagline: "Double thread side seam sewing machine", page: 108 },
  { model: "XSE-168H", category: "Special Industrial Sewing Machines", tagline: "Double needle/double shuttle side seam sewing machine", page: 108 },
  { model: "XSE-204-102", category: "Special Industrial Sewing Machines", tagline: "Double needle sewing machine", page: 110 },
  { model: "XSE-243", category: "Special Industrial Sewing Machines", tagline: null, page: 110 },
  { model: "XSE-6369-180L", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-6369-180R", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-6369-2/320", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-6369-2/420", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-6369-320R", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-6369/420", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-6591", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-7591", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-8362-703-250", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-8365-550/250", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-8365-703/250", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-8365-703F-457", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-8365D", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-8365D-18", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-8365S-330R", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-8591-360", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-8592", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSE-9591", category: "Post Bed Sewing Machines", tagline: null, page: 111 },
  { model: "XSO-AK-3700F", category: "Bag Closing Machines", tagline: null, page: 112 },
  { model: "XSS-26-1A", category: "Bag Closing Machines", tagline: null, page: 112 },
  { model: "XSS-35-20", category: "Bag Closing Machines", tagline: null, page: 112 },
  { model: "XSS-35-2CF", category: "Bag Closing Machines", tagline: null, page: 112 },
  { model: "XSS-35-7", category: "Bag Closing Machines", tagline: null, page: 112 },
  { model: "XSS-35-8A", category: "Bag Closing Machines", tagline: null, page: 112 },
  { model: "XSE-1204", category: "Bag Closing Machines", tagline: "4 Head 12 Needles embroidery machine", page: 115 },
  { model: "XSE-1206", category: "Bag Closing Machines", tagline: "6 Head 12 Needles embroidery machine", page: 115 },
  { model: "XSE-1208", category: "Bag Closing Machines", tagline: "8 Head 12 Needles embroidery machine", page: 115 },
  { model: "XP-25100A/25100-WD", category: "Heat Press Machine Series", tagline: "Webbing manual heat transfer printing machine", page: 117 },
  { model: "XP-3540", category: "Heat Press Machine Series", tagline: null, page: 118 },
  { model: "XP-3560", category: "Heat Press Machine Series", tagline: "Hot and Cold Dual-Mode Flat Press Machine", page: 118 },
  { model: "XP-R200", category: "Heat Press Machine Series", tagline: null, page: 118 },
  { model: "XP-4040/4050/4060-D4-Y", category: "Heat Press Machine Series", tagline: "Full automatic hydraulic four-station heat press machine", page: 119 },
  { model: "XP-6040/6080-TD2-ZQ", category: "Heat Press Machine Series", tagline: "Heat press machine up-sliding pneumatic double-station steam", page: 119 },
  { model: "XP-80100/10120/120150-D2", category: "Heat Press Machine Series", tagline: "Pneumatic large format double-station machine", page: 119 },
  { model: "XSU-10006", category: "Ironing and Finishing Equipment", tagline: null, page: 123 },
  { model: "XSU-100M", category: "Ironing and Finishing Equipment", tagline: null, page: 123 },
  { model: "XSU-200M", category: "Ironing and Finishing Equipment", tagline: null, page: 123 },
  { model: "XSU-80M", category: "Ironing and Finishing Equipment", tagline: null, page: 123 },
  { model: "XPL-1", category: "Ironing and Finishing Equipment", tagline: null, page: 127 },
  { model: "XPS-1", category: "Ironing and Finishing Equipment", tagline: null, page: 127 },
  { model: "XPS-2", category: "Ironing and Finishing Equipment", tagline: null, page: 127 },
  { model: "XSH-1212", category: "Household Sewing Machines", tagline: null, page: 130 },
  { model: "XSH-201", category: "Household Sewing Machines", tagline: null, page: 130 },
  { model: "XSH-2100AT", category: "Household Sewing Machines", tagline: "Domestic lockstitch sewing machine", page: 130 },
  { model: "XSH-307", category: "Household Sewing Machines", tagline: null, page: 130 },
  { model: "XSH-510", category: "Household Sewing Machines", tagline: null, page: 130 },
  { model: "XSH-588", category: "Household Sewing Machines", tagline: null, page: 130 },
  { model: "XSH-811", category: "Household Sewing Machines", tagline: "Domestic lockstitch sewing machine", page: 130 },
  { model: "XSH-974", category: "Household Sewing Machines", tagline: null, page: 130 },
  { model: "XSH-E300", category: "Household Sewing Machines", tagline: null, page: 130 },
  { model: "XSH-E310", category: "Household Sewing Machines", tagline: null, page: 130 },
  { model: "XSH-E320", category: "Household Sewing Machines", tagline: null, page: 130 },
  { model: "XSH-E320A", category: "Household Sewing Machines", tagline: null, page: 130 },
  { model: "XSH-E350", category: "Household Sewing Machines", tagline: null, page: 130 },
  { model: "XSH-320", category: "Household Sewing Machines", tagline: null, page: 131 },
  { model: "XSH-330", category: "Household Sewing Machines", tagline: "Domestic overlock sewing machine", page: 131 },
  { model: "XSH-434", category: "Household Sewing Machines", tagline: null, page: 131 },
  { model: "XSH-505", category: "Household Sewing Machines", tagline: null, page: 131 },
  { model: "XSH-515", category: "Household Sewing Machines", tagline: null, page: 131 },
  { model: "XSH-525", category: "Household Sewing Machines", tagline: null, page: 131 },
  { model: "XSH-703", category: "Household Sewing Machines", tagline: null, page: 131 },
  { model: "XA-550L", category: "Industrial Sewing Machine Motors and Lights", tagline: null, page: 133 },
  { model: "XA-550S", category: "Industrial Sewing Machine Motors and Lights", tagline: null, page: 133 },
  { model: "XA-700D", category: "Industrial Sewing Machine Motors and Lights", tagline: null, page: 133 },
  { model: "XA-8700-3", category: "Industrial Sewing Machine Motors and Lights", tagline: null, page: 133 },
  { model: "XA-8700-4", category: "Industrial Sewing Machine Motors and Lights", tagline: null, page: 133 },
  { model: "XA-DOL-13H", category: "Industrial Sewing Machine Motors and Lights", tagline: null, page: 133 },
  { model: "XR-150", category: "Thread Distribution Machines", tagline: null, page: 135 },
  { model: "XR-199", category: "Thread Distribution Machines", tagline: null, page: 135 },
  { model: "XR-200", category: "Thread Distribution Machines", tagline: null, page: 135 },
  { model: "XR-201", category: "Thread Distribution Machines", tagline: null, page: 135 },
  { model: "XR-300", category: "Thread Distribution Machines", tagline: "Band tape ruler", page: 135 },
  { model: "XR-301", category: "Thread Distribution Machines", tagline: null, page: 135 },
  { model: "XR-303", category: "Thread Distribution Machines", tagline: "Band tape ruler", page: 135 },
  { model: "XA-1688-1", category: "Thread Stand Series", tagline: null, page: 136 },
  { model: "XA-1788-1", category: "Thread Stand Series", tagline: null, page: 136 },
  { model: "XA-4824", category: "Thread Stand Series", tagline: null, page: 136 },
  { model: "XA-500D", category: "Thread Stand Series", tagline: null, page: 136 },
  { model: "XA-XJ-500-2", category: "Thread Stand Series", tagline: null, page: 136 },
  { model: "XA-XJ-500-58", category: "Thread Stand Series", tagline: null, page: 136 },
  { model: "XA-XJ-500-5A", category: "Thread Stand Series", tagline: null, page: 136 },
  { model: "XA-XJ-F2AA", category: "Thread Stand Series", tagline: null, page: 136 },
  { model: "XA-XJ-F3AA", category: "Thread Stand Series", tagline: null, page: 136 },
  { model: "XSU-0.36", category: "Thread Stand Series", tagline: null, page: 137 },
  { model: "XSU-100B", category: "Thread Stand Series", tagline: null, page: 137 },
  { model: "XSU-1200H-24", category: "Thread Stand Series", tagline: null, page: 137 },
  { model: "XSU-20", category: "Thread Stand Series", tagline: null, page: 137 },
  { model: "XSU-20Y", category: "Thread Stand Series", tagline: null, page: 137 },
  { model: "XSU-50", category: "Thread Stand Series", tagline: null, page: 137 },
  { model: "XSU-550H-65", category: "Thread Stand Series", tagline: null, page: 137 },
  { model: "XSU-550H-9L", category: "Thread Stand Series", tagline: null, page: 137 },
  { model: "XSU-5S50H-15L", category: "Thread Stand Series", tagline: null, page: 137 },
  { model: "XA-4DF", category: "Pneumatic Lint Collector Series", tagline: null, page: 138 },
  { model: "XA-6D", category: "Pneumatic Lint Collector Series", tagline: null, page: 138 },
  { model: "XA-6DL", category: "Pneumatic Lint Collector Series", tagline: null, page: 138 },
  { model: "XA-TFU16-3UT", category: "Pneumatic Lint Collector Series", tagline: null, page: 138 },
  { model: "XA-XFD1", category: "Pneumatic Lint Collector Series", tagline: null, page: 138 },
];

