/* ===========================================================================
   Emoji dataset — iOS-grouped 8 categories.

   ~700 emojis covering the same eight tabs Apple ships in iOS / macOS
   (Smileys & People, Animals & Nature, Food & Drink, Activity, Travel
   & Places, Objects, Symbols, Flags). Hand-curated rather than
   exhaustive — emoji 15+ adds new ones constantly and we'd rather
   keep the bundle small than mirror Unicode 1:1.

   Search keywords are pre-baked alongside each emoji so the picker
   can filter by typing without us having to ship the entire Unicode
   name database (which would 10× the bundle).
   ========================================================================== */

export interface EmojiEntry {
  /** The emoji character itself. */
  c: string;
  /** Space-separated keywords for search ("smile happy joy …"). All
   *  lowercase, ASCII only. */
  k: string;
}

export interface EmojiCategory {
  id: string;
  /** Two-character emoji used as the tab glyph (iOS-style). */
  icon: string;
  /** Default English label — translated at use site. */
  label: string;
  /** Translation key (matches financeT / dedicated chat dict if added). */
  key: string;
  emojis: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    icon: "😀",
    label: "Smileys & People",
    key: "emoji.smileys",
    emojis: [
      { c: "😀", k: "grin smile happy face" },
      { c: "😃", k: "smile happy face" },
      { c: "😄", k: "smile happy joy" },
      { c: "😁", k: "beam smile teeth" },
      { c: "😆", k: "laugh squint" },
      { c: "😅", k: "sweat laugh nervous" },
      { c: "🤣", k: "rofl laugh tears" },
      { c: "😂", k: "joy laugh tears" },
      { c: "🙂", k: "smile slight" },
      { c: "🙃", k: "upside down silly" },
      { c: "😉", k: "wink flirt" },
      { c: "😊", k: "blush smile happy" },
      { c: "😇", k: "innocent angel halo" },
      { c: "🥰", k: "love hearts smile" },
      { c: "😍", k: "love heart eyes" },
      { c: "🤩", k: "star eyes wow" },
      { c: "😘", k: "kiss love" },
      { c: "😗", k: "kiss" },
      { c: "😚", k: "kiss closed" },
      { c: "😙", k: "kiss smile" },
      { c: "😋", k: "yum tasty" },
      { c: "😛", k: "tongue silly" },
      { c: "😜", k: "wink tongue silly" },
      { c: "🤪", k: "zany crazy" },
      { c: "😝", k: "tongue squint" },
      { c: "🤑", k: "money mouth rich" },
      { c: "🤗", k: "hug" },
      { c: "🤭", k: "oops mouth" },
      { c: "🤫", k: "shh quiet" },
      { c: "🤔", k: "think hmm" },
      { c: "🤐", k: "zip silent" },
      { c: "🤨", k: "raised eyebrow" },
      { c: "😐", k: "neutral straight" },
      { c: "😑", k: "expressionless" },
      { c: "😶", k: "no mouth" },
      { c: "😏", k: "smirk" },
      { c: "😒", k: "unamused meh" },
      { c: "🙄", k: "eye roll" },
      { c: "😬", k: "grimace awkward" },
      { c: "🤥", k: "lie pinocchio" },
      { c: "😌", k: "relieved" },
      { c: "😔", k: "pensive sad" },
      { c: "😪", k: "sleepy tired" },
      { c: "🤤", k: "drool" },
      { c: "😴", k: "sleeping" },
      { c: "😷", k: "mask sick" },
      { c: "🤒", k: "thermometer sick" },
      { c: "🤕", k: "head bandage hurt" },
      { c: "🤢", k: "nausea sick" },
      { c: "🤮", k: "vomit sick" },
      { c: "🤧", k: "sneeze" },
      { c: "🥵", k: "hot heat" },
      { c: "🥶", k: "cold freeze" },
      { c: "🥴", k: "woozy drunk" },
      { c: "😵", k: "dizzy ko" },
      { c: "🤯", k: "mind blown shock" },
      { c: "🤠", k: "cowboy" },
      { c: "🥳", k: "party hat" },
      { c: "😎", k: "cool sunglasses" },
      { c: "🤓", k: "nerd glasses" },
      { c: "🧐", k: "monocle" },
      { c: "😕", k: "confused" },
      { c: "😟", k: "worried" },
      { c: "🙁", k: "slight frown" },
      { c: "☹️", k: "frown sad" },
      { c: "😮", k: "open mouth surprise" },
      { c: "😯", k: "hushed surprise" },
      { c: "😲", k: "astonished shock" },
      { c: "😳", k: "flushed embarrass" },
      { c: "🥺", k: "pleading puppy eyes" },
      { c: "😦", k: "frowning open" },
      { c: "😧", k: "anguished" },
      { c: "😨", k: "fearful" },
      { c: "😰", k: "cold sweat anxious" },
      { c: "😥", k: "sad relieved" },
      { c: "😢", k: "cry sad" },
      { c: "😭", k: "loud cry sob" },
      { c: "😱", k: "scream shock" },
      { c: "😖", k: "confounded" },
      { c: "😣", k: "persevere struggle" },
      { c: "😞", k: "disappointed sad" },
      { c: "😓", k: "downcast sweat" },
      { c: "😩", k: "weary tired" },
      { c: "😫", k: "tired exhausted" },
      { c: "🥱", k: "yawn tired" },
      { c: "😤", k: "huff steam" },
      { c: "😡", k: "angry mad rage" },
      { c: "😠", k: "angry mad" },
      { c: "🤬", k: "swear curse" },
      { c: "👍", k: "thumbs up ok yes" },
      { c: "👎", k: "thumbs down no" },
      { c: "👌", k: "ok perfect" },
      { c: "🤌", k: "pinched fingers" },
      { c: "🤏", k: "pinch small" },
      { c: "✌️", k: "peace victory" },
      { c: "🤞", k: "crossed fingers luck" },
      { c: "🤟", k: "love you sign" },
      { c: "🤘", k: "rock on horns" },
      { c: "🤙", k: "call me hang loose" },
      { c: "👈", k: "point left" },
      { c: "👉", k: "point right" },
      { c: "👆", k: "point up" },
      { c: "👇", k: "point down" },
      { c: "☝️", k: "index up one" },
      { c: "✋", k: "hand stop high five" },
      { c: "🤚", k: "raised back hand" },
      { c: "🖐️", k: "splayed hand five" },
      { c: "🖖", k: "vulcan spock" },
      { c: "👋", k: "wave hello bye" },
      { c: "🤝", k: "handshake deal" },
      { c: "🙏", k: "pray thanks please" },
      { c: "🙌", k: "praise hands celebration" },
      { c: "👏", k: "clap applause" },
      { c: "👊", k: "fist bump punch" },
      { c: "✊", k: "raised fist power" },
      { c: "🤛", k: "left fist bump" },
      { c: "🤜", k: "right fist bump" },
      { c: "💪", k: "muscle flex strong" },
      { c: "🦾", k: "robot arm" },
      { c: "👂", k: "ear listen" },
      { c: "👃", k: "nose smell" },
      { c: "👀", k: "eyes look watch" },
      { c: "👁️", k: "eye see" },
      { c: "👅", k: "tongue taste" },
      { c: "👄", k: "mouth lips" },
      { c: "💋", k: "kiss lips" },
      { c: "🧠", k: "brain mind think" },
      { c: "🫀", k: "anatomical heart" },
      { c: "🦴", k: "bone" },
      { c: "👶", k: "baby" },
      { c: "🧒", k: "child" },
      { c: "👦", k: "boy" },
      { c: "👧", k: "girl" },
      { c: "🧑", k: "person adult" },
      { c: "👨", k: "man" },
      { c: "👩", k: "woman" },
      { c: "🧔", k: "beard man" },
      { c: "👴", k: "old man grandpa" },
      { c: "👵", k: "old woman grandma" },
      { c: "👲", k: "person cap" },
      { c: "👳", k: "turban" },
      { c: "👮", k: "police officer" },
      { c: "👷", k: "construction worker" },
      { c: "💂", k: "guard" },
      { c: "🕵️", k: "detective spy" },
      { c: "👨‍⚕️", k: "doctor man" },
      { c: "👩‍⚕️", k: "doctor woman" },
      { c: "👨‍💻", k: "developer man tech" },
      { c: "👩‍💻", k: "developer woman tech" },
      { c: "👨‍💼", k: "office worker man" },
      { c: "👩‍💼", k: "office worker woman" },
      { c: "🤴", k: "prince" },
      { c: "👸", k: "princess" },
      { c: "🦸", k: "superhero" },
      { c: "🦹", k: "supervillain" },
      { c: "🤵", k: "tuxedo person" },
      { c: "👰", k: "bride veil" },
      { c: "🤰", k: "pregnant" },
      { c: "🤱", k: "breastfeed" },
      { c: "👨‍👩‍👧", k: "family" },
      { c: "💑", k: "couple" },
      { c: "💏", k: "couple kiss" },
    ],
  },
  {
    id: "nature",
    icon: "🐶",
    label: "Animals & Nature",
    key: "emoji.nature",
    emojis: [
      { c: "🐶", k: "dog puppy" }, { c: "🐱", k: "cat kitten" },
      { c: "🐭", k: "mouse" }, { c: "🐹", k: "hamster" },
      { c: "🐰", k: "rabbit bunny" }, { c: "🦊", k: "fox" },
      { c: "🐻", k: "bear" }, { c: "🐼", k: "panda" },
      { c: "🐨", k: "koala" }, { c: "🐯", k: "tiger" },
      { c: "🦁", k: "lion" }, { c: "🐮", k: "cow" },
      { c: "🐷", k: "pig" }, { c: "🐽", k: "pig nose" },
      { c: "🐸", k: "frog" }, { c: "🐵", k: "monkey" },
      { c: "🙈", k: "see no evil monkey" }, { c: "🙉", k: "hear no evil" },
      { c: "🙊", k: "speak no evil" }, { c: "🐒", k: "monkey" },
      { c: "🐔", k: "chicken" }, { c: "🐧", k: "penguin" },
      { c: "🐦", k: "bird" }, { c: "🐤", k: "baby chick" },
      { c: "🐣", k: "hatching chick" }, { c: "🐥", k: "chick" },
      { c: "🦆", k: "duck" }, { c: "🦅", k: "eagle" },
      { c: "🦉", k: "owl" }, { c: "🦇", k: "bat" },
      { c: "🐺", k: "wolf" }, { c: "🐗", k: "boar pig" },
      { c: "🐴", k: "horse" }, { c: "🦄", k: "unicorn" },
      { c: "🐝", k: "bee" }, { c: "🐛", k: "bug worm" },
      { c: "🦋", k: "butterfly" }, { c: "🐌", k: "snail" },
      { c: "🐞", k: "ladybug" }, { c: "🐜", k: "ant" },
      { c: "🦗", k: "cricket" }, { c: "🕷️", k: "spider" },
      { c: "🦂", k: "scorpion" }, { c: "🐢", k: "turtle" },
      { c: "🐍", k: "snake" }, { c: "🦎", k: "lizard" },
      { c: "🦖", k: "trex dinosaur" }, { c: "🦕", k: "sauropod dinosaur" },
      { c: "🐙", k: "octopus" }, { c: "🦑", k: "squid" },
      { c: "🦐", k: "shrimp" }, { c: "🦞", k: "lobster" },
      { c: "🦀", k: "crab" }, { c: "🐡", k: "blowfish" },
      { c: "🐠", k: "tropical fish" }, { c: "🐟", k: "fish" },
      { c: "🐬", k: "dolphin" }, { c: "🐳", k: "whale" },
      { c: "🐋", k: "whale big" }, { c: "🦈", k: "shark" },
      { c: "🐊", k: "crocodile" }, { c: "🐅", k: "tiger" },
      { c: "🐆", k: "leopard" }, { c: "🦓", k: "zebra" },
      { c: "🦍", k: "gorilla" }, { c: "🦧", k: "orangutan" },
      { c: "🐘", k: "elephant" }, { c: "🦛", k: "hippo" },
      { c: "🦏", k: "rhino" }, { c: "🐪", k: "camel" },
      { c: "🐫", k: "camel two humps" }, { c: "🦒", k: "giraffe" },
      { c: "🦘", k: "kangaroo" }, { c: "🐃", k: "buffalo" },
      { c: "🐂", k: "ox" }, { c: "🐄", k: "cow" },
      { c: "🐎", k: "horse race" }, { c: "🐖", k: "pig" },
      { c: "🐏", k: "ram" }, { c: "🐑", k: "sheep" },
      { c: "🦙", k: "llama" }, { c: "🐐", k: "goat" },
      { c: "🦌", k: "deer" }, { c: "🐕", k: "dog" },
      { c: "🐩", k: "poodle" }, { c: "🦮", k: "guide dog" },
      { c: "🐈", k: "cat" }, { c: "🐓", k: "rooster" },
      { c: "🦃", k: "turkey" }, { c: "🦚", k: "peacock" },
      { c: "🦜", k: "parrot" }, { c: "🦢", k: "swan" },
      { c: "🦩", k: "flamingo" }, { c: "🕊️", k: "dove peace" },
      { c: "🌲", k: "evergreen tree" }, { c: "🌳", k: "tree" },
      { c: "🌴", k: "palm tree" }, { c: "🌵", k: "cactus" },
      { c: "🌾", k: "rice grain" }, { c: "🌿", k: "herb plant" },
      { c: "☘️", k: "shamrock" }, { c: "🍀", k: "four leaf clover luck" },
      { c: "🍁", k: "maple leaf" }, { c: "🍂", k: "fallen leaves autumn" },
      { c: "🍃", k: "leaf wind" }, { c: "🌺", k: "hibiscus flower" },
      { c: "🌻", k: "sunflower" }, { c: "🌹", k: "rose" },
      { c: "🌷", k: "tulip" }, { c: "🌸", k: "cherry blossom" },
      { c: "🌼", k: "blossom flower" }, { c: "💐", k: "bouquet flowers" },
      { c: "🌱", k: "seedling sprout" }, { c: "🪴", k: "potted plant" },
      { c: "🌍", k: "earth africa europe" }, { c: "🌎", k: "earth americas" },
      { c: "🌏", k: "earth asia" }, { c: "🌑", k: "new moon" },
      { c: "🌕", k: "full moon" }, { c: "🌗", k: "last quarter moon" },
      { c: "🌙", k: "crescent moon" }, { c: "⭐", k: "star" },
      { c: "🌟", k: "glowing star" }, { c: "✨", k: "sparkles" },
      { c: "⚡", k: "lightning bolt" }, { c: "🔥", k: "fire" },
      { c: "💧", k: "water drop" }, { c: "🌊", k: "wave ocean" },
      { c: "☀️", k: "sun" }, { c: "🌤️", k: "sun cloud" },
      { c: "⛅", k: "partly sunny" }, { c: "☁️", k: "cloud" },
      { c: "🌧️", k: "rain cloud" }, { c: "⛈️", k: "thunderstorm" },
      { c: "🌩️", k: "lightning storm" }, { c: "🌨️", k: "snow cloud" },
      { c: "❄️", k: "snowflake" }, { c: "☃️", k: "snowman" },
      { c: "⛄", k: "snowman no snow" }, { c: "🌬️", k: "wind face" },
      { c: "🌫️", k: "fog" }, { c: "🌈", k: "rainbow" },
    ],
  },
  {
    id: "food",
    icon: "🍎",
    label: "Food & Drink",
    key: "emoji.food",
    emojis: [
      { c: "🍏", k: "green apple" }, { c: "🍎", k: "red apple" },
      { c: "🍐", k: "pear" }, { c: "🍊", k: "orange" },
      { c: "🍋", k: "lemon" }, { c: "🍌", k: "banana" },
      { c: "🍉", k: "watermelon" }, { c: "🍇", k: "grapes" },
      { c: "🍓", k: "strawberry" }, { c: "🫐", k: "blueberries" },
      { c: "🍈", k: "melon" }, { c: "🍒", k: "cherry" },
      { c: "🍑", k: "peach" }, { c: "🥭", k: "mango" },
      { c: "🍍", k: "pineapple" }, { c: "🥥", k: "coconut" },
      { c: "🥝", k: "kiwi" }, { c: "🍅", k: "tomato" },
      { c: "🍆", k: "eggplant" }, { c: "🥑", k: "avocado" },
      { c: "🥦", k: "broccoli" }, { c: "🥬", k: "leafy green" },
      { c: "🥒", k: "cucumber" }, { c: "🌶️", k: "hot pepper" },
      { c: "🫑", k: "bell pepper" }, { c: "🌽", k: "corn" },
      { c: "🥕", k: "carrot" }, { c: "🧄", k: "garlic" },
      { c: "🧅", k: "onion" }, { c: "🥔", k: "potato" },
      { c: "🍠", k: "sweet potato" }, { c: "🥐", k: "croissant" },
      { c: "🥖", k: "baguette" }, { c: "🍞", k: "bread" },
      { c: "🥨", k: "pretzel" }, { c: "🥯", k: "bagel" },
      { c: "🥞", k: "pancakes" }, { c: "🧇", k: "waffle" },
      { c: "🧀", k: "cheese" }, { c: "🍗", k: "chicken leg" },
      { c: "🍖", k: "meat bone" }, { c: "🥩", k: "steak" },
      { c: "🥓", k: "bacon" }, { c: "🍔", k: "hamburger" },
      { c: "🍟", k: "fries" }, { c: "🍕", k: "pizza" },
      { c: "🌭", k: "hot dog" }, { c: "🥪", k: "sandwich" },
      { c: "🌮", k: "taco" }, { c: "🌯", k: "burrito" },
      { c: "🫔", k: "tamale" }, { c: "🥙", k: "stuffed flatbread" },
      { c: "🧆", k: "falafel" }, { c: "🥚", k: "egg" },
      { c: "🍳", k: "fried egg" }, { c: "🥘", k: "shallow pan" },
      { c: "🍲", k: "stew pot" }, { c: "🫕", k: "fondue" },
      { c: "🥣", k: "bowl spoon" }, { c: "🥗", k: "salad" },
      { c: "🍿", k: "popcorn" }, { c: "🧈", k: "butter" },
      { c: "🧂", k: "salt" }, { c: "🥫", k: "canned food" },
      { c: "🍱", k: "bento" }, { c: "🍘", k: "rice cracker" },
      { c: "🍙", k: "rice ball" }, { c: "🍚", k: "rice" },
      { c: "🍛", k: "curry" }, { c: "🍜", k: "noodles ramen" },
      { c: "🍝", k: "spaghetti pasta" }, { c: "🍢", k: "oden" },
      { c: "🍣", k: "sushi" }, { c: "🍤", k: "fried shrimp" },
      { c: "🍥", k: "fish cake" }, { c: "🥮", k: "moon cake" },
      { c: "🍡", k: "dango" }, { c: "🥟", k: "dumpling" },
      { c: "🥠", k: "fortune cookie" }, { c: "🥡", k: "takeout" },
      { c: "🦪", k: "oyster" }, { c: "🍦", k: "soft ice cream" },
      { c: "🍧", k: "shaved ice" }, { c: "🍨", k: "ice cream" },
      { c: "🍩", k: "donut" }, { c: "🍪", k: "cookie" },
      { c: "🎂", k: "birthday cake" }, { c: "🍰", k: "cake slice" },
      { c: "🧁", k: "cupcake" }, { c: "🥧", k: "pie" },
      { c: "🍫", k: "chocolate" }, { c: "🍬", k: "candy" },
      { c: "🍭", k: "lollipop" }, { c: "🍮", k: "custard" },
      { c: "🍯", k: "honey" }, { c: "🍼", k: "baby bottle" },
      { c: "🥛", k: "milk" }, { c: "☕", k: "coffee hot" },
      { c: "🫖", k: "teapot" }, { c: "🍵", k: "tea" },
      { c: "🍶", k: "sake" }, { c: "🍾", k: "champagne" },
      { c: "🍷", k: "wine" }, { c: "🍸", k: "cocktail martini" },
      { c: "🍹", k: "tropical drink" }, { c: "🍺", k: "beer" },
      { c: "🍻", k: "cheers beer" }, { c: "🥂", k: "cheers" },
      { c: "🥃", k: "whiskey" }, { c: "🥤", k: "soda cup" },
      { c: "🧋", k: "bubble tea" }, { c: "🧃", k: "juice box" },
      { c: "🧉", k: "mate" }, { c: "🧊", k: "ice cube" },
    ],
  },
  {
    id: "activity",
    icon: "⚽",
    label: "Activity",
    key: "emoji.activity",
    emojis: [
      { c: "⚽", k: "soccer football" }, { c: "🏀", k: "basketball" },
      { c: "🏈", k: "american football" }, { c: "⚾", k: "baseball" },
      { c: "🥎", k: "softball" }, { c: "🎾", k: "tennis" },
      { c: "🏐", k: "volleyball" }, { c: "🏉", k: "rugby" },
      { c: "🥏", k: "frisbee" }, { c: "🎱", k: "pool 8 ball" },
      { c: "🪀", k: "yo-yo" }, { c: "🏓", k: "ping pong" },
      { c: "🏸", k: "badminton" }, { c: "🏒", k: "ice hockey" },
      { c: "🏑", k: "field hockey" }, { c: "🥍", k: "lacrosse" },
      { c: "🏏", k: "cricket" }, { c: "🥅", k: "goal net" },
      { c: "⛳", k: "golf flag" }, { c: "🪁", k: "kite" },
      { c: "🏹", k: "archery bow" }, { c: "🎣", k: "fishing" },
      { c: "🤿", k: "diving mask" }, { c: "🥊", k: "boxing glove" },
      { c: "🥋", k: "martial arts" }, { c: "🎽", k: "running shirt" },
      { c: "🛹", k: "skateboard" }, { c: "🛼", k: "roller skate" },
      { c: "🛷", k: "sled" }, { c: "⛸️", k: "ice skate" },
      { c: "🥌", k: "curling" }, { c: "🎿", k: "skis" },
      { c: "⛷️", k: "skier" }, { c: "🏂", k: "snowboarder" },
      { c: "🪂", k: "parachute" }, { c: "🏋️", k: "weightlift gym" },
      { c: "🤼", k: "wrestling" }, { c: "🤸", k: "cartwheel" },
      { c: "⛹️", k: "basketball player" }, { c: "🤺", k: "fencing" },
      { c: "🤾", k: "handball" }, { c: "🏌️", k: "golfer" },
      { c: "🏇", k: "horse racing" }, { c: "🧘", k: "yoga meditation" },
      { c: "🏄", k: "surfer" }, { c: "🏊", k: "swimmer" },
      { c: "🤽", k: "water polo" }, { c: "🚣", k: "rowboat" },
      { c: "🧗", k: "climber" }, { c: "🚴", k: "cyclist" },
      { c: "🚵", k: "mountain biker" }, { c: "🤹", k: "juggling" },
      { c: "🎯", k: "darts bullseye" }, { c: "🎮", k: "video game controller" },
      { c: "🕹️", k: "joystick game" }, { c: "🎰", k: "slot machine" },
      { c: "🎲", k: "dice game" }, { c: "🧩", k: "puzzle piece" },
      { c: "🎭", k: "theatre masks" }, { c: "🖼️", k: "framed picture art" },
      { c: "🎨", k: "art painter" }, { c: "🧵", k: "thread sewing" },
      { c: "🧶", k: "yarn knit" }, { c: "🎤", k: "microphone karaoke" },
      { c: "🎧", k: "headphone music" }, { c: "🎼", k: "musical score" },
      { c: "🎹", k: "piano keyboard" }, { c: "🥁", k: "drum" },
      { c: "🎷", k: "saxophone" }, { c: "🎺", k: "trumpet" },
      { c: "🎸", k: "guitar" }, { c: "🪕", k: "banjo" },
      { c: "🎻", k: "violin" }, { c: "🎬", k: "clapper film" },
      { c: "🎟️", k: "admission ticket" }, { c: "🎫", k: "ticket" },
      { c: "🎗️", k: "ribbon awareness" }, { c: "🎖️", k: "military medal" },
      { c: "🏅", k: "sports medal" }, { c: "🥇", k: "first place gold" },
      { c: "🥈", k: "second place silver" }, { c: "🥉", k: "third place bronze" },
      { c: "🏆", k: "trophy winner" }, { c: "🎊", k: "confetti ball" },
      { c: "🎉", k: "party popper celebrate" }, { c: "🎈", k: "balloon" },
      { c: "🎁", k: "gift present" }, { c: "🎀", k: "ribbon bow" },
    ],
  },
  {
    id: "travel",
    icon: "✈️",
    label: "Travel & Places",
    key: "emoji.travel",
    emojis: [
      { c: "🚗", k: "car automobile" }, { c: "🚕", k: "taxi" },
      { c: "🚙", k: "suv recreational" }, { c: "🚌", k: "bus" },
      { c: "🚎", k: "trolleybus" }, { c: "🏎️", k: "racing car" },
      { c: "🚓", k: "police car" }, { c: "🚑", k: "ambulance" },
      { c: "🚒", k: "fire engine" }, { c: "🚐", k: "minibus" },
      { c: "🛻", k: "pickup truck" }, { c: "🚚", k: "delivery truck" },
      { c: "🚛", k: "articulated lorry" }, { c: "🚜", k: "tractor" },
      { c: "🦽", k: "manual wheelchair" }, { c: "🦼", k: "motor wheelchair" },
      { c: "🛴", k: "kick scooter" }, { c: "🚲", k: "bicycle" },
      { c: "🛵", k: "motor scooter" }, { c: "🏍️", k: "motorcycle" },
      { c: "🛺", k: "auto rickshaw" }, { c: "🚨", k: "police siren" },
      { c: "🚔", k: "oncoming police" }, { c: "🚍", k: "oncoming bus" },
      { c: "🚘", k: "oncoming car" }, { c: "🚖", k: "oncoming taxi" },
      { c: "🚡", k: "aerial tram" }, { c: "🚠", k: "cable car" },
      { c: "🚟", k: "suspension railway" }, { c: "🚃", k: "railway car" },
      { c: "🚋", k: "tram car" }, { c: "🚞", k: "mountain railway" },
      { c: "🚝", k: "monorail" }, { c: "🚄", k: "high speed train" },
      { c: "🚅", k: "bullet train" }, { c: "🚈", k: "light rail" },
      { c: "🚂", k: "locomotive steam" }, { c: "🚆", k: "train" },
      { c: "🚇", k: "metro" }, { c: "🚊", k: "tram" },
      { c: "🚉", k: "station" }, { c: "✈️", k: "airplane plane" },
      { c: "🛫", k: "airplane departure" }, { c: "🛬", k: "airplane arrival" },
      { c: "🛩️", k: "small airplane" }, { c: "💺", k: "seat" },
      { c: "🚀", k: "rocket" }, { c: "🛰️", k: "satellite" },
      { c: "🚁", k: "helicopter" }, { c: "🛶", k: "canoe" },
      { c: "⛵", k: "sailboat" }, { c: "🚤", k: "speedboat" },
      { c: "🛥️", k: "motor boat" }, { c: "🛳️", k: "passenger ship" },
      { c: "⛴️", k: "ferry" }, { c: "🚢", k: "ship" },
      { c: "⚓", k: "anchor" }, { c: "⛽", k: "fuel pump gas" },
      { c: "🚧", k: "construction barrier" }, { c: "🚦", k: "vertical traffic light" },
      { c: "🚥", k: "horizontal traffic light" }, { c: "🗺️", k: "world map" },
      { c: "🗿", k: "moai statue" }, { c: "🗽", k: "statue of liberty" },
      { c: "🗼", k: "tokyo tower" }, { c: "🏰", k: "castle" },
      { c: "🏯", k: "japanese castle" }, { c: "🏟️", k: "stadium" },
      { c: "🎡", k: "ferris wheel" }, { c: "🎢", k: "roller coaster" },
      { c: "🎠", k: "carousel" }, { c: "⛲", k: "fountain" },
      { c: "⛱️", k: "beach umbrella" }, { c: "🏖️", k: "beach" },
      { c: "🏝️", k: "desert island" }, { c: "🏜️", k: "desert" },
      { c: "🌋", k: "volcano" }, { c: "⛰️", k: "mountain" },
      { c: "🏔️", k: "snow mountain" }, { c: "🗻", k: "mount fuji" },
      { c: "🏕️", k: "camping" }, { c: "⛺", k: "tent" },
      { c: "🏠", k: "house" }, { c: "🏡", k: "house garden" },
      { c: "🏘️", k: "houses" }, { c: "🏚️", k: "derelict house" },
      { c: "🏗️", k: "building construction" }, { c: "🏭", k: "factory" },
      { c: "🏢", k: "office building" }, { c: "🏬", k: "department store" },
      { c: "🏣", k: "japanese post" }, { c: "🏤", k: "european post" },
      { c: "🏥", k: "hospital" }, { c: "🏦", k: "bank" },
      { c: "🏨", k: "hotel" }, { c: "🏪", k: "convenience store" },
      { c: "🏫", k: "school" }, { c: "🏩", k: "love hotel" },
      { c: "💒", k: "wedding chapel" }, { c: "⛪", k: "church" },
      { c: "🕌", k: "mosque" }, { c: "🛕", k: "hindu temple" },
      { c: "🕍", k: "synagogue" }, { c: "⛩️", k: "shinto shrine" },
      { c: "🕋", k: "kaaba" }, { c: "🏛️", k: "classical building" },
      { c: "🌆", k: "cityscape dusk" }, { c: "🌇", k: "sunset over buildings" },
      { c: "🌃", k: "night with stars" }, { c: "🌉", k: "bridge night" },
      { c: "🌌", k: "milky way" }, { c: "♨️", k: "hot springs" },
    ],
  },
  {
    id: "objects",
    icon: "💡",
    label: "Objects",
    key: "emoji.objects",
    emojis: [
      { c: "⌚", k: "watch" }, { c: "📱", k: "phone iphone mobile" },
      { c: "📲", k: "phone arrow incoming call" }, { c: "💻", k: "laptop computer" },
      { c: "⌨️", k: "keyboard" }, { c: "🖥️", k: "desktop computer" },
      { c: "🖨️", k: "printer" }, { c: "🖱️", k: "computer mouse" },
      { c: "🖲️", k: "trackball" }, { c: "💽", k: "minidisc" }, { c: "💾", k: "floppy disk save" },
      { c: "💿", k: "cd" }, { c: "📀", k: "dvd" },
      { c: "📼", k: "videocassette vhs" }, { c: "📷", k: "camera" },
      { c: "📸", k: "camera flash" }, { c: "📹", k: "video camera" },
      { c: "🎥", k: "movie camera" }, { c: "📽️", k: "film projector" },
      { c: "🎞️", k: "film frames" }, { c: "📞", k: "telephone receiver" },
      { c: "☎️", k: "telephone" }, { c: "📟", k: "pager" },
      { c: "📠", k: "fax" }, { c: "📺", k: "television tv" },
      { c: "📻", k: "radio" }, { c: "🎙️", k: "studio microphone" },
      { c: "🎚️", k: "level slider" }, { c: "🎛️", k: "control knobs" },
      { c: "🧭", k: "compass" }, { c: "⏱️", k: "stopwatch" },
      { c: "⏲️", k: "timer clock" }, { c: "⏰", k: "alarm clock" },
      { c: "🕰️", k: "mantelpiece clock" }, { c: "⌛", k: "hourglass done" },
      { c: "⏳", k: "hourglass not done" }, { c: "📡", k: "satellite antenna" },
      { c: "🔋", k: "battery" }, { c: "🔌", k: "plug" },
      { c: "💡", k: "light bulb idea" }, { c: "🔦", k: "flashlight" },
      { c: "🕯️", k: "candle" }, { c: "🪔", k: "diya lamp" },
      { c: "🧯", k: "fire extinguisher" }, { c: "🛢️", k: "oil drum" },
      { c: "💸", k: "money with wings" }, { c: "💵", k: "dollar banknote" },
      { c: "💴", k: "yen banknote" }, { c: "💶", k: "euro banknote" },
      { c: "💷", k: "pound banknote" }, { c: "💰", k: "money bag" },
      { c: "💳", k: "credit card" }, { c: "🧾", k: "receipt" },
      { c: "💎", k: "gem diamond" }, { c: "⚖️", k: "balance scale" },
      { c: "🪜", k: "ladder" }, { c: "🧰", k: "toolbox" },
      { c: "🔧", k: "wrench" }, { c: "🔨", k: "hammer" },
      { c: "⚒️", k: "hammer pick" }, { c: "🛠️", k: "hammer wrench" },
      { c: "⛏️", k: "pick" }, { c: "🪓", k: "axe" },
      { c: "🪚", k: "saw" }, { c: "🔩", k: "nut bolt" },
      { c: "⚙️", k: "gear settings" }, { c: "🪤", k: "mouse trap" },
      { c: "🧱", k: "brick" }, { c: "⛓️", k: "chains" },
      { c: "🧲", k: "magnet" }, { c: "🔫", k: "water gun" },
      { c: "💣", k: "bomb" }, { c: "🧨", k: "firecracker" },
      { c: "🪃", k: "boomerang" }, { c: "🛡️", k: "shield" }, { c: "🪙", k: "coin" },
      { c: "🔪", k: "kitchen knife" }, { c: "🗡️", k: "dagger" },
      { c: "⚔️", k: "crossed swords" }, { c: "🚬", k: "cigarette" },
      { c: "⚰️", k: "coffin" }, { c: "🪦", k: "headstone" },
      { c: "⚱️", k: "funeral urn" }, { c: "🏺", k: "amphora" },
      { c: "🔮", k: "crystal ball" }, { c: "🪄", k: "magic wand" },
      { c: "📿", k: "prayer beads" }, { c: "🧿", k: "nazar amulet" },
      { c: "💈", k: "barber pole" }, { c: "⚗️", k: "alembic" },
      { c: "🔭", k: "telescope" }, { c: "🔬", k: "microscope" },
      { c: "🕳️", k: "hole" }, { c: "🩹", k: "adhesive bandage" },
      { c: "🩺", k: "stethoscope" }, { c: "💊", k: "pill" },
      { c: "💉", k: "syringe" }, { c: "🩸", k: "blood drop" },
      { c: "🧬", k: "dna" }, { c: "🦠", k: "microbe germ" },
      { c: "🧫", k: "petri dish" }, { c: "🧪", k: "test tube" },
      { c: "🌡️", k: "thermometer" }, { c: "🧹", k: "broom" },
      { c: "🪣", k: "bucket" }, { c: "🧺", k: "basket" },
      { c: "🧻", k: "toilet paper" }, { c: "🚽", k: "toilet" },
      { c: "🚰", k: "potable water" }, { c: "🚿", k: "shower" },
      { c: "🛁", k: "bathtub" }, { c: "🛀", k: "person bath" },
      { c: "🧼", k: "soap" }, { c: "🪥", k: "toothbrush" },
      { c: "🪒", k: "razor" }, { c: "🧽", k: "sponge" },
      { c: "🧴", k: "lotion bottle" }, { c: "🛎️", k: "bellhop bell" },
      { c: "🔑", k: "key" }, { c: "🗝️", k: "old key" },
      { c: "🚪", k: "door" }, { c: "🪑", k: "chair" },
      { c: "🛋️", k: "couch lamp" }, { c: "🛏️", k: "bed" },
      { c: "🛌", k: "person in bed" }, { c: "🪞", k: "mirror" },
      { c: "🪟", k: "window" }, { c: "📦", k: "package box" },
      { c: "📫", k: "mailbox closed flag" }, { c: "📪", k: "mailbox closed" },
      { c: "📬", k: "mailbox open flag" }, { c: "📭", k: "mailbox open" },
      { c: "📮", k: "postbox" }, { c: "✉️", k: "envelope email" },
      { c: "📩", k: "envelope arrow" }, { c: "📨", k: "incoming envelope" },
      { c: "📧", k: "email mail" }, { c: "📤", k: "outbox tray" },
      { c: "📥", k: "inbox tray" }, { c: "🗳️", k: "ballot box" },
      { c: "📜", k: "scroll" }, { c: "📃", k: "page curl" },
      { c: "📄", k: "page" }, { c: "📰", k: "newspaper" },
      { c: "🗞️", k: "rolled-up newspaper" }, { c: "📓", k: "notebook" },
      { c: "📔", k: "decorative notebook" }, { c: "📒", k: "ledger" },
      { c: "📕", k: "red book" }, { c: "📗", k: "green book" },
      { c: "📘", k: "blue book" }, { c: "📙", k: "orange book" },
      { c: "📚", k: "books" }, { c: "📖", k: "open book" },
      { c: "🔖", k: "bookmark" }, { c: "🧷", k: "safety pin" },
      { c: "🔗", k: "link" }, { c: "📎", k: "paperclip" },
      { c: "🖇️", k: "linked paperclips" }, { c: "📐", k: "triangular ruler" },
      { c: "📏", k: "straight ruler" }, { c: "🧮", k: "abacus" },
      { c: "📌", k: "pushpin pin" }, { c: "📍", k: "round pushpin" },
      { c: "✂️", k: "scissors" }, { c: "🖊️", k: "pen" },
      { c: "🖋️", k: "fountain pen" }, { c: "✒️", k: "black nib" },
      { c: "🖌️", k: "paintbrush" }, { c: "🖍️", k: "crayon" },
      { c: "📝", k: "memo writing pencil" }, { c: "✏️", k: "pencil" },
      { c: "🔍", k: "magnifying glass search" }, { c: "🔎", k: "search right" },
      { c: "🔏", k: "locked with pen" }, { c: "🔐", k: "locked with key" },
      { c: "🔒", k: "locked" }, { c: "🔓", k: "unlocked" },
      { c: "💼", k: "briefcase business" }, { c: "📊", k: "bar chart" },
      { c: "📈", k: "chart up trend" }, { c: "📉", k: "chart down trend" },
      { c: "📅", k: "calendar date" }, { c: "📆", k: "tear off calendar" },
      { c: "🗓️", k: "spiral calendar" }, { c: "📇", k: "card index" },
      { c: "🗃️", k: "card file box" }, { c: "🗄️", k: "file cabinet" },
      { c: "🗑️", k: "wastebasket trash" }, ],
  },
  {
    id: "symbols",
    icon: "❤️",
    label: "Symbols",
    key: "emoji.symbols",
    emojis: [
      { c: "❤️", k: "red heart love" }, { c: "🧡", k: "orange heart" },
      { c: "💛", k: "yellow heart" }, { c: "💚", k: "green heart" },
      { c: "💙", k: "blue heart" }, { c: "💜", k: "purple heart" },
      { c: "🖤", k: "black heart" }, { c: "🤍", k: "white heart" },
      { c: "🤎", k: "brown heart" }, { c: "💔", k: "broken heart" },
      { c: "❣️", k: "heart exclamation" }, { c: "💕", k: "two hearts" },
      { c: "💞", k: "revolving hearts" }, { c: "💓", k: "beating heart" },
      { c: "💗", k: "growing heart" }, { c: "💖", k: "sparkling heart" },
      { c: "💘", k: "heart arrow cupid" }, { c: "💝", k: "heart ribbon gift" },
      { c: "💟", k: "heart decoration" }, { c: "☮️", k: "peace symbol" },
      { c: "✝️", k: "latin cross" }, { c: "☪️", k: "star crescent" },
      { c: "🕉️", k: "om hindu" }, { c: "☸️", k: "wheel dharma" },
      { c: "✡️", k: "star of david" }, { c: "🔯", k: "six pointed star" },
      { c: "🕎", k: "menorah" }, { c: "☯️", k: "yin yang" },
      { c: "☦️", k: "orthodox cross" }, { c: "🛐", k: "place of worship" },
      { c: "⛎", k: "ophiuchus" }, { c: "♈", k: "aries" },
      { c: "♉", k: "taurus" }, { c: "♊", k: "gemini" },
      { c: "♋", k: "cancer" }, { c: "♌", k: "leo" },
      { c: "♍", k: "virgo" }, { c: "♎", k: "libra" },
      { c: "♏", k: "scorpio" }, { c: "♐", k: "sagittarius" },
      { c: "♑", k: "capricorn" }, { c: "♒", k: "aquarius" },
      { c: "♓", k: "pisces" }, { c: "🆔", k: "id button" },
      { c: "⚛️", k: "atom" }, { c: "🉑", k: "japanese acceptable" },
      { c: "☢️", k: "radioactive" }, { c: "☣️", k: "biohazard" },
      { c: "📴", k: "phone off" }, { c: "📳", k: "vibration mode" },
      { c: "🈶", k: "japanese not free" }, { c: "🈚", k: "japanese free" },
      { c: "🈸", k: "japanese application" }, { c: "🈺", k: "japanese open" },
      { c: "🈷️", k: "japanese monthly amount" }, { c: "✴️", k: "eight pointed star" },
      { c: "🆚", k: "vs" }, { c: "💮", k: "white flower" },
      { c: "🉐", k: "japanese bargain" }, { c: "㊙️", k: "japanese secret" },
      { c: "㊗️", k: "japanese congratulations" }, { c: "🈴", k: "japanese passing grade" },
      { c: "🈵", k: "japanese no vacancy" }, { c: "🈹", k: "japanese discount" },
      { c: "🈲", k: "japanese prohibited" }, { c: "🅰️", k: "a button blood" },
      { c: "🅱️", k: "b button blood" }, { c: "🆎", k: "ab button blood" },
      { c: "🆑", k: "cl button" }, { c: "🅾️", k: "o button blood" },
      { c: "🆘", k: "sos button" }, { c: "❌", k: "cross mark x no" },
      { c: "⭕", k: "hollow red circle" }, { c: "🛑", k: "stop sign" },
      { c: "⛔", k: "no entry" }, { c: "📛", k: "name badge" },
      { c: "🚫", k: "no prohibited" }, { c: "💯", k: "hundred points" },
      { c: "💢", k: "anger symbol" }, { c: "🚷", k: "no pedestrians" }, { c: "🚯", k: "no littering" },
      { c: "🚳", k: "no bicycles" }, { c: "🚱", k: "non potable water" },
      { c: "🔞", k: "no one under 18" }, { c: "📵", k: "no mobile" },
      { c: "🚭", k: "no smoking" }, { c: "❗", k: "exclamation" },
      { c: "❕", k: "white exclamation" }, { c: "❓", k: "question mark" },
      { c: "❔", k: "white question" }, { c: "‼️", k: "double exclamation" },
      { c: "⁉️", k: "exclamation question" }, { c: "🔅", k: "dim button" },
      { c: "🔆", k: "bright button" }, { c: "〽️", k: "part alternation" },
      { c: "⚠️", k: "warning" }, { c: "🚸", k: "children crossing" },
      { c: "🔱", k: "trident" }, { c: "⚜️", k: "fleur-de-lis" },
      { c: "🔰", k: "japanese beginner" }, { c: "♻️", k: "recycle" },
      { c: "✅", k: "check mark green" }, { c: "🈯", k: "japanese reserved" },
      { c: "💹", k: "chart yen" }, { c: "❇️", k: "sparkle" },
      { c: "✳️", k: "eight spoked asterisk" }, { c: "❎", k: "cross mark button" },
      { c: "🌐", k: "globe meridians web" }, { c: "💠", k: "diamond shape" },
      { c: "Ⓜ️", k: "m circled metro" }, { c: "🌀", k: "cyclone spiral" },
      { c: "💤", k: "zzz sleeping" }, { c: "🏧", k: "atm sign" },
      { c: "🚾", k: "water closet" }, { c: "♿", k: "wheelchair" },
      { c: "🅿️", k: "p button parking" }, { c: "🛗", k: "elevator" },
      { c: "🈳", k: "japanese vacancy" }, { c: "🈂️", k: "japanese service" },
      { c: "🛂", k: "passport control" }, { c: "🛃", k: "customs" },
      { c: "🛄", k: "baggage claim" }, { c: "🛅", k: "left luggage" },
      { c: "🚹", k: "men room" }, { c: "🚺", k: "women room" },
      { c: "🚼", k: "baby symbol" }, { c: "🚻", k: "restroom" },
      { c: "🚮", k: "litter bin" }, { c: "🎦", k: "cinema" },
      { c: "📶", k: "antenna bars signal" }, { c: "🈁", k: "japanese here" },
      { c: "🔣", k: "input symbols" }, { c: "ℹ️", k: "information" },
      { c: "🔤", k: "input latin letters" }, { c: "🔡", k: "input lowercase" },
      { c: "🔠", k: "input uppercase" }, { c: "🆖", k: "ng" },
      { c: "🆗", k: "ok button" }, { c: "🆙", k: "up button" },
      { c: "🆒", k: "cool button" }, { c: "🆕", k: "new button" },
      { c: "🆓", k: "free button" }, { c: "0️⃣", k: "0" },
      { c: "1️⃣", k: "1" }, { c: "2️⃣", k: "2" },
      { c: "3️⃣", k: "3" }, { c: "4️⃣", k: "4" },
      { c: "5️⃣", k: "5" }, { c: "6️⃣", k: "6" },
      { c: "7️⃣", k: "7" }, { c: "8️⃣", k: "8" },
      { c: "9️⃣", k: "9" }, { c: "🔟", k: "10" },
      { c: "🔢", k: "input numbers" }, { c: "#️⃣", k: "hash" },
      { c: "*️⃣", k: "asterisk" }, { c: "⏏️", k: "eject" },
      { c: "▶️", k: "play button" }, { c: "⏸️", k: "pause" },
      { c: "⏯️", k: "play pause" }, { c: "⏹️", k: "stop" },
      { c: "⏺️", k: "record" }, { c: "⏭️", k: "next track" },
      { c: "⏮️", k: "last track" }, { c: "⏩", k: "fast forward" },
      { c: "⏪", k: "fast reverse" }, { c: "⏫", k: "fast up" },
      { c: "⏬", k: "fast down" }, { c: "◀️", k: "reverse" },
      { c: "🔼", k: "up button" }, { c: "🔽", k: "down button" },
      { c: "➡️", k: "right arrow" }, { c: "⬅️", k: "left arrow" },
      { c: "⬆️", k: "up arrow" }, { c: "⬇️", k: "down arrow" },
      { c: "↗️", k: "up right arrow" }, { c: "↘️", k: "down right arrow" },
      { c: "↙️", k: "down left arrow" }, { c: "↖️", k: "up left arrow" },
      { c: "↕️", k: "up down arrow" }, { c: "↔️", k: "left right arrow" },
      { c: "↪️", k: "right arrow curving" }, { c: "↩️", k: "left arrow curving" },
      { c: "⤴️", k: "right arrow curving up" }, { c: "⤵️", k: "right arrow curving down" },
      { c: "🔀", k: "shuffle tracks" }, { c: "🔁", k: "repeat" },
      { c: "🔂", k: "repeat one" }, { c: "🔄", k: "counterclockwise arrows" },
      { c: "🔃", k: "clockwise vertical arrows" }, { c: "🎵", k: "musical note" },
      { c: "🎶", k: "musical notes" }, { c: "➕", k: "plus" },
      { c: "➖", k: "minus" }, { c: "➗", k: "divide" },
      { c: "✖️", k: "multiply" }, { c: "🟰", k: "equals" },
      { c: "♾️", k: "infinity" }, { c: "💲", k: "dollar" },
      { c: "💱", k: "currency exchange" }, { c: "™️", k: "trademark" },
      { c: "©️", k: "copyright" }, { c: "®️", k: "registered" },
    ],
  },
  {
    id: "flags",
    icon: "🏳️",
    label: "Flags",
    key: "emoji.flags",
    emojis: [
      { c: "🏁", k: "checkered flag finish" }, { c: "🚩", k: "triangular flag" },
      { c: "🎌", k: "crossed flags" }, { c: "🏴", k: "black flag" },
      { c: "🏳️", k: "white flag" }, { c: "🏳️‍🌈", k: "rainbow flag pride" },
      { c: "🏴‍☠️", k: "pirate flag" }, { c: "🇨🇳", k: "china flag cn" },
      { c: "🇺🇸", k: "usa flag us" }, { c: "🇬🇧", k: "uk flag" },
      { c: "🇪🇬", k: "egypt flag" }, { c: "🇸🇦", k: "saudi arabia flag" },
      { c: "🇦🇪", k: "uae flag emirates" }, { c: "🇨🇦", k: "canada flag" },
      { c: "🇯🇵", k: "japan flag" }, { c: "🇰🇷", k: "korea flag" },
      { c: "🇩🇪", k: "germany flag" }, { c: "🇫🇷", k: "france flag" },
      { c: "🇮🇹", k: "italy flag" }, { c: "🇪🇸", k: "spain flag" },
      { c: "🇧🇷", k: "brazil flag" }, { c: "🇮🇳", k: "india flag" },
      { c: "🇷🇺", k: "russia flag" }, { c: "🇦🇺", k: "australia flag" },
      { c: "🇲🇽", k: "mexico flag" }, { c: "🇹🇷", k: "turkey flag" },
      { c: "🇳🇱", k: "netherlands flag" }, { c: "🇸🇪", k: "sweden flag" },
      { c: "🇨🇭", k: "switzerland flag" }, { c: "🇧🇪", k: "belgium flag" },
      { c: "🇦🇹", k: "austria flag" }, { c: "🇩🇰", k: "denmark flag" },
      { c: "🇳🇴", k: "norway flag" }, { c: "🇫🇮", k: "finland flag" },
      { c: "🇮🇪", k: "ireland flag" }, { c: "🇵🇹", k: "portugal flag" },
      { c: "🇬🇷", k: "greece flag" }, { c: "🇵🇱", k: "poland flag" },
      { c: "🇨🇿", k: "czech flag" }, { c: "🇭🇺", k: "hungary flag" },
      { c: "🇷🇴", k: "romania flag" }, { c: "🇺🇦", k: "ukraine flag" },
      { c: "🇮🇱", k: "israel flag" }, { c: "🇮🇷", k: "iran flag" },
      { c: "🇮🇶", k: "iraq flag" }, { c: "🇸🇾", k: "syria flag" },
      { c: "🇯🇴", k: "jordan flag" }, { c: "🇱🇧", k: "lebanon flag" },
      { c: "🇶🇦", k: "qatar flag" }, { c: "🇰🇼", k: "kuwait flag" },
      { c: "🇲🇦", k: "morocco flag" }, { c: "🇩🇿", k: "algeria flag" },
      { c: "🇹🇳", k: "tunisia flag" }, { c: "🇱🇾", k: "libya flag" },
      { c: "🇸🇩", k: "sudan flag" }, { c: "🇿🇦", k: "south africa flag" },
      { c: "🇳🇬", k: "nigeria flag" }, { c: "🇰🇪", k: "kenya flag" },
      { c: "🇪🇹", k: "ethiopia flag" }, { c: "🇹🇭", k: "thailand flag" },
      { c: "🇻🇳", k: "vietnam flag" }, { c: "🇮🇩", k: "indonesia flag" },
      { c: "🇲🇾", k: "malaysia flag" }, { c: "🇸🇬", k: "singapore flag" },
      { c: "🇵🇭", k: "philippines flag" }, { c: "🇵🇰", k: "pakistan flag" },
      { c: "🇧🇩", k: "bangladesh flag" }, { c: "🇳🇿", k: "new zealand flag" },
      { c: "🇨🇱", k: "chile flag" }, { c: "🇦🇷", k: "argentina flag" },
      { c: "🇨🇴", k: "colombia flag" }, { c: "🇵🇪", k: "peru flag" },
      { c: "🇻🇪", k: "venezuela flag" }, { c: "🇪🇺", k: "european union flag" },
      { c: "🇺🇳", k: "united nations flag" }, { c: "🇭🇰", k: "hong kong flag" },
      { c: "🇹🇼", k: "taiwan flag" },
    ],
  },
];

/** Flat list of every emoji entry — handy for global keyword search. */
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis);
