/* Real-render proof for doc-gen: launches the actual local Chrome through
   the SHARED launcher, renders a bilingual sample document, saves the PDF
   into the workspace so the owner can open it. */
import { sanitizeDocInput, renderDocumentPdf } from "../src/lib/server/ai/doc-gen";
import * as fs from "node:fs";

async function main() {
  const raw = {
    title: "KOLEEX Hub — Weekly Operations Summary",
    subtitle: "Generated by Koleex AI · sample render",
    kind: "Report",
    reference: "KX-TEST-001",
    date: "8 October 2026",
    lang: "en",
    sections: [
      {
        heading: "Overview",
        paragraphs: [
          "This week covered three workstreams: the HR scroll fix reached production, image generation shipped through the generate_image tool, and the document engine you are reading now was built.",
          "All production deployments completed within their function budgets.",
        ],
        bullets: ["Zero security regressions", "Two new AI capabilities live", "One vendor switch (Qwen → Grok)"],
      },
      {
        heading: "Packing List — Sample Shipment",
        table: {
          columns: ["Item", "Model", "Qty", "Net Weight"],
          rows: [
            ["Overlock sewing machine", "KX-747D", "12", "34 kg"],
            ["Flatbed machine", "KX-0303", "8", "41 kg"],
            ["Spare parts kit", "KX-SP-02", "25", "2 kg"],
          ],
        },
      },
      {
        heading: "ملاحظات بالعربية",
        paragraphs: ["هذا الجزء يختبر الخط العربي داخل المستند الإنجليزي للتأكد من سلامة الحروف."],
      },
    ],
    footerNote: "Generated working document — not an official KOLEEX business document.",
  };

  const doc = sanitizeDocInput(raw);
  if (!doc) { console.error("sanitize rejected the sample"); process.exit(1); }

  const outcome = await renderDocumentPdf(doc);
  if (!outcome.ok) { console.error("render failed:", outcome.error); process.exit(1); }

  const out = "/Users/kamalshafei/Desktop/Koleex HUB/doc-gen-sample.pdf";
  fs.writeFileSync(out, outcome.bytes);
  console.log(`OK ms=${outcome.ms} bytes=${outcome.bytes.length}`);
  console.log("saved:", out);

  /* Adversarial: markup injection must survive as TEXT, never markup. */
  const evil = sanitizeDocInput({
    title: "<script>alert(1)</script>",
    sections: [{ paragraphs: ["<img src=x onerror=alert(1)>"] }],
  });
  if (!evil) { console.error("evil sample rejected entirely (unexpected)"); process.exit(1); }
  const evilOut = await renderDocumentPdf(evil);
  console.log("injection sample renders safely:", evilOut.ok);
}

main().catch((e) => { console.error(e); process.exit(1); });
