/* ---------------------------------------------------------------------------
   daily-quotes — decorative rotating quotes for the Home AIGreeter.
   (Phase 4 — Platform Speed Max-Out, Workstream 1: Home hydration reduction)

   Extracted out of src/app/page.tsx so these ~120 long localized strings are
   code-split into their own chunk and loaded lazily AFTER Home mounts
   (dynamic import inside AIGreeter), instead of being parsed on the Home
   critical path. Purely decorative content — reversible by re-inlining.
   --------------------------------------------------------------------------- */

export const DAILY_QUOTES: Record<string, string[]> = {
  en: [
    "Hard work beats talent when talent doesn't work hard, so show up every single day and let your effort speak for you.",
    "Success is not one great leap but the quiet sum of small efforts you repeat, faithfully, day after day after day.",
    "The only way to do truly great work is to love what you do, and to keep doing it long after the excitement fades.",
    "Dream as big as you dare and start as small as you must, but above everything else, find the courage to simply begin.",
    "Your future isn't waiting somewhere ahead of you; it is being built right now, quietly, by the choices you make today.",
    "Don't watch the clock and count the hours you have left — do what the clock does, and just keep moving forward.",
    "The harder you work for something, the greater the pride and the joy you will feel the moment you finally achieve it.",
    "Believe that you are truly capable, and you have already travelled half the distance toward whatever you set out to do.",
    "Opportunities rarely arrive on their own; far more often, they are created by the people brave enough to go looking.",
    "Discipline is the bridge that connects the goals you only imagine to the accomplishments you actually get to live.",
    "A little honest progress each day, however small it may seem, quietly adds up to results that will astonish you later.",
    "Work hard in silence, and let the quality of your results — not the volume of your words — make all of the noise.",
    "The secret of getting ahead is simply getting started, even before you feel completely ready to take the first step.",
    "Don't let your challenges decide the limit of who you become; instead, rise up and dare to challenge your own limits.",
    "Great things are never born inside the comfort zone, so be willing to step into the discomfort that real growth demands.",
    "Push yourself forward, because no one else is going to do it for you, and the effort you give is the gift you keep.",
    "Success will not come walking to your door; you have to decide where it lives and travel the whole way to meet it.",
    "Every expert you admire was once a clumsy beginner who simply refused to give up before they had a chance to improve.",
    "Stay patient, trust the long road you are walking, and remember that slow progress is still progress worth keeping.",
    "Wake up each morning with quiet determination, and go to bed each night with the deep satisfaction of effort well spent.",
    "If a goal does not challenge you in some real and uncomfortable way, then it almost certainly will not change you either.",
    "Become so good, so consistent, and so genuinely reliable at what you do that the world simply cannot afford to ignore you.",
    "Small, steady steps taken every single day will carry you much further than the giant leaps you only ever dream about.",
    "Don't stop running the moment you feel tired; stop only when the work is genuinely, honestly, and completely finished.",
    "The only limit that truly holds you back is the one you quietly agree to place upon yourself — so refuse to accept it.",
    "The hardest days are often the very ones that build the strongest people, so meet them with courage instead of fear.",
    "Focus on being truly productive rather than merely busy, because constant motion and real progress are not the same thing.",
    "Treat every single day as a blank canvas, and do the patient work to make it a small masterpiece you are proud of.",
    "The difference between the ordinary and the extraordinary is almost always found in that little bit of extra effort.",
    "Do something today, however small, that the person you become tomorrow will look back on and sincerely thank you for.",
    "Energy, patience, and stubborn persistence will, in the end, conquer nearly everything that once seemed impossible.",
    "Don't waste your wishes on the work being easier; spend your energy instead on becoming stronger and more capable.",
    "Success has a strange habit of arriving for the people who are far too busy doing the work to go chasing after it.",
    "The most reliable way to predict your future is to stop guessing about it and quietly get busy creating it yourself.",
    "Action is the foundation beneath every success — ideas may inspire you, but only doing the work will ever carry you.",
    "No matter how many times life knocks you down, the only number that truly matters is the one more time that you rise.",
    "Work for a cause you genuinely believe in rather than for the applause of others, and let purpose, not praise, drive you.",
    "Every great accomplishment, without a single exception, begins with the quiet, simple, and very brave decision to try.",
    "True quality is what you create when no one is watching, measured only by the high standards you refuse to lower.",
    "Believe in yourself and in everything you already are, then go and become everything you are still capable of being.",
  ],
  zh: [
    "当天赋不肯努力时，努力终将胜出；所以每一天都全力以赴，让你的付出替你说话。",
    "成功不是一次伟大的飞跃，而是你日复一日、忠实地重复着的那些微小努力的安静累积。",
    "做出真正伟大工作的唯一方法，就是热爱你所做的事，并在热情褪去之后依然坚持下去。",
    "敢想多大就想多大，必须多小就从多小开始，但最重要的，是找到迈出第一步的勇气。",
    "你的未来并不在前方某处等你，而是此刻正由你今天所做的每一个选择，悄悄地建造着。",
    "不要盯着时钟去数自己还剩多少小时——像时钟那样，只管不停地向前走。",
    "你为一件事付出得越多，真正达成它的那一刻，你所感到的骄傲与喜悦就越深。",
    "相信自己真的有能力做到，你便已经走完了通往目标的一半路程。",
    "机会很少自己降临，更多时候，是由那些有勇气主动去寻找的人亲手创造的。",
    "自律，是连接你所想象的目标与你真正得以实现的成就之间的那座桥梁。",
    "每天一点点真实的进步，无论看起来多么微小，都会在日后悄悄汇成令你惊叹的成果。",
    "在沉默中努力，让你成果的质量、而不是言语的多少，去发出所有的声音。",
    "领先的秘诀，不过是先开始——哪怕你还没完全准备好迈出第一步。",
    "别让困难来决定你能成为谁；相反，要挺身而起，敢于去挑战你自己的极限。",
    "伟大从不诞生于舒适区，所以请甘愿走进真正的成长所必需的那份不适之中。",
    "推动自己向前，因为没有人会替你这么做；而你付出的努力，正是你为自己留下的礼物。",
    "成功不会自己走到你门前；你得决定它住在哪里，然后走完全程去与它相遇。",
    "你所敬佩的每一位专家，都曾是笨拙的初学者，只是他们在进步之前从不肯放弃。",
    "保持耐心，信任你正在走的这条漫长道路，并记住：缓慢的进步，依然是值得珍惜的进步。",
    "每天清晨带着安静的决心醒来，每个夜晚带着付出之后那份深深的满足入睡。",
    "如果一个目标没有以某种真实而不适的方式挑战你，那它几乎也不会以任何持久的方式改变你。",
    "把你所做的事做到如此出色、如此稳定、如此可靠，让这个世界再也无法忽视你。",
    "每一天迈出的微小而坚定的步伐，会带你走得比你只敢空想的那些巨大飞跃更远。",
    "不要在感到疲惫的那一刻就停下；只有当工作真正、诚实、彻底地完成时，才停下来。",
    "真正困住你的唯一极限，是你默默同意加在自己身上的那一个——所以请拒绝接受它。",
    "最艰难的日子，往往正是造就最坚强的人的日子；所以请用勇气、而非恐惧去迎接它们。",
    "专注于真正的高效，而不只是看起来忙碌，因为不停的奔忙与真正的进步从来不是一回事。",
    "把每一天都当作一张空白的画布，用耐心去把它画成一幅你引以为傲的小小杰作。",
    "平凡与非凡之间的差别，几乎总是藏在那多付出的一点点努力里。",
    "今天去做一件事——哪怕很小——让明天的你回望时，会由衷地感谢今天的自己。",
    "精力、耐心与倔强的坚持，终将征服几乎一切曾经看似不可能的事情。",
    "别把愿望浪费在「但愿事情更容易」上；把你的精力用在让自己变得更强、更有能力上。",
    "成功有个奇怪的习惯：它总是降临在那些忙于做事、无暇去追逐它的人身上。",
    "预测你未来最可靠的方法，就是别再去猜测，而是安静地动手，亲自去创造它。",
    "行动是一切成功的根基——想法或许能激励你，但唯有真正动手去做，才能带你前行。",
    "无论生活把你击倒多少次，真正重要的，永远只是你再次站起来的那一次。",
    "为你所真正相信的事业而努力，而非为他人的掌声；让目标、而非赞美，驱动你前行。",
    "每一项伟大的成就，无一例外，都始于那个安静、简单而无比勇敢的决定：去尝试。",
    "真正的品质，是你在无人注视时所创造的东西，只以你拒绝降低的那份高标准来衡量。",
    "相信你自己以及你已然拥有的一切，然后去成为你仍有能力成为的那个自己。",
  ],
  ar: [
    "الاجتهاد يتغلّب على الموهبة حين لا تجتهد الموهبة؛ فاحضر كل يوم، ودَع جهدك يتحدّث عنك.",
    "النجاح ليس قفزةً واحدة كبرى، بل هو الحصيلة الهادئة لجهودٍ صغيرة تكرّرها بإخلاص يومًا بعد يوم.",
    "الطريق الوحيد للعمل العظيم حقًّا أن تحبّ ما تفعله، وأن تستمرّ فيه حتى بعد أن يخبو الحماس.",
    "احلم بقدر ما تجرؤ، وابدأ بأصغر ما تستطيع، ولكن قبل كل شيء، اعثر على شجاعة أن تبدأ.",
    "مستقبلك لا ينتظرك في مكانٍ ما أمامك، بل يُبنى الآن بهدوء عبر الخيارات التي تتّخذها اليوم.",
    "لا تراقب الساعة وتَعُدّ ما تبقّى لك من ساعات — افعل كما تفعل هي، وواصل التقدّم ببساطة.",
    "كلما اجتهدت أكثر لأجل شيء، كان فخرك وفرحتك أعظم في اللحظة التي تحقّقه فيها أخيرًا.",
    "آمِن بأنك قادر حقًّا، فتكون قد قطعت بالفعل نصف الطريق نحو كل ما عزمت على بلوغه.",
    "الفرص نادرًا ما تأتي وحدها؛ بل غالبًا ما يصنعها أولئك الشجعان بما يكفي للبحث عنها.",
    "الانضباط هو الجسر الذي يربط بين الأهداف التي تتخيّلها والإنجازات التي تعيشها فعلًا.",
    "تقدّمٌ بسيط وصادق كل يوم، مهما بدا ضئيلًا، يتراكم بهدوء ليصير نتائج تذهلك لاحقًا.",
    "اجتهد في صمت، ودَع جودة نتائجك — لا كثرة كلامك — هي التي تُحدث كل الضجيج.",
    "سرّ التقدّم ببساطة أن تبدأ، حتى قبل أن تشعر بأنك جاهز تمامًا لاتخاذ الخطوة الأولى.",
    "لا تدع تحدّياتك تقرّر مَن ستصبح؛ بل انهض وتجرّأ على أن تتحدّى حدودك أنت.",
    "الأشياء العظيمة لا تُولد داخل منطقة الراحة، فكن مستعدًّا لخوض ما يتطلّبه النموّ الحقيقي من مشقّة.",
    "ادفع نفسك إلى الأمام، فلن يفعل ذلك أحد غيرك، والجهد الذي تبذله هو الهدية التي تبقى لك.",
    "النجاح لن يأتي إلى بابك؛ عليك أن تقرّر أين يسكن، وأن تقطع الطريق كله للقائه.",
    "كل خبيرٍ تُعجَب به كان يومًا مبتدئًا أخرق، لكنه رفض ببساطة أن يستسلم قبل أن تتاح له فرصة التحسّن.",
    "تحلَّ بالصبر، وثِق بالطريق الطويل الذي تسلكه، وتذكّر أن التقدّم البطيء يظلّ تقدّمًا يستحقّ التمسّك به.",
    "استيقظ كل صباح بعزيمة هادئة، ونم كل ليلة برضا عميق عمّا بذلته من جهد.",
    "إن لم يتحدَّك الهدف بشكل حقيقي وغير مريح، فإنه على الأرجح لن يغيّرك بأي شكل دائم.",
    "كن بارعًا وثابتًا وموثوقًا حقًّا في عملك إلى حدٍّ يجعل العالم عاجزًا عن تجاهلك.",
    "الخطوات الصغيرة الثابتة التي تخطوها كل يوم ستحملك أبعد بكثير من القفزات الكبرى التي تكتفي بالحلم بها.",
    "لا تتوقّف في اللحظة التي تشعر فيها بالتعب؛ توقّف فقط حين يكتمل العمل حقًّا وبصدق وتمام.",
    "الحدّ الوحيد الذي يكبحك فعلًا هو ذاك الذي توافق بصمت على وضعه على نفسك — فارفض أن تقبله.",
    "أصعب الأيام غالبًا هي ذاتها التي تصنع أقوى الناس، فاستقبلها بالشجاعة لا بالخوف.",
    "ركّز على أن تكون منتجًا حقًّا لا مجرّد مشغول، فالحركة الدائمة والتقدّم الحقيقي ليسا الشيء ذاته.",
    "تعامل مع كل يوم كلوحة بيضاء، واعمل بصبر على أن تجعله تحفةً صغيرة تفخر بها.",
    "الفرق بين العادي والاستثنائي يكمن دائمًا تقريبًا في ذلك القدر الإضافي البسيط من الجهد.",
    "افعل اليوم شيئًا، مهما صغُر، يشكرك عليه الشخص الذي ستصبحه غدًا حين ينظر إلى الوراء.",
    "الطاقة والصبر والمثابرة العنيدة ستقهر في النهاية كل ما بدا ذات يوم مستحيلًا.",
    "لا تُهدر أمنياتك على أن يكون الأمر أسهل؛ أنفِق طاقتك على أن تصير أقوى وأكثر قدرة.",
    "للنجاح عادة غريبة: فهو يأتي لأولئك المنشغلين بالعمل أكثر من أن يلهثوا وراءه.",
    "أوثق وسيلة للتنبؤ بمستقبلك أن تكفّ عن تخمينه، وأن تنشغل بهدوء في صناعته بنفسك.",
    "الفعل هو الأساس الذي يقوم عليه كل نجاح؛ فالأفكار قد تُلهمك، لكن العمل وحده هو ما يحملك.",
    "مهما أسقطتك الحياة من مرّات، فالرقم الوحيد الذي يهمّ حقًّا هو مرّة النهوض الإضافية.",
    "اعمل من أجل قضية تؤمن بها حقًّا لا من أجل تصفيق الآخرين، ودَع الغاية لا المديح تقودك.",
    "كل إنجاز عظيم، بلا استثناء واحد، يبدأ بقرار هادئ وبسيط وشجاع للغاية: أن تحاول.",
    "الجودة الحقيقية هي ما تصنعه حين لا يراك أحد، ولا يقيسها سوى المعايير العالية التي ترفض خفضها.",
    "آمِن بنفسك وبكل ما أنت عليه الآن، ثم اذهب لتصبح كل ما لا تزال قادرًا على أن تكونه.",
  ],
};
