/* AUTO-GENERATED from ./catalog.ts by scripts/reports-heads.ts — do not
   hand-edit. After changing the catalog, run `npm run -s reports:heads`:
   validate:reports fails while this file differs from it.

   The HEADS of the built-in report types — what the Reports home needs to
   list a type, group it, draw it and decide who is offered it; never its
   sections, readers or defaults. The home and its lists import this; the
   full catalog stays with the server and the template builder's own chunk
   (validate:reports §23/§25), so the page no longer carries every type's
   sections. */

import type { ReportFamily, ReportTemplateHead } from "./templates";

export const REPORT_HEADS: readonly ReportTemplateHead[] = [
  { key: "daily", family: "work", icon: "calendar", cadence: "daily" },
  { key: "weekly_plan", family: "work", icon: "bullseye-arrow", cadence: "weekly" },
  { key: "weekly", family: "work", icon: "clipboard", cadence: "weekly" },
  { key: "monthly", family: "work", icon: "newspaper", cadence: "monthly" },
  { key: "customer_visit", family: "visits", icon: "handshake", cadence: null },
  { key: "supplier_visit", family: "visits", icon: "building", cadence: null },
  { key: "customer_call", family: "sales", icon: "user-headset", cadence: null },
  { key: "complaint", family: "sales", icon: "hand-holding-heart", cadence: null },
  { key: "lost_deal", family: "sales", icon: "cross-circle", cadence: null },
  { key: "sales_weekly", family: "sales", icon: "coins", cadence: "weekly" },
  { key: "sales_monthly", family: "sales", icon: "money", cadence: "monthly" },
  { key: "quote_followup", family: "sales", icon: "clock", cadence: null },
  { key: "collection", family: "sales", icon: "wallet", cadence: null },
  { key: "account_plan", family: "sales", icon: "flag-checkered", cadence: null },
  { key: "account_review", family: "sales", icon: "badge-check", cadence: null },
  { key: "competitor_prices", family: "sales", icon: "scale", cadence: null },
  { key: "country_study", family: "sales", icon: "ship-side", cadence: null },
  { key: "agent_report", family: "sales", icon: "contract", cadence: null },
  { key: "pre_shipment", family: "quality", icon: "box-circle-check", cadence: null },
  { key: "incoming", family: "quality", icon: "box-open", cadence: null },
  { key: "defect_report", family: "quality", icon: "stethoscope", cadence: null },
  { key: "corrective_action", family: "quality", icon: "recycle", cadence: null },
  { key: "supplier_return", family: "quality", icon: "delivery-truck", cadence: null },
  { key: "supplier_approval", family: "suppliers", icon: "shield-check", cadence: null },
  { key: "sample_evaluation", family: "suppliers", icon: "flask", cadence: null },
  { key: "negotiation", family: "suppliers", icon: "percentage", cadence: null },
  { key: "production_followup", family: "suppliers", icon: "pallet", cadence: null },
  { key: "supplier_performance", family: "suppliers", icon: "heart-rate", cadence: null },
  { key: "supplier_risk", family: "suppliers", icon: "flag-alt", cadence: null },
  { key: "supplier_stop", family: "suppliers", icon: "lock", cadence: null },
  { key: "purchasing_weekly", family: "suppliers", icon: "truck-container", cadence: "weekly" },
  { key: "purchasing_monthly", family: "suppliers", icon: "ship-side", cadence: "monthly" },
  { key: "late_pos", family: "suppliers", icon: "clock", cadence: null },
  { key: "payables", family: "suppliers", icon: "file-invoice-dollar", cadence: null },
  { key: "container_loading", family: "logistics", icon: "truck-side", cadence: null },
  { key: "shipment_update", family: "logistics", icon: "shipping-fast", cadence: null },
  { key: "damage_claim", family: "logistics", icon: "gavel", cadence: null },
  { key: "customs_clearance", family: "logistics", icon: "stamp", cadence: null },
  { key: "service_visit", family: "service", icon: "car-mechanic", cadence: null },
  { key: "warranty_claim", family: "service", icon: "receipt", cadence: null },
  { key: "customer_training", family: "service", icon: "graduation-cap", cadence: null },
  { key: "spare_parts_request", family: "service", icon: "cog", cadence: null },
  { key: "trip_report", family: "travel", icon: "plane-departure", cadence: null },
  { key: "delegation_visit", family: "travel", icon: "hotel", cadence: null },
  { key: "meeting_minutes", family: "travel", icon: "chair-office", cadence: null },
  { key: "decision_log", family: "travel", icon: "books", cadence: null },
  { key: "factory_audit", family: "suppliers", icon: "tools", cadence: null },
  { key: "price_comparison", family: "suppliers", icon: "balance-scale-left", cadence: null },
  { key: "installation", family: "service", icon: "hammer", cadence: null },
  { key: "team_summary", family: "team", icon: "users", cadence: null, teamOnly: true },
  { key: "one_on_one", family: "team", icon: "handshake", cadence: null, teamOnly: true },
  { key: "promotion_recommendation", family: "team", icon: "award", cadence: null, teamOnly: true },
  { key: "morning_brief", family: "office", icon: "mug-hot", cadence: null, officeOnly: true },
  { key: "decisions_waiting", family: "office", icon: "scale", cadence: null, officeOnly: true },
  { key: "followups_open", family: "office", icon: "clipboard", cadence: null, officeOnly: true },
  { key: "promises_log", family: "office", icon: "badge-check", cadence: null, officeOnly: true },
  { key: "calls_log", family: "office", icon: "user-headset", cadence: null, officeOnly: true },
  { key: "next_week", family: "office", icon: "calendar", cadence: null, officeOnly: true },
  { key: "trip_folder", family: "office", icon: "plane", cadence: null, officeOnly: true },
  { key: "bookings_log", family: "office", icon: "ticket", cadence: null, officeOnly: true },
  { key: "time_split", family: "office", icon: "clock", cadence: null, officeOnly: true },
  { key: "meetings_summary", family: "office", icon: "chair-office", cadence: null, officeOnly: true },
  { key: "office_readiness", family: "office", icon: "broom", cadence: null, officeOnly: true },
  { key: "admin_affairs", family: "office", icon: "building", cadence: "monthly", officeOnly: true },
  { key: "office_expenses", family: "office", icon: "wallet", cadence: "monthly", officeOnly: true },
  { key: "assets_custody", family: "office", icon: "key", cadence: null, officeOnly: true },
  { key: "renewals", family: "office", icon: "recycle", cadence: null, officeOnly: true },
  { key: "visitors_log", family: "office", icon: "id-badge", cadence: null, officeOnly: true },
  { key: "gov_bank", family: "office", icon: "bank", cadence: null, officeOnly: true },
  { key: "company_documents", family: "office", icon: "file", cadence: null, officeOnly: true },
  { key: "stamp_log", family: "office", icon: "signature", cadence: null, officeOnly: true },
  { key: "correspondence", family: "office", icon: "paper-plane", cadence: null, officeOnly: true },
  { key: "gift_register", family: "office", icon: "gift", cadence: null, officeOnly: true },
  { key: "occasions", family: "office", icon: "cocktail", cadence: null, officeOnly: true },
  { key: "decision_memo", family: "memos", icon: "gavel", cadence: null },
  { key: "escalation", family: "memos", icon: "flag-alt", cadence: null, urgent: true },
  { key: "handover", family: "memos", icon: "briefcase", cadence: null },
  { key: "free", family: "memos", icon: "document", cadence: null },
  { key: "hr_incident", family: "hr", group: "records", icon: "hard-hat", cadence: null, urgent: true },
  { key: "hr_grievance", family: "hr", group: "relations", icon: "lock", cadence: null },
  { key: "hr_warning", family: "hr", group: "relations", icon: "id-badge", cadence: null, hrOnly: true },
  { key: "hr_exit_interview", family: "hr", group: "exit", icon: "users", cadence: null, hrOnly: true },
  { key: "hr_hiring_plan", family: "hr", group: "hiring", icon: "users", cadence: null, app: "HR" },
  { key: "hr_pipeline", family: "hr", group: "hiring", icon: "search", cadence: "weekly", app: "HR" },
  { key: "hr_interview", family: "hr", group: "hiring", icon: "user-headset", cadence: null, app: "HR" },
  { key: "hr_reference_check", family: "hr", group: "hiring", icon: "fingerprint", cadence: null, hrOnly: true, app: "HR" },
  { key: "hr_offer", family: "hr", group: "hiring", icon: "contract", cadence: null, hrOnly: true, app: "HR" },
  { key: "hr_onboarding", family: "hr", group: "hiring", icon: "box-circle-check", cadence: null, app: "HR" },
  { key: "hr_new_hire", family: "hr", group: "hiring", icon: "graduation-cap", cadence: "weekly", app: "HR" },
  { key: "hr_attendance", family: "hr", group: "time", icon: "fingerprint", cadence: "monthly", app: "HR" },
  { key: "hr_lateness", family: "hr", group: "time", icon: "clock", cadence: "monthly", app: "HR" },
  { key: "hr_leave", family: "hr", group: "time", icon: "calendar", cadence: "monthly", app: "HR" },
  { key: "hr_overtime", family: "hr", group: "time", icon: "clock", cadence: "monthly", app: "HR" },
  { key: "hr_payroll", family: "hr", group: "pay", icon: "money", cadence: "monthly", payrollOnly: true },
  { key: "hr_staff_cost", family: "hr", group: "pay", icon: "calculator", cadence: "monthly", payrollOnly: true },
  { key: "hr_insurance", family: "hr", group: "pay", icon: "shield-check", cadence: "monthly", app: "HR" },
  { key: "hr_salary_review", family: "hr", group: "pay", icon: "percentage", cadence: null, payrollOnly: true },
  { key: "hr_appraisal", family: "hr", group: "performance", icon: "award", cadence: null, app: "HR" },
  { key: "hr_appraisal_results", family: "hr", group: "performance", icon: "badge-check", cadence: null, app: "HR" },
  { key: "hr_training", family: "hr", group: "performance", icon: "books", cadence: "monthly", app: "HR" },
  { key: "hr_skills", family: "hr", group: "performance", icon: "bulb", cadence: null, app: "HR" },
  { key: "hr_behavior", family: "hr", group: "performance", icon: "heart-rate", cadence: null, app: "HR" },
  { key: "hr_investigation", family: "hr", group: "relations", icon: "gavel", cadence: null, hrOnly: true, app: "HR" },
  { key: "hr_grievance_summary", family: "hr", group: "relations", icon: "hand-holding-heart", cadence: "monthly", app: "HR" },
  { key: "hr_movement", family: "hr", group: "exit", icon: "arrow-up-right", cadence: "monthly", app: "HR" },
  { key: "hr_turnover", family: "hr", group: "exit", icon: "recycle", cadence: "monthly", app: "HR" },
  { key: "hr_end_of_service", family: "hr", group: "exit", icon: "stamp", cadence: null, hrOnly: true, app: "HR" },
  { key: "hr_expiring", family: "hr", group: "records", icon: "clock", cadence: "monthly", app: "HR" },
  { key: "hr_contracts", family: "hr", group: "records", icon: "contract", cadence: "monthly", app: "HR" },
  { key: "hr_missing_files", family: "hr", group: "records", icon: "file", cadence: "monthly", app: "HR" },
  { key: "hr_safety_inspection", family: "hr", group: "records", icon: "hard-hat", cadence: "monthly", app: "HR" },
  { key: "hr_monthly", family: "hr", group: "records", icon: "newspaper", cadence: "monthly", app: "HR" },
  { key: "hr_headcount", family: "hr", group: "records", icon: "building", cadence: "monthly", app: "HR" },
  { key: "prj_proposal", family: "projects", group: "start", icon: "bulb", cadence: null, app: "Projects" },
  { key: "prj_charter", family: "projects", group: "start", icon: "flag-checkered", cadence: null, app: "Projects" },
  { key: "prj_plan", family: "projects", group: "start", icon: "calendar", cadence: null, app: "Projects" },
  { key: "prj_stakeholders", family: "projects", group: "start", icon: "users", cadence: null, app: "Projects" },
  { key: "prj_status", family: "projects", group: "execution", icon: "clipboard", cadence: "weekly", app: "Projects" },
  { key: "prj_progress", family: "projects", group: "execution", icon: "bullseye-arrow", cadence: null, app: "Projects" },
  { key: "prj_budget", family: "projects", group: "execution", icon: "coins", cadence: null, app: "Projects" },
  { key: "prj_resources", family: "projects", group: "execution", icon: "users", cadence: "monthly", app: "Projects" },
  { key: "prj_overdue", family: "projects", group: "execution", icon: "clock", cadence: null, app: "Projects" },
  { key: "prj_dependencies", family: "projects", group: "execution", icon: "key", cadence: null, app: "Projects" },
  { key: "prj_risks", family: "projects", group: "execution", icon: "shield-check", cadence: null, app: "Projects" },
  { key: "prj_change", family: "projects", group: "execution", icon: "arrow-up-right", cadence: null, app: "Projects" },
  { key: "prj_milestone", family: "projects", group: "execution", icon: "flag-checkered", cadence: null, app: "Projects" },
  { key: "prj_acceptance", family: "projects", group: "execution", icon: "signature", cadence: null, app: "Projects" },
  { key: "prj_quality", family: "projects", group: "execution", icon: "badge-check", cadence: null, app: "Projects" },
  { key: "prj_portfolio", family: "projects", group: "portfolio", icon: "briefcase", cadence: "weekly", app: "Projects" },
  { key: "prj_at_risk", family: "projects", group: "portfolio", icon: "flag-alt", cadence: "weekly", app: "Projects" },
  { key: "prj_closure", family: "projects", group: "closure", icon: "box-circle-check", cadence: null, app: "Projects" },
  { key: "prj_post_review", family: "projects", group: "closure", icon: "search", cadence: null, app: "Projects" },
  { key: "prj_team_eval", family: "projects", group: "closure", icon: "award", cadence: null, app: "Projects" },
  { key: "inv_count", family: "inventory", icon: "clipboard", cadence: null, app: "Inventory" },
  { key: "inv_writeoff", family: "inventory", icon: "trash", cadence: null, app: "Inventory" },
  { key: "inv_movement", family: "inventory", icon: "pallet", cadence: "daily", app: "Inventory" },
  { key: "inv_low_stock", family: "inventory", icon: "box-open", cadence: "weekly", app: "Inventory" },
  { key: "fin_expenses", family: "finance", icon: "receipt", cadence: "monthly", app: "Finance" },
  { key: "fin_petty_cash", family: "finance", icon: "wallet", cadence: "monthly", app: "Expenses" },
  { key: "fin_budget", family: "finance", icon: "piggy-bank", cadence: "monthly", app: "Finance" },
  { key: "fin_cash_flow", family: "finance", icon: "bank", cadence: "monthly", app: "Finance" },
  { key: "fin_statements", family: "finance", icon: "balance-scale-left", cadence: "monthly", app: "Finance" },
  { key: "fin_month_close", family: "finance", icon: "stamp", cadence: "monthly", app: "Finance" },
  { key: "return_plan", family: "work", icon: "arrow-left", cadence: null },
  { key: "attendance_note", family: "work", icon: "fingerprint", cadence: null },
  { key: "probation_review", family: "hr", group: "hiring", icon: "award", cadence: null, requestOnly: true },
];

/** The groups a family's types show under on the Reports home, in order —
 *  each `grp.<family>.<group>`. A builder type has none: it shows after them. */
export const FAMILY_GROUPS: Partial<Record<ReportFamily, string[]>> = {
  hr: ["hiring", "time", "pay", "performance", "relations", "exit", "records"],
  projects: ["start", "execution", "portfolio", "closure"],
};

const BY_KEY = new Map(REPORT_HEADS.map((h) => [h.key, h]));
/** A built-in's head by its key — null for a builder type or a key that is gone. */
export const reportHead = (key: string): ReportTemplateHead | null => BY_KEY.get(key) ?? null;
