-- ============================================================================
-- Identity consolidation Phase 4 — cleanup status.
-- ============================================================================
-- (A) Drop retired employee private-address columns — ✅ DONE 2026-07-12
--     (applied via identity_p4_drop_employee_private_address.sql after the
--     P1b backfill + full code rewire). Nothing further to do here.
--
-- (B) Hard-dedupe duplicate contacts — NOT NEEDED right now.
--     GET /api/contacts/link-candidates returns 0 confident duplicates, so
--     there is nothing to merge or delete. If, in future, contacts get linked
--     to people and a linked contact turns out to be a pure duplicate of
--     another record, delete it MANUALLY, one reviewed id at a time, after
--     confirming nothing references it (accounts.contact_id, catalogs.contact_id,
--     quotations, invoices, ...). There is deliberately NO bulk auto-delete —
--     deleting customer/supplier rows in bulk must stay a manual, per-row
--     decision.
-- Example (fill in a specific, reviewed id):
-- DELETE FROM public.contacts WHERE id = '<reviewed-duplicate-contact-id>';
